contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Export AIMS facilities, vendors, employees, work order priority list
  mappings and devices data to PANW IoT cloud
dirtyInputs: true
id: Export AIMS maps and devices to PANW IoT
inputs: []
name: Export AIMS maps and devices to PANW IoT
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4d42b553-9df3-4fae-8d52-e0c9b1c6d288
      iscommand: false
      name: ""
      version: -1
    taskid: 4d42b553-9df3-4fae-8d52-e0c9b1c6d288
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 930,
          "y": 70
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the facilities mapping details from AIMS
      id: a7b6a65e-e353-4df1-8792-c1e4d112a2ea
      iscommand: true
      name: Get facility maps
      script: '|||aims-get-facility-maps'
      type: regular
      version: -1
    taskid: a7b6a65e-e353-4df1-8792-c1e4d112a2ea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 285,
          "y": 370
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: AIMS instance is not enabled
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: dd57f592-9021-40d2-8cb0-71ba3f8a5c62
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: dd57f592-9021-40d2-8cb0-71ba3f8a5c62
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385,
          "y": 730
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Error while getting data from AIMS
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 91bd4e9e-08e2-4b3e-876b-9dd333532c7f
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 91bd4e9e-08e2-4b3e-876b-9dd333532c7f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Successfully received data from AIMS
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 2e66a4e3-e32c-4bb4-8cee-da989cc8318e
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 2e66a4e3-e32c-4bb4-8cee-da989cc8318e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 1070
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the vendors mapping details from AIMS
      id: de605629-7765-4038-88d5-947a8115423d
      iscommand: true
      name: Get vendor maps
      script: '|||aims-get-vendor-maps'
      type: regular
      version: -1
    taskid: de605629-7765-4038-88d5-947a8115423d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 715,
          "y": 370
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the equipment type mapping details from AIMS
      id: 1c8c7db1-220d-4182-8407-26372eb42df3
      iscommand: true
      name: Get equipment type maps
      script: '|||aims-get-equipment-type-maps'
      type: regular
      version: -1
    taskid: 1c8c7db1-220d-4182-8407-26372eb42df3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1145,
          "y": 370
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the cost center mapping details from AIMS
      id: 1ff97be9-fed8-47ca-8120-56d43be09054
      iscommand: true
      name: Get cost center maps
      script: '|||aims-get-cost-center-maps'
      type: regular
      version: -1
    taskid: 1ff97be9-fed8-47ca-8120-56d43be09054
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1575,
          "y": 370
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all available devices from the AIMS and send them to PANW
        IoT cloud using the custom attributes.
      id: a3d57057-f4b1-4b8b-8f16-97442ecc7564
      iscommand: false
      name: Send AIMS devices to PANW IoT
      script: SendAIMSDevicesToPANWIoT
      type: regular
      version: -1
    taskid: a3d57057-f4b1-4b8b-8f16-97442ecc7564
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 1220
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      IntegrationName:
        simple: aims
      MetaData:
        simple: '{"FacilityMaps": ${CommandOutput.FacilityMaps}, "VendorMaps": ${CommandOutput.VendorMaps},
          "EquipmentTypeMaps": ${CommandOutput.EquipmentTypeMaps}, "CostCenterMaps":
          ${CommandOutput.CostCenterMaps}}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send metadata to PANW IOT cloud
      id: 8f9fc60e-782e-47cd-8b5b-4791a41023c4
      iscommand: true
      name: Send AIMS metadata to PANW IoT
      script: '|||panw-iot-3rd-party-report-metadata'
      type: regular
      version: -1
    taskid: 8f9fc60e-782e-47cd-8b5b-4791a41023c4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 730
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 13193131-2115-44d7-8098-b0a9d39a582e
      iscommand: false
      name: Was there an error sending metadata to PANW IoT?
      script: isError
      type: condition
      version: -1
    taskid: 13193131-2115-44d7-8098-b0a9d39a582e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 890
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "17"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 148e165f-82b4-4926-8eed-390f08c0edc4
      iscommand: false
      name: Was there an error getting data from AIMS?
      script: isError
      type: condition
      version: -1
    taskid: 148e165f-82b4-4926-8eed-390f08c0edc4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 570
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 16ae59c1-7be8-49ae-8117-a8ca454b9c52
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 16ae59c1-7be8-49ae-8117-a8ca454b9c52
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385,
          "y": 880
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "3"
      - "13"
      - "14"
      - "15"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - AIMS
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: e61a9e5b-c140-419e-88df-b79291f66d4c
      iscommand: false
      name: Is AIMS Integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: e61a9e5b-c140-419e-88df-b79291f66d4c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 185
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: be31b75e-7d2b-409a-8c36-f1bafcd9ef2e
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: be31b75e-7d2b-409a-8c36-f1bafcd9ef2e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1480
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "20_11_no": 0.41,
      "25_10_yes": 0.69
    },
    "paper": {
      "dimensions": {
        "height": 1505,
        "width": 1670,
        "x": 285,
        "y": 70
      }
    }
  }
