contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.15
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook retrieves a list of Qualys scanner appliances and scan
  profile options and report them to PANW IoT Cloud.
id: 9f880b08-3b12-4a80-86ea-29c7511a40b2
inputs: []
name: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 9f880b08-3b12-4a80-86ea-29c7511a40b2
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 446be821-225e-45e3-8c3c-43f2d1537320
      iscommand: false
      name: ""
      version: -1
    taskid: 446be821-225e-45e3-8c3c-43f2d1537320
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 690,
          "y": -370
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "13"
      "yes":
      - "24"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Qualys
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 97d74e4a-2076-489d-853f-4d2f9b131a12
      iscommand: false
      name: Is Qualys Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 97d74e4a-2076-489d-853f-4d2f9b131a12
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 690,
          "y": -225
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: c41398b4-89ab-4adb-88fc-ad22eb3a5461
      iscommand: false
      name: Was There an Error Getting Scanner and Profile Lists?
      script: isError
      type: condition
      version: -1
    taskid: c41398b4-89ab-4adb-88fc-ad22eb3a5461
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 485
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 6bb65bf1-0c2a-4604-8a93-371b5eef2bce
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 6bb65bf1-0c2a-4604-8a93-371b5eef2bce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 845
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: Successfully sent scanner and appliance list to PANW IoT Cloud
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 541b64a5-a4d0-4c47-8cf6-48b2f1e2e5bd
      iscommand: true
      name: Report Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 541b64a5-a4d0-4c47-8cf6-48b2f1e2e5bd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 670
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: qualys
      message:
        simple: Qualys Integration is not enabled
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 4a0f2759-d45a-45bd-8a0a-eeaa09ce507d
      iscommand: true
      name: Report Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 4a0f2759-d45a-45bd-8a0a-eeaa09ce507d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 230,
          "y": -50
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: Failed to send scanner and appliance list to PANW IoT Cloud
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: a22f2876-d3b2-430c-8287-df6688161eee
      iscommand: true
      name: Report Error Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: a22f2876-d3b2-430c-8287-df6688161eee
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 670
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      qualys_instance_name:
        simple: ${incident.integrationinstancename}
      scanner_sync:
        simple: ${incident.automaticallysynchronizescannerswithiotsecuritytoavoidfalsesecurityalerts}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Get list of Qualys Scanners and Profiles and write to context
      id: 7a233a35-9649-422e-8d25-1ceda6e48ac3
      iscommand: false
      name: Get A list of Qualys Scanners and Scan Profile Options
      script: GetQualysScannersAndProfiles
      type: regular
      version: -1
    taskid: 7a233a35-9649-422e-8d25-1ceda6e48ac3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 310
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "19"
      "no":
      - "20"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Qualys
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 44d1020e-5c4e-44f0-8ca3-1061297aeba6
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 44d1020e-5c4e-44f0-8ca3-1061297aeba6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 880,
          "y": 130
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 28d079a0-1350-496a-869e-3d2fa5ec2ed2
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 28d079a0-1350-496a-869e-3d2fa5ec2ed2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 310
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 5bbeace2-f219-4c70-83a2-573504626c47
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 5bbeace2-f219-4c70-83a2-573504626c47
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1250,
          "y": 310
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 7fa1c08a-9d76-4023-8fae-f34d2693861a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 7fa1c08a-9d76-4023-8fae-f34d2693861a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1060,
          "y": 500
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "27"
      "yes":
      - "18"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Qualys
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: c5880364-8d43-4080-8d34-4dc6a9832283
      iscommand: false
      name: Is Qualys  Integration Instance Enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: c5880364-8d43-4080-8d34-4dc6a9832283
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 880,
          "y": -50
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: qualys
      message:
        simple: Qualys Integration is not enabled
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: d4bead66-7450-47b7-813c-611b72e76880
      iscommand: true
      name: Report Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: d4bead66-7450-47b7-813c-611b72e76880
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1670,
          "y": 150
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1310,
        "width": 1820,
        "x": 230,
        "y": -370
      }
    }
  }
