contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to be run every 15 minutes via a job. Each run will get incremental
  updates for devices, and will update or create new endpoints in Aruba ClearPass
  with PANW IOT discovered attributes (ClearPass custom attributes).
id: d9127f9b-79ad-4be1-8f6d-8947eac4405d
inputs: []
name: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: Incremental Export to Cisco ISE - PANW IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8adc901f-9f30-4ccd-8095-d56cc2c722f6
      iscommand: false
      name: ""
      version: -1
    taskid: 8adc901f-9f30-4ccd-8095-d56cc2c722f6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "20"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba ClearPass
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 0049d291-3915-46c4-8167-4e5e2bf3addc
      iscommand: false
      name: Is Aruba ClearPass enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 0049d291-3915-46c4-8167-4e5e2bf3addc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: clearpass
      message:
        simple: Aruba ClearPass instance is not configured
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: fac52c24-dee1-411f-8551-25affe6a55b6
      iscommand: true
      name: Send disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: fac52c24-dee1-411f-8551-25affe6a55b6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      active_aruba_cp_instance:
        simple: ${incident.integrationinstancename}
      custom_attributes:
        simple: ${incident.panwiotdevicecustomattributes}
      device_maps:
        simple: ${PanwIot3rdParty.ArubaClearPassAttributes}
      increment_time:
        simple: ${incident.playbookpollinterval}
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
      sites:
        simple: ${incident.sitenames}
      tags:
        simple: ${incident.panwiotinscopetagenforcement}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f3fad096-0b2b-4f32-8c14-9c4e724c9824
      iscommand: false
      name: Send devices to Aruba ClearPass
      script: SendPANWIoTDevicesToArubaClearPass
      type: regular
      version: -1
    taskid: f3fad096-0b2b-4f32-8c14-9c4e724c9824
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 545
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "17"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: c7b65b3b-9fbe-4321-8113-29d844bbac51
      iscommand: false
      name: Was there an error while exporting devices?
      script: isError
      type: condition
      version: -1
    taskid: c7b65b3b-9fbe-4321-8113-29d844bbac51
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 720
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: clearpass
      message:
        simple: 'Failed to export PANW IoT devices to  Aruba ClearPass '
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 9ca6c580-9612-4fd4-8256-bcb78d8aafce
      iscommand: true
      name: Send error status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 9ca6c580-9612-4fd4-8256-bcb78d8aafce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 895
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: clearpass
      message:
        simple: ${PaloAltoIoTIntegrationBase.Status}
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 8dce7305-1f36-417b-820e-97e2ed532138
      iscommand: true
      name: Send success status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 8dce7305-1f36-417b-820e-97e2ed532138
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 895
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 63645885-eea9-4feb-8da7-158775de04d0
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 63645885-eea9-4feb-8da7-158775de04d0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 1070
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "21"
      "no":
      - "22"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Aruba ClearPass
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9479b9a4-2794-4a74-8692-eaf202777315
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 9479b9a4-2794-4a74-8692-eaf202777315
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 705,
          "y": 370
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: clearpass
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 68777a45-2ff8-4b66-832e-f20f5370f601
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 68777a45-2ff8-4b66-832e-f20f5370f601
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: clearpass
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 41242bbe-2bbd-4a8b-8d86-cf637fcb2809
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 41242bbe-2bbd-4a8b-8d86-cf637fcb2809
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 545
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: a490a611-db34-4456-8006-1dbffdbc0fb2
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: a490a611-db34-4456-8006-1dbffdbc0fb2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1680,
        "x": 50,
        "y": 50
      }
    }
  }
