contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Fetch data from Aruba WLAN Controller and send it to PANW IoT Platform
dirtyInputs: true
id: 15408441-f380-4125-8442-aeaedf7118ce
inputs: []
name: Import Aruba WLC devices to PANW IoT cloud
outputs: []
sourceplaybookid: Import Aruba WLC devices to PANW IoT cloud
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0a537187-9bfa-48e5-86d9-b9f4dcf650e9
      iscommand: false
      name: ""
      version: -1
    taskid: 0a537187-9bfa-48e5-86d9-b9f4dcf650e9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": -760
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "no":
      - "2"
      "yes":
      - "19"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba WLAN Controller
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 1613ffdb-ed33-4d69-8886-9f38a8f324ff
      iscommand: false
      name: Is Aruba WLC integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 1613ffdb-ed33-4d69-8886-9f38a8f324ff
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": -400
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_wlc
      message:
        simple: Aruba WLAN Controller integration is not enabled
      playbook_name:
        simple: Import Aruba WLC devices to PANW IoT cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: ddd27c44-d5a8-4566-8a02-3601904d34a8
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: ddd27c44-d5a8-4566-8a02-3601904d34a8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1230,
          "y": -250
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: bc9c0768-9af1-4577-8e1e-eca8f60d75de
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: bc9c0768-9af1-4577-8e1e-eca8f60d75de
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 470
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      aruba_wlc_instance:
        simple: ${incident.integrationinstancename}
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ba0f6d3f-92b8-4544-877e-e337f8fe47e3
      iscommand: false
      name: Send Aruba WiFi clients to PANW IoT
      script: f97053f9-65c2-4ed0-842a-feccacea18a9
      type: regular
      version: -1
    taskid: ba0f6d3f-92b8-4544-877e-e337f8fe47e3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 200
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      aruba_wlc_instance:
        simple: ${incident.integrationinstancename}
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 98c3fc74-a592-4453-806d-db4069ee9791
      iscommand: false
      name: Send Aruba Bluetooth clients to PANW IoT
      script: 63e5da9b-9f57-463e-8ba2-c4578185b6cb
      type: regular
      version: -1
    taskid: 98c3fc74-a592-4453-806d-db4069ee9791
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 200
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_wlc
      message:
        simple: Invalid integration instance name provided
      playbook_name:
        simple: Import Aruba WLC devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 88b29c5d-73b8-4698-893a-9f9ecee3b5b9
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 88b29c5d-73b8-4698-893a-9f9ecee3b5b9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1630,
          "y": -250
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "20"
      "no":
      - "21"
      "yes":
      - "16"
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - Aruba WLAN Controller
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b0224ac9-8887-460a-85d1-2d056cd34bf3
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: b0224ac9-8887-460a-85d1-2d056cd34bf3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": -200
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_wlc
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import Aruba WLC devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 6213d3dd-2f4a-4bc9-8677-1ce0a2fee8f3
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 6213d3dd-2f4a-4bc9-8677-1ce0a2fee8f3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -120,
          "y": -80
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_wlc
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import Aruba WLC devices to PANW IoT cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 9a1b4c87-a40b-45f5-8ad1-1a645797b072
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 9a1b4c87-a40b-45f5-8ad1-1a645797b072
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 310,
          "y": -70
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 818ac02b-0b1c-499d-8faf-d379f31a787a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 818ac02b-0b1c-499d-8faf-d379f31a787a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 90,
          "y": 200
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 19ab5dc4-0c86-4e35-851f-8e4b443fec1f
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 19ab5dc4-0c86-4e35-851f-8e4b443fec1f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1430,
          "y": -80
        }
      }
  "24":
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "25"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: cfa49b49-dd27-42f4-83ab-821081d4ec3b
      iscommand: false
      name: Is Aruba WLC Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: cfa49b49-dd27-42f4-83ab-821081d4ec3b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": -640
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: aruba_wlc
      message:
        simple: No Aruba WLC Integration instance passed
      playbook_name:
        simple: Import Aruba WLC devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 9a324d1d-8298-4947-890a-e602fead68c0
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 9a324d1d-8298-4947-890a-e602fead68c0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 90,
          "y": -400
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      aruba_wlc_instance:
        simple: ${incident.integrationinstancename}
      device_type:
        simple: switch
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ce4a107c-3fa7-4d34-849d-80234d112900
      iscommand: false
      name: Send Aruba WLC Switches to PanW IoT
      script: 63e5da9b-9f57-463e-8ba2-c4578185b6cb
      type: regular
      version: -1
    taskid: ce4a107c-3fa7-4d34-849d-80234d112900
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 550,
          "y": 130
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      aruba_wlc_instance:
        simple: ${incident.integrationinstancename}
      device_type:
        simple: AP
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 191e90da-241b-4de6-8160-118cc352b7bb
      iscommand: false
      name: Send Aruba WLC Access Points to PanW IoT
      script: 63e5da9b-9f57-463e-8ba2-c4578185b6cb
      type: regular
      version: -1
    taskid: 191e90da-241b-4de6-8160-118cc352b7bb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 550,
          "y": 510
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    scriptarguments:
      aruba_wlc_instance:
        simple: ${incident.integrationinstancename}
      device_type:
        simple: IAP
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9d958c5f-c017-4dc5-8dc6-0ecfed94d2ff
      iscommand: false
      name: Send Aruba WLC IAPs to PanW IoT
      script: 63e5da9b-9f57-463e-8ba2-c4578185b6cb
      type: regular
      version: -1
    taskid: 9d958c5f-c017-4dc5-8dc6-0ecfed94d2ff
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 550,
          "y": 305
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_18_#default#": 0.66,
      "1_2_no": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 1705,
        "width": 2130,
        "x": -120,
        "y": -760
      }
    }
  }
