contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.23
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Fetch IPAM subnets from SolarWinds IPAM and send it to PANW IoT Platform
id: a2c426ee-a823-4828-83b1-8c53cb6bf017
inputs: []
name: Import Solarwinds IPAM subnets to PANW IoT cloud
outputs: []
sourceplaybookid: Import MS Defender devices to PANW IoT cloud
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5ce45bc1-8492-4245-8368-ede88309918d
      iscommand: false
      name: ""
      version: -1
    taskid: 5ce45bc1-8492-4245-8368-ede88309918d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "no":
      - "2"
      "yes":
      - "19"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - SolarWinds UDT
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 1bf7f02a-1d21-4ae4-8c5a-9bf0e791a92d
      iscommand: false
      name: Is SolarWinds Orion integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 1bf7f02a-1d21-4ae4-8c5a-9bf0e791a92d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 720,
          "y": 370
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      message:
        simple: SolarWinds Orion integration is not enabled
      playbook_name:
        simple: Import Solarwinds IPAM subnets to PANW IoT cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: a6d700d6-362f-435f-858b-55413b0f83ca
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: a6d700d6-362f-435f-858b-55413b0f83ca
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 617.5,
          "y": 615
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 692239f8-ea0d-46fa-87b1-6d5002d3c4b8
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 692239f8-ea0d-46fa-87b1-6d5002d3c4b8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 1010
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      data_overwrite:
        simple: ${incident.useipamnonsitedataifthesameblockorsubnetisiniotsecurity}
      instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f0a58740-f785-4a64-8f6f-f948e6257831
      iscommand: false
      name: Send SolarWinds IPAM Subnets to PANW IoT
      script: 358c1c93-3141-4f13-878d-7ffa27562df7
      type: regular
      version: -1
    taskid: f0a58740-f785-4a64-8f6f-f948e6257831
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 800
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      message:
        simple: Invalid integration instance name provided
      playbook_name:
        simple: Import Solarwinds IPAM subnets to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 8c3cc8e4-6ece-4486-8390-090746bfeb38
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 8c3cc8e4-6ece-4486-8390-090746bfeb38
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 207.5,
          "y": 615
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "27"
      "no":
      - "21"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - SolarWinds UDT
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 29453116-fc77-4909-8e25-65a3a7fd1c02
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 29453116-fc77-4909-8e25-65a3a7fd1c02
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1120,
          "y": 550
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: solarwinds_ipam
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import Solarwinds IPAM subnets to PANW IoT cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: bb217649-db87-4201-8edd-7b408bf12b9e
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: bb217649-db87-4201-8edd-7b408bf12b9e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 920,
          "y": 810
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: ab258d05-8e36-4341-8d21-94d0e3201777
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ab258d05-8e36-4341-8d21-94d0e3201777
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 830,
          "y": 1220
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 018f4c08-b81c-4772-83ea-ae8e4d657fef
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 018f4c08-b81c-4772-83ea-ae8e4d657fef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": 970
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "25"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 84e4559e-47fc-4211-8044-d2544cdc8da8
      iscommand: false
      name: Is Solarwinds Orion Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: 84e4559e-47fc-4211-8044-d2544cdc8da8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      message:
        simple: No SolarWinds Integration instance passed
      playbook_name:
        simple: Import Solarwinds IPAM subnets to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: dc884ea6-52b5-4c56-8d41-021910141acf
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: dc884ea6-52b5-4c56-8d41-021910141acf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -150,
          "y": 420
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: solarwinds_ipam
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import Solarwinds IPAM subnets to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 27ef7ae4-ccb0-479e-8cc8-fc2bd95c2919
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 27ef7ae4-ccb0-479e-8cc8-fc2bd95c2919
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1790,
          "y": 800
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_18_#default#": 0.85,
      "1_2_no": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 1265,
        "width": 2320,
        "x": -150,
        "y": 50
      }
    }
  }
