contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook check for finished PANW IoT initiated scans, generates
  reports.
id: 32228f80-b194-4e16-87bd-8693927c2fab
inputs: []
name: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 39ba7f39-a1da-44c0-863f-38ea540f24ea
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: aa229dcb-a211-4003-867f-ce8b827f6ba2
      iscommand: false
      name: ""
      version: -1
    taskid: aa229dcb-a211-4003-867f-ce8b827f6ba2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "26"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Rapid7 Nexpose
      using:
        simple: PANW IoT 3rd Party Rapid7 Nexpose Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 0524866c-5060-4f5f-8372-10684650cc8f
      iscommand: false
      name: Is Rapid7 Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 0524866c-5060-4f5f-8372-10684650cc8f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: rapid7
      message:
        simple: Rapid7 integration is not enabled
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: e8cd8525-0da3-41a3-87b8-2a044e5967a8
      iscommand: true
      name: Report disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e8cd8525-0da3-41a3-87b8-2a044e5967a8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 415e649f-402d-47aa-8da2-1a6c240de8e0
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 415e649f-402d-47aa-8da2-1a6c240de8e0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 1070
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      rapid7_instance:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 37de1cb4-9d6f-4733-8187-b1b937f13e52
      iscommand: false
      name: Launch Rapid7 reports for finished scans
      script: LaunchReportsforFinishedPANWIoTRapid7VulnerabilityScans
      type: regular
      version: -1
    taskid: 37de1cb4-9d6f-4733-8187-b1b937f13e52
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 545
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "30"
      "yes":
      - "20"
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
      path:
        simple: Nexpose.LaunchReportfailStatus
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks for errors in a given task. If found, write it to the path
        provided as an argument.
      id: 074d82cc-0201-4947-802e-cdacbe9ebe41
      iscommand: false
      name: Did the Report Launch Fail?
      script: ba739f62-3f46-417e-809b-3c73715e062d
      type: condition
      version: -1
    taskid: 074d82cc-0201-4947-802e-cdacbe9ebe41
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 720
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobid}
      message:
        simple: ${Nexpose.LaunchReportfailStatus}
      scan_type:
        simple: rapid7
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Upload reports (PDF + XML) for specified scan to IoT Cloud
      id: 2ceba1ce-dc93-40ba-8f02-31a863dc3008
      iscommand: true
      name: Report Launch Error as Event
      script: '|||panw-iot-3rd-party-upload-vulnerability-scan-report'
      type: regular
      version: -1
    taskid: 2ceba1ce-dc93-40ba-8f02-31a863dc3008
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1022.5,
          "y": 895
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: rapid7
      message:
        simple: ${Nexpose.LaunchReportfailStatus}
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 7af2f22c-a459-4acf-8b2f-f3b4b60da5c2
      iscommand: true
      name: Report Launch Errors to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 7af2f22c-a459-4acf-8b2f-f3b4b60da5c2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1452.5,
          "y": 895
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 31056383-d0fc-4c8f-8831-a5d7edf20c81
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 31056383-d0fc-4c8f-8831-a5d7edf20c81
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1070
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "27"
      "no":
      - "28"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Rapid7 Nexpose
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ec3eac55-2b03-44f6-8732-af57bf423e51
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: ec3eac55-2b03-44f6-8732-af57bf423e51
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 370
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: rapid7
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 30d076ce-fcc4-489c-83cb-4aa550bb5fdf
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 30d076ce-fcc4-489c-83cb-4aa550bb5fdf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "28":
    continueonerror: true
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: rapid7
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: f61c47d8-d9e4-4506-8035-db80e0eeb8b6
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: f61c47d8-d9e4-4506-8035-db80e0eeb8b6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 545
        }
      }
  "29":
    continueonerror: true
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: b4ee7937-b077-4ec7-8e7c-098b08315719
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: b4ee7937-b077-4ec7-8e7c-098b08315719
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 720
        }
      }
  "30":
    continueonerror: true
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: rapid7
      message:
        simple: Report Launch success
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: a87e9d36-b8e3-404a-8fbf-57509bb5574b
      iscommand: true
      name: Report Launch Success to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: a87e9d36-b8e3-404a-8fbf-57509bb5574b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1782.5,
        "x": 50,
        "y": 50
      }
    }
  }
