contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.17
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: The playbook will fetch vulnerabilities from the MS Defender XDR and
  send it to the Palo Alto IoT platform via a REST API call.
dirtyInputs: true
id: 97923dc8-3b66-40d9-8302-7a5d52b8211c
inputs: []
name: Import MS Defender Vulnerabilities to PANW IoT cloud
outputs: []
sourceplaybookid: Import Defender WLC devices to PANW IoT cloud
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6cd81ca1-eaec-428a-87f1-90b3191e5295
      iscommand: false
      name: ""
      version: -1
    taskid: 6cd81ca1-eaec-428a-87f1-90b3191e5295
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "no":
      - "2"
      "yes":
      - "19"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - MS Defender XDR
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: c24f5dc4-7ec1-449e-8a36-e74630eb46b3
      iscommand: false
      name: Is MS Defender integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: c24f5dc4-7ec1-449e-8a36-e74630eb46b3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 730,
          "y": 410
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: MS Defender integration is not enabled
      playbook_name:
        simple: Import MS Defender Vulnerabilities to PANW IoT cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 75582a6d-3edb-47c0-8805-94299554ed8c
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 75582a6d-3edb-47c0-8805-94299554ed8c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 730,
          "y": 585
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 8721e388-62ac-4d73-8ac2-38f3beaa3b29
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8721e388-62ac-4d73-8ac2-38f3beaa3b29
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1902.5,
          "y": 895
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      active_defender_instance:
        simple: ${incident.integrationinstancename}
      poll_interval:
        simple: ${incident.pollingdurationindays}
      severities:
        simple: ${incident.importvulnerabilitiesbycveseveritylevels}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 289553c9-fa11-44e7-89b2-2bc76508f388
      iscommand: false
      name: Send MS Defender vulnerabilities to PANW IoT
      script: SendMSDefenderVulnerabilitiesToPANWIoT
      type: regular
      version: -1
    taskid: 289553c9-fa11-44e7-89b2-2bc76508f388
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1902.5,
          "y": 720
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: Invalid integration instance name provided
      playbook_name:
        simple: Import MS Defender Vulnerabilities to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 94bcc4c7-f4ff-4eac-8e59-aa09320b2e47
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 94bcc4c7-f4ff-4eac-8e59-aa09320b2e47
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 257.5,
          "y": 545
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "20"
      "no":
      - "21"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - MS Defender XDR
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2609af02-6fe7-4b39-8070-b2406df36b95
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 2609af02-6fe7-4b39-8070-b2406df36b95
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1242.5,
          "y": 545
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import MS Defender Vulnerabilities to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 89b2e1e9-40db-4a9a-8763-bbf12a2d857a
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 89b2e1e9-40db-4a9a-8763-bbf12a2d857a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1032.5,
          "y": 720
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import MS Defender Vulnerabilities to PANW IoT cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: e178eeb5-25cc-4022-86ab-8cc8b46b2aa7
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: e178eeb5-25cc-4022-86ab-8cc8b46b2aa7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1462.5,
          "y": 720
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: f6957023-411d-4a17-8d11-a9ffe3f85834
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f6957023-411d-4a17-8d11-a9ffe3f85834
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 960
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 7663ff8e-8285-498b-8646-8acec4faa1ea
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 7663ff8e-8285-498b-8646-8acec4faa1ea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 540,
          "y": 760
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "25"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: e7927c5e-40a7-4955-8c6a-dbf095934f34
      iscommand: false
      name: Is MS Defender Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: e7927c5e-40a7-4955-8c6a-dbf095934f34
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: No MS Defender Integration instance passed
      playbook_name:
        simple: Import MS Defender Vulnerabilities to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: a65deb55-4022-49cb-8987-b01a4c8c164d
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: a65deb55-4022-49cb-8987-b01a4c8c164d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -150,
          "y": 420
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_18_#default#": 0.85,
      "1_2_no": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 1005,
        "width": 2432.5,
        "x": -150,
        "y": 50
      }
    }
  }
