contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.17
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Fetch data from MS Defender and send it to PANW IoT Platform
id: 948611d3-2930-44b4-84e3-7a08a0b46d72
inputs: []
name: Import MS Defender devices to PANW IoT cloud
outputs: []
sourceplaybookid: Import MS Defender devices to PANW IoT cloud
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6e92d471-ef71-43c9-8698-c95ac85b7c60
      iscommand: false
      name: ""
      version: -1
    taskid: 6e92d471-ef71-43c9-8698-c95ac85b7c60
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "no":
      - "2"
      "yes":
      - "19"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - MS Defender XDR
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 0dbea61a-4b4d-4e1c-8adb-7e96c8d32817
      iscommand: false
      name: Is MS Defender integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 0dbea61a-4b4d-4e1c-8adb-7e96c8d32817
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 730,
          "y": 410
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: MS Defender integration is not enabled
      playbook_name:
        simple: Import MS Defender devices to PANW IoT cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: dc9aa814-c8e6-46e1-847d-08b6c598e638
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: dc9aa814-c8e6-46e1-847d-08b6c598e638
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 730,
          "y": 585
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: d4366c0e-0f8c-4771-8d6f-ccbb43ff5c71
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d4366c0e-0f8c-4771-8d6f-ccbb43ff5c71
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1902.5,
          "y": 895
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      active_defender_instance:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5606cd30-4580-44f1-813a-a8980f3c6439
      iscommand: false
      name: Send MS Defender devices to PANW IoT
      script: SendMSDefenderDevicesToPANWIoT
      type: regular
      version: -1
    taskid: 5606cd30-4580-44f1-813a-a8980f3c6439
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1902.5,
          "y": 720
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: Invalid integration instance name provided
      playbook_name:
        simple: Import MS Defender devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 4b0596e3-9cae-4811-826c-6422caff23b7
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 4b0596e3-9cae-4811-826c-6422caff23b7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 257.5,
          "y": 545
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "20"
      "no":
      - "21"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - MS Defender XDR
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ac30182b-e49f-40d9-8355-86e9b2b4dc87
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: ac30182b-e49f-40d9-8355-86e9b2b4dc87
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1242.5,
          "y": 545
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import MS Defender devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 937228f4-66ca-4079-846d-51b75a09f037
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 937228f4-66ca-4079-846d-51b75a09f037
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1032.5,
          "y": 720
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import MS Defender devices to PANW IoT cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: c74d27e4-84ab-4c77-80bf-9c50761b8898
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: c74d27e4-84ab-4c77-80bf-9c50761b8898
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1462.5,
          "y": 720
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: d612a15f-2fb0-462b-86df-9e62c8b52619
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d612a15f-2fb0-462b-86df-9e62c8b52619
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 960
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 41b78946-4b4d-4469-881b-5e1942e6b4f7
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 41b78946-4b4d-4469-881b-5e1942e6b4f7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 540,
          "y": 760
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "25"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: c11ba9d3-6af6-4711-8e3c-4a999744f442
      iscommand: false
      name: Is MS Defender Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: c11ba9d3-6af6-4711-8e3c-4a999744f442
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ms_defender_xdr
      message:
        simple: No MS Defender Integration instance passed
      playbook_name:
        simple: Import MS Defender devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: eb21577f-6840-4f01-8047-1bc45bd504fd
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: eb21577f-6840-4f01-8047-1bc45bd504fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -150,
          "y": 420
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_18_#default#": 0.85,
      "1_2_no": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 1005,
        "width": 2432.5,
        "x": -150,
        "y": 50
      }
    }
  }
