contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 2.0.11
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Alert to SIEM.
id: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
inputs: []
name: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "PANW IoT 3rd Party
    SIEM Integration - Alert/Vulnerability"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f696e852-4adf-4b83-8cbb-2c2ac0723b42
      iscommand: false
      name: ""
      version: -1
    taskid: f696e852-4adf-4b83-8cbb-2c2ac0723b42
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 440,
          "y": -250
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 2818150e-cf09-4a3b-8213-3f86ddd5a22c
      iscommand: false
      name: Is Syslog Sender(SIEM) Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 2818150e-cf09-4a3b-8213-3f86ddd5a22c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 110
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: Syslog Sender (SIEM) instance is not enabled
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 0efd9a45-4d1d-4a55-82e1-83f45c571e2e
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 0efd9a45-4d1d-4a55-82e1-83f45c571e2e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 200,
          "y": 410
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${incident.zb_ticketid}
      asset_type:
        simple: ${incident.asset_type}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: For a given a asset ID (alert-id, vulnerability-id or mac-address)
        returns the asset details.
      id: 954ba0c8-57a8-4b10-8a11-d9295b9adbb2
      iscommand: true
      name: Get PANW IoT Asset details
      script: '|||panw-iot-3rd-party-get-single-asset'
      type: regular
      version: -1
    taskid: 954ba0c8-57a8-4b10-8a11-d9295b9adbb2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 660,
          "y": 400
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "5"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 4895d950-9068-4e0d-8c2c-cf45a8ba9560
      iscommand: false
      name: Was there an error getting asset details?
      script: isError
      type: condition
      version: -1
    taskid: 4895d950-9068-4e0d-8c2c-cf45a8ba9560
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 660,
          "y": 570
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 8c87fa43-3d06-4a9e-8f16-8fb007520647
      iscommand: false
      name: Does the asset exist?
      script: Exists
      type: condition
      version: -1
    taskid: 8c87fa43-3d06-4a9e-8f16-8fb007520647
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 880,
          "y": 750
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: Failed to get Alert (${incident.zb_ticketid}) from IoT cloud.
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 062f28c7-9c16-4c8b-8bac-6b6b5591764f
      iscommand: true
      name: Send error status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 062f28c7-9c16-4c8b-8bac-6b6b5591764f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 410,
          "y": 760
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_list:
        simple: ${PanwIot3rdParty.SingleAsset}
      asset_type:
        simple: ${incident.asset_type}
      output_format:
        simple: SIEM
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: For a given asset (alert, device, vuln) converts it to 3rd party
        format.
      id: 15db9c7b-5164-4a43-82c5-d151c90a4bd6
      iscommand: true
      name: Convert asset to CEF format
      script: '|||panw-iot-3rd-party-convert-assets-to-external-format'
      type: regular
      version: -1
    taskid: 15db9c7b-5164-4a43-82c5-d151c90a4bd6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1120
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: No Alert found with given ID  (${incident.zb_ticketid}).
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 2a512c4e-dd58-471e-867e-0f551a52a379
      iscommand: true
      name: send status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 2a512c4e-dd58-471e-867e-0f551a52a379
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 640,
          "y": 930
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.AlertCEFSyslogs}${PanwIot3rdParty.VulnerabilityCEFSyslogs}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 3d6ab764-c941-4893-874a-35859bac6044
      iscommand: false
      name: Is there any syslog (CEF) available?
      script: Exists
      type: condition
      version: -1
    taskid: 3d6ab764-c941-4893-874a-35859bac6044
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1120,
          "y": 1280
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: ${PanwIot3rdParty.AlertCEFSyslogs}${PanwIot3rdParty.VulnerabilityCEFSyslogs}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a message to Syslog.
      id: f272f170-7d5f-455f-8588-707427e06370
      iscommand: true
      name: 'Send asset syslog '
      script: '|||syslog-send'
      type: regular
      version: -1
    taskid: f272f170-7d5f-455f-8588-707427e06370
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1310,
          "y": 1460
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: Alert ID  (${incident.zb_ticketid}) not valid for CEF conversion.
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 39d7f08e-f0c8-42d6-8bda-6d407feb3beb
      iscommand: true
      name: Send error status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 39d7f08e-f0c8-42d6-8bda-6d407feb3beb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1460
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: Successfully sent Alert (${incident.zb_ticketid}) to SIEM
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 5c0efb59-faea-4534-810c-c8527b18c2f9
      iscommand: true
      name: Send success status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 5c0efb59-faea-4534-810c-c8527b18c2f9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1310,
          "y": 1600
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 4d55086b-cb0c-4217-8287-3b9589734f12
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4d55086b-cb0c-4217-8287-3b9589734f12
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1750
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "13"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      asset:
        simple: ${PanwIot3rdParty.SingleAsset}
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 35c4bf38-87a2-451b-8cd9-2a8fda28a9ea
      iscommand: false
      name: Does severity level match configuration filter?
      script: 2ef6f81e-1456-41a9-8ce5-3b6ebf04ea9d
      type: condition
      version: -1
    taskid: 35c4bf38-87a2-451b-8cd9-2a8fda28a9ea
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1120,
          "y": 920
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2095,
        "width": 1490,
        "x": 200,
        "y": -250
      }
    }
  }
