contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Export AIMS facilities, vendors, employees, work order priority list
  mappings and devices data to PANW IoT cloud
id: Export AIMS maps and devices to PANW IoT
inputs: []
name: Export AIMS maps and devices to PANW IoT
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1aecbc1f-df6e-4764-8295-fd3ac41e2a6b
      iscommand: false
      name: ""
      version: -1
    taskid: 1aecbc1f-df6e-4764-8295-fd3ac41e2a6b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 930,
          "y": 70
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the facilities mapping details from AIMS
      id: e2fee46a-f619-4485-82da-82f8ccfb10fe
      iscommand: true
      name: Get facility maps
      script: '|||aims-get-facility-maps'
      type: regular
      version: -1
    taskid: e2fee46a-f619-4485-82da-82f8ccfb10fe
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 285,
          "y": 370
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: AIMS instance is not enabled
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 9b375ab7-8e71-4430-8c51-875f407547f9
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 9b375ab7-8e71-4430-8c51-875f407547f9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385,
          "y": 730
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Error while getting data from AIMS
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: a32e3836-1957-423d-8c82-dbde253c471e
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: a32e3836-1957-423d-8c82-dbde253c471e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Successfully received data from AIMS
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: caa694b1-1077-45ed-864c-23cf657efd7e
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: caa694b1-1077-45ed-864c-23cf657efd7e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 1070
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the vendors mapping details from AIMS
      id: 26df5108-5a35-4e1a-8cba-b73a328ce65a
      iscommand: true
      name: Get vendor maps
      script: '|||aims-get-vendor-maps'
      type: regular
      version: -1
    taskid: 26df5108-5a35-4e1a-8cba-b73a328ce65a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 715,
          "y": 370
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the equipment type mapping details from AIMS
      id: ec807191-c04a-4567-8683-7359bbbbc3fa
      iscommand: true
      name: Get equipment type maps
      script: '|||aims-get-equipment-type-maps'
      type: regular
      version: -1
    taskid: ec807191-c04a-4567-8683-7359bbbbc3fa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1145,
          "y": 370
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the cost center mapping details from AIMS
      id: 8e42db96-a29c-4fe2-8e35-5220ffa185dc
      iscommand: true
      name: Get cost center maps
      script: '|||aims-get-cost-center-maps'
      type: regular
      version: -1
    taskid: 8e42db96-a29c-4fe2-8e35-5220ffa185dc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1575,
          "y": 370
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all available devices from the AIMS and send them to PANW
        IoT cloud using the custom attributes.
      id: 972c8e49-1d64-41f9-86e4-302629f35bb3
      iscommand: false
      name: Send AIMS devices to PANW IoT
      script: SendAIMSDevicesToPANWIoT
      type: regular
      version: -1
    taskid: 972c8e49-1d64-41f9-86e4-302629f35bb3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 1220
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      IntegrationName:
        simple: aims
      MetaData:
        simple: '{"FacilityMaps": ${CommandOutput.FacilityMaps}, "VendorMaps": ${CommandOutput.VendorMaps},
          "EquipmentTypeMaps": ${CommandOutput.EquipmentTypeMaps}, "CostCenterMaps":
          ${CommandOutput.CostCenterMaps}}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send metadata to PANW IOT cloud
      id: 376f34cd-7ed3-4afd-8e80-cb7cd1c6c5b7
      iscommand: true
      name: Send AIMS metadata to PANW IoT
      script: '|||panw-iot-3rd-party-report-metadata'
      type: regular
      version: -1
    taskid: 376f34cd-7ed3-4afd-8e80-cb7cd1c6c5b7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 730
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 28ddc817-1534-4081-8c57-5a37def084c0
      iscommand: false
      name: Was there an error sending metadata to PANW IoT?
      script: isError
      type: condition
      version: -1
    taskid: 28ddc817-1534-4081-8c57-5a37def084c0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 890
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "17"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: cb26b709-3244-4577-8f88-f5a1d69c2516
      iscommand: false
      name: Was there an error getting data from AIMS?
      script: isError
      type: condition
      version: -1
    taskid: cb26b709-3244-4577-8f88-f5a1d69c2516
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 570
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: a2aeaeaa-c3ad-4574-8a58-076b6ae9bbb0
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: a2aeaeaa-c3ad-4574-8a58-076b6ae9bbb0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385,
          "y": 880
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "3"
      - "13"
      - "14"
      - "15"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - AIMS
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: e759d9c3-11c5-4eef-8ac0-48f9e4998043
      iscommand: false
      name: Is AIMS Integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: e759d9c3-11c5-4eef-8ac0-48f9e4998043
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 185
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 453add93-7f68-4d23-89d2-e0a652b9a17a
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 453add93-7f68-4d23-89d2-e0a652b9a17a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1480
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "20_11_no": 0.41,
      "25_10_yes": 0.69
    },
    "paper": {
      "dimensions": {
        "height": 1505,
        "width": 1670,
        "x": 285,
        "y": 70
      }
    }
  }
