contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 6c5ee2fe-98bf-40ab-8ab0-c624a765cab3
inputs: []
name: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT Cloud
outputs: []
sourceplaybookid: 985135c8-3cc9-43b1-8783-926b487a076d
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4ee35707-c704-4ee3-8f41-3332d731b8a6
      iscommand: false
      name: ""
      version: -1
    taskid: 4ee35707-c704-4ee3-8f41-3332d731b8a6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 20
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "11"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - BlueCat IPAM
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: a36718d8-ffba-4b83-86cf-beb5ba69c32a
      iscommand: false
      name: Is BlueCat enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: a36718d8-ffba-4b83-86cf-beb5ba69c32a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 960,
          "y": 400
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ipam_bluecat
      message:
        simple: BlueCat IPAM integration is not enabled
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 7e412035-940e-4b5a-8a3e-4b62b9b4f3da
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 7e412035-940e-4b5a-8a3e-4b62b9b4f3da
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 280,
          "y": 570
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: fc0a1071-a14c-40a3-8033-34c3b582e33d
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: fc0a1071-a14c-40a3-8033-34c3b582e33d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": 770
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      bluecat_instance_name:
        simple: ${incident.integrationinstancename}
      data_overwrite:
        simple: ${incident.useipamnonsitedataifthesameblockorsubnetisiniotsecurity}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2f2aba82-5664-4bdb-81cf-56305e69bb43
      iscommand: false
      name: Export BlueCat Subnet Info and Update PANW IoT cloud
      script: BlueCatIPAMGetSubnetNetwork
      type: regular
      version: -1
    taskid: 2f2aba82-5664-4bdb-81cf-56305e69bb43
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 720
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: ad9d64dd-dd72-46c9-899c-d71879590529
      iscommand: false
      name: Was there an error when sending devices to PANW IoT Cloud?
      script: isError
      type: condition
      version: -1
    taskid: ad9d64dd-dd72-46c9-899c-d71879590529
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 895
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ipam_bluecat
      message:
        simple: 'Error: Failed to do a bulk export BlueCat IPAM Data'
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: c2242c40-5286-4ea9-8057-d048104c5799
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: c2242c40-5286-4ea9-8057-d048104c5799
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 1070
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 56a3aff3-f612-4e2e-88ef-4d129a9593e4
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 56a3aff3-f612-4e2e-88ef-4d129a9593e4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 1245
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 8331fbad-508f-4438-812b-c6797d72a6aa
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8331fbad-508f-4438-812b-c6797d72a6aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1245
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ipam_bluecat
      message:
        simple: Successfully exported BlueCat IPAM Data
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 8cee5081-eeb7-4239-8bdd-59d44e1db332
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 8cee5081-eeb7-4239-8bdd-59d44e1db332
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1070
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "no":
      - "12"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - BlueCat IPAM
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 612a8094-0649-4cd9-83e4-9177e865682b
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 612a8094-0649-4cd9-83e4-9177e865682b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 980,
          "y": 610
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ipam_bluecat
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Bulk Import of subnet network info from BlueCat IPAM to PANW IoT Cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 93f6e772-3024-4295-86b5-819cfad8455e
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 93f6e772-3024-4295-86b5-819cfad8455e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 850
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: c20cb033-e4eb-4435-8560-a0b1de1b65f9
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: c20cb033-e4eb-4435-8560-a0b1de1b65f9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1020
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ipam_bluecat
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Bulk Import of subnet network info from BlueCat IPAM to PANW IoT Cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: bf28201a-8429-4ed0-8189-70ace1425fb1
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: bf28201a-8429-4ed0-8189-70ace1425fb1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 670,
          "y": 850
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "16"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 751b97cc-1c99-44df-8a41-e9bc53eb2e46
      iscommand: false
      name: Is BlueCat IPAM Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: 751b97cc-1c99-44df-8a41-e9bc53eb2e46
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 175
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ipam_bluecat
      message:
        simple: No BlueCat IPAM integration is passed
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: eda11040-be87-404d-86d2-75c8d97c1b66
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: eda11040-be87-404d-86d2-75c8d97c1b66
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -140,
          "y": 530
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "15_16_no": 0.14
    },
    "paper": {
      "dimensions": {
        "height": 1320,
        "width": 2300,
        "x": -140,
        "y": 20
      }
    }
  }
