contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 1.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook is meant to be triggered by incident type from PANW IoT
  Cloud. The custom fields (jobid, ip, scanner, scanType and profile) are used to
  launch a scan on Qualys
id: 38d9fa0d-80ca-4d0b-8424-4d388ebce25b
inputs: []
name: Qualys Scan Launch - PANW IoT 3rd Party Integration
outputs:
- contextPath: incident
  type: unknown
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d7dbf7e9-5142-4350-8471-d0bde0c4808d
      iscommand: false
      name: ""
      version: -1
    taskid: d7dbf7e9-5142-4350-8471-d0bde0c4808d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 33cb9d99-e754-4ed7-8e55-5ed6a3f652ec
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 33cb9d99-e754-4ed7-8e55-5ed6a3f652ec
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "7"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Qualys
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: f51b3a20-cf20-4e3b-8432-bcaa733e79d9
      iscommand: false
      name: Is Qualys Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: f51b3a20-cf20-4e3b-8432-bcaa733e79d9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: Qualys integration is not enabled
      playbook_name:
        simple: Qualys Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: d1257a5e-e885-4bfa-83f6-b7907e5e5e60
      iscommand: true
      name: Report disabled status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: d1257a5e-e885-4bfa-83f6-b7907e5e5e60
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${incident.ip}
      iscanner_name:
        simple: ${incident.scanner}
      option_title:
        simple: ${incident.profile}
      scan_title:
        simple: panw_iot_${incident.ip}_scan_${incident.jobid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ' launch vulnerability scans in the user’s account.'
      id: 1875306e-5966-44d4-8c93-5067a15d9bd2
      iscommand: true
      name: Launch Qualys VM vulnerability Scan
      script: '|||qualys-vm-scan-launch'
      type: regular
      version: -1
    taskid: 1875306e-5966-44d4-8c93-5067a15d9bd2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: ${Qualys.scanLaunchfailStatus}
      playbook_name:
        simple: Qualys Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 78a3883c-f08c-49d3-87ab-3e349d76ca7a
      iscommand: true
      name: Report Scan Launch Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 78a3883c-f08c-49d3-87ab-3e349d76ca7a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: QualysLaunchedScans
      operation:
        simple: insert
      value:
        simple: ${Qualys.Scan.Reference}_${incident.ip}_${incident.jobid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: List operations, will create a new list if list does not exist
      id: 6266a0e5-7551-4c8d-8bc8-693f1ed30196
      iscommand: false
      name: Update Qualys launched scan cache
      script: PANWIoTLaunchedVulnerabilityScanCacheOperations
      type: regular
      version: -1
    taskid: 6266a0e5-7551-4c8d-8bc8-693f1ed30196
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "12"
      "yes":
      - "9"
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
      path:
        simple: Qualys.scanLaunchfailStatus
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks for errors in a given task. If found, write it to the path
        provided as an argument.
      id: 46e22052-9499-4747-8c0c-5700b106ceb5
      iscommand: false
      name: Did the Scan Launch Fail?
      script: ea2fa025-47c1-420b-895b-d5b62cfab9b3
      type: condition
      version: -1
    taskid: 46e22052-9499-4747-8c0c-5700b106ceb5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobid}
      message:
        simple: ${Qualys.scanLaunchfailStatus}
      scan_type:
        simple: qualys
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Upload reports (PDF + XML) for specified scan to IoT Cloud
      id: a254c6d4-7e06-4db1-8e19-6274104b2dff
      iscommand: true
      name: Report Scan Launch Error As Event
      script: '|||panw-iot-3rd-party-upload-vulnerability-scan-report'
      type: regular
      version: -1
    taskid: a254c6d4-7e06-4db1-8e19-6274104b2dff
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 895
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: Successfully launched scan for ip ${incident.ip}
      playbook_name:
        simple: Qualys Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: ba432654-3b02-4cf1-8280-85c74c9988f5
      iscommand: true
      name: Report Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: ba432654-3b02-4cf1-8280-85c74c9988f5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
