contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    itemVersion: 2.6.38
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  ## Containment Plan - Clear User Sessions

  This playbook is a sub-playbook within the containment plan playbook.
  The playbook uses the 'Okta v2' and 'MSGraph User' integrations to clear user sessions.
id: Containment Plan - Clear User Sessions
inputSections:
- description: Generic group for inputs.
  inputs:
  - ClearUserSessions
  - Username
  - IAMUserDomain
  name: General (Inputs group)
inputs:
- description: Set to 'True' to clear the user active sessions.
  key: ClearUserSessions
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: The username to disable.
  key: Username
  playbookInputQuery: null
  required: false
  value: {}
- description: The Okta IAM users domain. The domain will be appended to the username.
    E.g., username@IAMUserDomain.
  key: IAMUserDomain
  playbookInputQuery: null
  required: false
  value: {}
name: Containment Plan - Clear User Sessions
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f2a578bb-7b26-4477-8391-2e40e77fb9d5
      iscommand: false
      name: ""
      version: -1
    taskid: f2a578bb-7b26-4477-8391-2e40e77fb9d5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 770,
          "y": -150
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      userId:
        complex:
          accessor: ID
          root: Account
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: |-
        Removes all active identity provider sessions. This forces the user to authenticate on the next operation. Optionally revokes OpenID Connect and OAuth refresh and access tokens issued to the user.
        For more information and examples:
        https://developer.okta.com/docs/reference/api/users/#user-sessions
      id: 965b6bb7-8584-4ee9-86be-705ca7951fba
      iscommand: true
      name: Okta clear user sessions
      script: '|||okta-clear-user-sessions'
      type: regular
      version: -1
    taskid: 965b6bb7-8584-4ee9-86be-705ca7951fba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 985
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 581b7da6-4c88-41a6-8175-a2116add396c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 581b7da6-4c88-41a6-8175-a2116add396c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 770,
          "y": 1320
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        simple: ${OktaUsersSessionToClear}
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Fetches information for a single user. You must enter one or more
        parameters for the command to run.
      id: ea29c7c0-e180-4c2e-8593-3948400c532e
      iscommand: true
      name: Get Okta user ID
      script: '|||okta-get-user'
      type: regular
      version: -1
    taskid: ea29c7c0-e180-4c2e-8593-3948400c532e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 590
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: UsersSessionCleared
      value:
        complex:
          accessor: Username
          root: Account
    separatecontext: false
    skipunavailable: true
    task:
      brand: Builtin
      description: commands.local.cmd.set.parent.alert.context
      id: bda090c7-6749-46e5-8453-31f56d8b778c
      iscommand: true
      name: Set the username to the Alert context
      script: Builtin|||setParentIncidentContext
      type: regular
      version: -1
    taskid: bda090c7-6749-46e5-8453-31f56d8b778c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 1145
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: OktaUsersSessionToClear
      value:
        complex:
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.Username
              operator: notContainsGeneral
              right:
                value:
                  simple: administrator
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.Username
              operator: notContainsGeneral
              right:
                value:
                  simple: system
          root: inputs.Username
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: cceb9ed8-97d2-4b2a-8688-c02b46be05a6
      iscommand: false
      name: Set users to clear the session with Okta
      script: Set
      type: regular
      version: -1
    taskid: cceb9ed8-97d2-4b2a-8688-c02b46be05a6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 410
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Okta v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'.
      id: 4025c083-2630-4171-889e-5f05b1fc51eb
      iscommand: false
      name: Is Okta enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 4025c083-2630-4171-889e-5f05b1fc51eb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 530,
          "y": 210
        }
      }
  "17":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.ClearUserSessions
          operator: isEqualString
          right:
            value:
              simple: "True"
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Username
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "15"
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to clear the user sessions based on the input values.
      id: f1d3409f-55f4-4804-8a48-354971cae04e
      iscommand: false
      name: Should clear the user sessions?
      type: condition
      version: -1
    taskid: f1d3409f-55f4-4804-8a48-354971cae04e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 770,
          "y": 0
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "27"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Microsoft Graph User
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'.
      id: 64c30075-eba8-4222-8251-cf075b841898
      iscommand: false
      name: Is MsGraphUser enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 64c30075-eba8-4222-8251-cf075b841898
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 210
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      user:
        simple: ${MsGraphUsersSessionToClear}
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: |-
        Retrieves the properties and relationships of a user object. For more information, visit: https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0).
        Permissions: - User.Read (Delegated) - User.Read.All (Application).
      id: f0ed1f31-5552-423b-8d43-44a4e3b69879
      iscommand: true
      name: Get MsGraph user ID
      script: '|||msgraph-user-get'
      type: regular
      version: -1
    taskid: f0ed1f31-5552-423b-8d43-44a4e3b69879
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 590
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      user:
        simple: ${MSGraphUser.ID}
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: |-
        Revoke a user session - Invalidates all the refresh tokens issued to applications for a user.
        Permission: Directory.AccessAsUser.All(Delegated).
      id: c82fc95c-577d-407a-8e4c-127b17c05843
      iscommand: true
      name: MSGraph clear user sessions
      script: '|||msgraph-user-session-revoke'
      type: regular
      version: -1
    taskid: c82fc95c-577d-407a-8e4c-127b17c05843
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 985
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: UsersSessionCleared
      value:
        simple: ${MSGraphUser.UserPrincipalName}
    separatecontext: false
    skipunavailable: true
    task:
      brand: Builtin
      description: commands.local.cmd.set.parent.alert.context
      id: aaafcc54-e334-42a5-8a5c-f4dea1d0c158
      iscommand: true
      name: Set the username to the Alert context
      script: Builtin|||setParentIncidentContext
      type: regular
      version: -1
    taskid: aaafcc54-e334-42a5-8a5c-f4dea1d0c158
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 1145
        }
      }
  "23":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: MSGraphUser.ID
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verify that the user exists.
      id: 4655db74-8104-4510-88b0-d9a081911b34
      iscommand: false
      name: Does the username exist?
      type: condition
      version: -1
    taskid: 4655db74-8104-4510-88b0-d9a081911b34
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 785
        }
      }
  "25":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: ID
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Account.Type
                    operator: isEqualString
                    right:
                      value:
                        simple: Okta
                root: Account
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verify that the user exists.
      id: c1ba5bf5-e37f-41ee-8392-7709acc40e8f
      iscommand: false
      name: Does the username exist?
      type: condition
      version: -1
    taskid: c1ba5bf5-e37f-41ee-8392-7709acc40e8f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 530,
          "y": 785
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: MsGraphUsersSessionToClear
      value:
        complex:
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.Username
              operator: notContainsGeneral
              right:
                value:
                  simple: administrator
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.Username
              operator: notContainsGeneral
              right:
                value:
                  simple: system
          root: inputs.Username
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 2fd929ed-f77b-49d3-8ec5-9ac7e37a2a47
      iscommand: false
      name: Set users to clear the session with MsGraph
      script: Set
      type: regular
      version: -1
    taskid: 2fd929ed-f77b-49d3-8ec5-9ac7e37a2a47
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 410
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "15_2_#default#": 0.15,
      "17_15_yes": 0.48,
      "17_2_#default#": 0.11,
      "18_2_#default#": 0.16,
      "23_2_#default#": 0.25,
      "25_1_yes": 0.45,
      "25_2_#default#": 0.33
    },
    "paper": {
      "dimensions": {
        "height": 1535,
        "width": 860,
        "x": 530,
        "y": -150
      }
    }
  }
