contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 840ba626-dac4-47f5-8cc6-bc892aea77f9
inputs: []
name: extract-dnac-clients
outputs: []
sourceplaybookid: 148aadac-6b17-442a-8d6b-26e9befd59e3
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 72909156-bed7-4b75-8931-3335146c232d
      iscommand: false
      name: ""
      version: -1
    taskid: 72909156-bed7-4b75-8931-3335146c232d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      active_range:
        simple: ${incident.playbookpollinterval}
      dnac_instance_name:
        simple: ${incident.integrationinstancename}
      execution-timeout:
        simple: "172800"
      siteids:
        simple: ${incident.sitenames}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 80491388-6857-451e-8eda-c5ab07bb8202
      iscommand: false
      name: Send All PANW Device Attributes From DNAC to PANW
      script: ExportDeviceAttributesFromDnacToPANWIoTCloud
      type: regular
      version: -1
    taskid: 80491388-6857-451e-8eda-c5ab07bb8202
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "25"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - cisco-dnac-IoT
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 8146fa8f-5907-43ed-87eb-ec8f0e8ef56b
      iscommand: false
      name: Is DNA Center enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 8146fa8f-5907-43ed-87eb-ec8f0e8ef56b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_dnac
      message:
        simple: Cisco DNA Center instance is not enabled
      playbook_name:
        simple: extract-dnac-clients
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 9bcf6441-0eee-40c0-8da1-4f1adee1de56
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 9bcf6441-0eee-40c0-8da1-4f1adee1de56
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: f229dd14-3bfe-4edd-841e-659db97b32e3
      iscommand: true
      name: close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f229dd14-3bfe-4edd-841e-659db97b32e3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "26"
      "no":
      - "27"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - cisco-dnac-IoT
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a18edbb8-6c03-41ce-8ae2-c1a5e05a0c6f
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: a18edbb8-6c03-41ce-8ae2-c1a5e05a0c6f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_dnac
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: extract-dnac-clients
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 8cf5952e-4633-44d6-8925-13b740a452df
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 8cf5952e-4633-44d6-8925-13b740a452df
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_dnac
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: extract-dnac-clients
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 15513b1a-dc74-416d-8a09-ead99cb20534
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 15513b1a-dc74-416d-8a09-ead99cb20534
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "28":
    continueonerror: true
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 03febf71-beb1-4ebf-8acc-6e9fe1faf005
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 03febf71-beb1-4ebf-8acc-6e9fe1faf005
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_11_no": 0.46
    },
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
