contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: |
  Playbook to be run every 15 minutes via a job. Each run will get incremental updates for devices, and will update or create new endpoints in Cisco ISE with PANW IOT discovered attributes (ISE custom attributes).
id: 9d2c6af3-5dc9-4101-8f34-be3359e9a8ca
inputs: []
name: Incremental Export to Cisco ISE pxGrid - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 9d2c6af3-5dc9-4101-8f34-be3359e9a8ca
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 49c775c6-27ba-4dfa-8d51-b781d05e6f80
      iscommand: false
      name: ""
      version: -1
    taskid: 49c775c6-27ba-4dfa-8d51-b781d05e6f80
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 570,
          "y": -250
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      increment_time:
        simple: "15"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieves devices from PANW IoT cloud and send them to Cisco ISE
        via pxGrid
      id: 542cf2c5-844a-4200-8d96-af86358f8e13
      iscommand: false
      name: Get PANW IoT devices and send to Cisco ISE pxGrid
      script: b18e3470-65f7-430c-82c2-5a5803aa0b4b
      type: regular
      version: -1
    taskid: 542cf2c5-844a-4200-8d96-af86358f8e13
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 680,
          "y": 470
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "5"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: Cisco ISE pxGrid
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 320e53af-af84-4380-8198-008896c525ff
      iscommand: false
      name: Is pxGrid Integration enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 320e53af-af84-4380-8198-008896c525ff
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 570,
          "y": -100
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: pxgrid
      message:
        simple: pxGrid integration is not enabled
      playbook_name:
        simple: Increment Export to Cisco ISE pxGrid - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: daec95f2-f121-4acb-8071-4f22605de0c3
      iscommand: true
      name: Report disabled status to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: daec95f2-f121-4acb-8071-4f22605de0c3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 260,
          "y": 470
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "no":
      - "7"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: Cisco ISE pxGrid
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c9104d68-60f5-44d4-8bac-1c36bacc3a39
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: c9104d68-60f5-44d4-8bac-1c36bacc3a39
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 890,
          "y": 170
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: pxgrid
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Increment Export to Cisco ISE pxGrid - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 56a6f9f0-878d-4129-8d66-6bac60f106d1
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 56a6f9f0-878d-4129-8d66-6bac60f106d1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1080,
          "y": 470
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: pxgrid
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Increment Export to Cisco ISE pxGrid - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 2f3b13ef-3d95-44ce-81de-e540da63be68
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 2f3b13ef-3d95-44ce-81de-e540da63be68
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1490,
          "y": 470
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: be918b7a-25d9-45e5-853e-5ac84cddd029
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: be918b7a-25d9-45e5-853e-5ac84cddd029
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 890,
          "y": 670
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1015,
        "width": 1610,
        "x": 260,
        "y": -250
      }
    }
  }
