contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Export AIMS facilities, vendors, employees, work order priority list
  mappings and devices data to PANW IoT cloud
id: Export AIMS maps and devices to PANW IoT
inputs: []
name: Export AIMS maps and devices to PANW IoT
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6ef142f8-3718-401e-884f-48c23fcfa0ca
      iscommand: false
      name: ""
      version: -1
    taskid: 6ef142f8-3718-401e-884f-48c23fcfa0ca
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 930,
          "y": 70
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the facilities mapping details from AIMS
      id: b1bc3284-2c8a-443d-89f4-2e62ba4f91f5
      iscommand: true
      name: Get facility maps
      script: '|||aims-get-facility-maps'
      type: regular
      version: -1
    taskid: b1bc3284-2c8a-443d-89f4-2e62ba4f91f5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 285,
          "y": 370
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: AIMS instance is not enabled
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 14f0ab28-c28e-4c40-81b9-90b5a7e48e0b
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 14f0ab28-c28e-4c40-81b9-90b5a7e48e0b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385,
          "y": 730
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Error while getting data from AIMS
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: fbde10ad-72a0-4420-8427-22182bb6df15
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: fbde10ad-72a0-4420-8427-22182bb6df15
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Successfully received data from AIMS
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: d4b8538d-9117-4a8e-8b6c-8740ea687273
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: d4b8538d-9117-4a8e-8b6c-8740ea687273
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 1070
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the vendors mapping details from AIMS
      id: ec99b6f2-356c-4423-852d-7aec373d95d8
      iscommand: true
      name: Get vendor maps
      script: '|||aims-get-vendor-maps'
      type: regular
      version: -1
    taskid: ec99b6f2-356c-4423-852d-7aec373d95d8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 715,
          "y": 370
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the equipment type mapping details from AIMS
      id: 69da9447-9d93-4b57-8fc8-d1c111548f71
      iscommand: true
      name: Get equipment type maps
      script: '|||aims-get-equipment-type-maps'
      type: regular
      version: -1
    taskid: 69da9447-9d93-4b57-8fc8-d1c111548f71
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1145,
          "y": 370
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the cost center mapping details from AIMS
      id: 9197c6b3-cb88-424f-833a-600ae9d9c789
      iscommand: true
      name: Get cost center maps
      script: '|||aims-get-cost-center-maps'
      type: regular
      version: -1
    taskid: 9197c6b3-cb88-424f-833a-600ae9d9c789
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1575,
          "y": 370
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all available devices from the AIMS and send them to PANW
        IoT cloud using the custom attributes.
      id: 2ffd5579-c7df-4618-8ac5-756c362cf6ac
      iscommand: false
      name: Send AIMS devices to PANW IoT
      script: SendAIMSDevicesToPANWIoT
      type: regular
      version: -1
    taskid: 2ffd5579-c7df-4618-8ac5-756c362cf6ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 1220
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      IntegrationName:
        simple: aims
      MetaData:
        simple: '{"FacilityMaps": ${CommandOutput.FacilityMaps}, "VendorMaps": ${CommandOutput.VendorMaps},
          "EquipmentTypeMaps": ${CommandOutput.EquipmentTypeMaps}, "CostCenterMaps":
          ${CommandOutput.CostCenterMaps}}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send metadata to PANW IOT cloud
      id: 2ac400f4-7ac0-4270-8e21-09dbb992421e
      iscommand: true
      name: Send AIMS metadata to PANW IoT
      script: '|||panw-iot-3rd-party-report-metadata'
      type: regular
      version: -1
    taskid: 2ac400f4-7ac0-4270-8e21-09dbb992421e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 730
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 979d2afd-89e5-4a1c-8d53-0409a654d0c3
      iscommand: false
      name: Was there an error sending metadata to PANW IoT?
      script: isError
      type: condition
      version: -1
    taskid: 979d2afd-89e5-4a1c-8d53-0409a654d0c3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 890
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "17"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 38d60407-67d6-4b13-8b60-2cfaf085a5ac
      iscommand: false
      name: Was there an error getting data from AIMS?
      script: isError
      type: condition
      version: -1
    taskid: 38d60407-67d6-4b13-8b60-2cfaf085a5ac
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 570
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 3c743959-9c8e-48c5-8f34-383687757022
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 3c743959-9c8e-48c5-8f34-383687757022
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385,
          "y": 880
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "3"
      - "13"
      - "14"
      - "15"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - AIMS
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 9b968a85-e174-419f-8f90-7bb143145d66
      iscommand: false
      name: Is AIMS Integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 9b968a85-e174-419f-8f90-7bb143145d66
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 185
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 34769f4c-b937-48a1-855f-b8272bc6c1ae
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 34769f4c-b937-48a1-855f-b8272bc6c1ae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1480
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "20_11_no": 0.41,
      "25_10_yes": 0.69
    },
    "paper": {
      "dimensions": {
        "height": 1505,
        "width": 1670,
        "x": 285,
        "y": 70
      }
    }
  }
