contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Import devices in Nuvolo to PANW IoT cloud.
id: d94178ae-3e99-4efe-86ea-f73a8528b035
inputs: []
name: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 985135c8-3cc9-43b1-8783-926b487a076d
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e80a6903-9d36-46bc-8a9e-054119250e58
      iscommand: false
      name: ""
      version: -1
    taskid: e80a6903-9d36-46bc-8a9e-054119250e58
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "11"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Nuvolo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 140d07c6-0f19-4467-877c-9055d5820f47
      iscommand: false
      name: Is Nuvolo enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 140d07c6-0f19-4467-877c-9055d5820f47
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: Nuvolo integration is not enabled
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: d6643ff2-129b-473c-802d-71b7f42e7f8c
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: d6643ff2-129b-473c-802d-71b7f42e7f8c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 370
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 1d3d3bdf-be8f-45bb-8823-2e9b0ec1701d
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 1d3d3bdf-be8f-45bb-8823-2e9b0ec1701d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: b55ce30d-c50f-4b27-88c5-193b19506604
      iscommand: false
      name: Was there an error when importing devices from Nuvolo?
      script: isError
      type: condition
      version: -1
    taskid: b55ce30d-c50f-4b27-88c5-193b19506604
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: 'Error: Failed to do a bulk device import from Nuvolo'
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: ffe9dbc6-a578-423a-85bc-04eadaaefc6d
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: ffe9dbc6-a578-423a-85bc-04eadaaefc6d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: e973537b-c3ac-467c-80ab-07826a11ac63
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e973537b-c3ac-467c-80ab-07826a11ac63
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: d8975e87-a053-4cee-8af5-e7ecf8bdaf3b
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d8975e87-a053-4cee-8af5-e7ecf8bdaf3b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: Successfully Importing devices from Nuvolo.
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 663708a2-2066-48c7-86ab-12b391dd39a0
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 663708a2-2066-48c7-86ab-12b391dd39a0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "no":
      - "12"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Nuvolo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 96d148a3-69a5-4718-8d75-1842bdd96691
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 96d148a3-69a5-4718-8d75-1842bdd96691
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 99659cf4-f495-47e9-898c-4e252f291f1b
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 99659cf4-f495-47e9-898c-4e252f291f1b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: ae6011c2-9e8d-4cca-83ea-9c8f844445c5
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ae6011c2-9e8d-4cca-83ea-9c8f844445c5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 720
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: c81ed104-3414-4854-868e-ef14d4114346
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: c81ed104-3414-4854-868e-ef14d4114346
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Pulling devices information from Nuvolo and send to PANW IoT Cloud
        Side.
      id: 29de491d-0d1b-4472-867c-c21a0d7ba7c0
      iscommand: false
      name: Send Nuvolo Data To PANW IoT Cloud
      script: 74e93f5e-820a-463d-8f5d-741f45aa4cc4
      type: regular
      version: -1
    taskid: 29de491d-0d1b-4472-867c-c21a0d7ba7c0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "6_10_no": 0.66
    },
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
