contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 2.0.16
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook gets all available assets ( alerts, vulnerabilities and
  devices) and send then to configured PANW third-party integration SIEM server.
id: Bulk Export to SIEM - PANW IoT 3rd Party Integration
inputs: []
name: Bulk Export to SIEM - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: Bulk Export to SIEM - PANW IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7fcacb22-96e4-46a4-840b-034b172f44d4
      iscommand: false
      name: ""
      version: -1
    taskid: 7fcacb22-96e4-46a4-840b-034b172f44d4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1100,
          "y": -510
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: siem
      message:
        simple: Syslog Sender (SIEM) instance is not enabled
      playbook_name:
        simple: Bulk Export to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: disabled
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: ad75dcc7-fe4c-4337-8c5f-73eef98f7c38
      iscommand: true
      name: Send disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: ad75dcc7-fe4c-4337-8c5f-73eef98f7c38
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2240,
          "y": 590
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      execution-timeout:
        simple: "864000"
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
      run_once:
        simple: ${incident.runonce}
      sites:
        simple: ${incident.sitenames}
      syslog_sender_instance:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation retrieves all specified assets from the PANW IoT
        cloud and send them to the SIEM server.
      id: 5a5000a1-82fb-4241-8598-12ac506b338c
      iscommand: false
      name: Send all PANW IoT devices to SIEM
      script: SendAllPANWIoTAssetsToSIEM
      type: regular
      version: -1
    taskid: 5a5000a1-82fb-4241-8598-12ac506b338c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 140,
          "y": 590
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      execution-timeout:
        simple: "864000"
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
      run_once:
        simple: ${incident.runonce}
      sites:
        simple: ${incident.sitenames}
      syslog_sender_instance:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation retrieves all specified assets from the PANW IoT
        cloud and send them to the SIEM server.
      id: 8bc30019-5e5b-4aa0-8156-d41498bf655b
      iscommand: false
      name: Send all PANW IoT alerts to SIEM
      script: SendAllPANWIoTAssetsToSIEM
      type: regular
      version: -1
    taskid: 8bc30019-5e5b-4aa0-8156-d41498bf655b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 540,
          "y": 590
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      execution-timeout:
        simple: "864000"
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
      run_once:
        simple: ${incident.runonce}
      sites:
        simple: ${incident.sitenames}
      syslog_sender_instance:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation retrieves all specified assets from the PANW IoT
        cloud and sends them to the SIEM server.
      id: 44273b0d-108a-4c6c-8cc1-f7e7c9d3ff30
      iscommand: false
      name: Send all PANW IoT vulnerabilities to SIEM
      script: SendAllPANWIoTAssetsToSIEM
      type: regular
      version: -1
    taskid: 44273b0d-108a-4c6c-8cc1-f7e7c9d3ff30
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 950,
          "y": 590
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 1f0f2734-0dff-4e3d-8dce-58b02edcb8fd
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 1f0f2734-0dff-4e3d-8dce-58b02edcb8fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1210,
          "y": 790
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "no":
      - "9"
      "yes":
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 149b32a2-9cb5-4f1d-8063-f555ac088de7
      iscommand: false
      name: is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 149b32a2-9cb5-4f1d-8063-f555ac088de7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1460,
          "y": -40
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: siem
      message:
        simple: Failed to get License
      playbook_name:
        simple: Bulk Export to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: a4aa2769-f77d-436a-854e-c346e3b5edad
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: a4aa2769-f77d-436a-854e-c346e3b5edad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1430,
          "y": 590
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: siem
      message:
        simple: License Limit Exceeded
      playbook_name:
        simple: Bulk Export to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: ceaf4cff-d4fe-43bd-8150-22545aebfbfb
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: ceaf4cff-d4fe-43bd-8150-22545aebfbfb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1840,
          "y": 590
        }
      }
  "10":
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: a9b2b494-d677-4805-80b7-2b351c36e7da
      iscommand: false
      name: Is Syslog(SIEM) Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: a9b2b494-d677-4805-80b7-2b351c36e7da
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1100,
          "y": -390
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: PANW IoT 3rd Party Integration - Syslog Sender
      message:
        simple: No Syslog  Integration instance passed
      playbook_name:
        simple: Incremental Export to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 4e044a93-d1b8-45e4-829f-89bfbe7f4b93
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 4e044a93-d1b8-45e4-829f-89bfbe7f4b93
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 630,
          "y": -220
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "7"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Syslog Sender
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: cdb11643-70ae-4a60-891c-56c06f3cce61
      iscommand: false
      name: Is Syslog (SIEM)  Integration Enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: cdb11643-70ae-4a60-891c-56c06f3cce61
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1580,
          "y": -220
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: d46d2dec-4906-4dbe-89ee-304a7079f99f
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d46d2dec-4906-4dbe-89ee-304a7079f99f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 630,
          "y": -40
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
      - "21"
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e1cc42a1-907c-47ad-8498-352619fae085
      iscommand: false
      name: 'Retrieve Configured SIEM Asset Types '
      script: CheckConfiguredSIEMAssetTypes
      type: regular
      version: -1
    taskid: e1cc42a1-907c-47ad-8498-352619fae085
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 130
        }
      }
  "19":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: asset.device
          operator: isEqualString
          right:
            value:
              simple: "yes"
      label: DEVICE
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      DEVICE:
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3ed7f3d2-2782-46bc-85c8-906107d6acfc
      iscommand: false
      name: Device Type Selected?
      type: condition
      version: -1
    taskid: 3ed7f3d2-2782-46bc-85c8-906107d6acfc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 200,
          "y": 340
        }
      }
  "20":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: asset.alert
          operator: isEqualString
          right:
            value:
              simple: "yes"
      label: ALERT
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      ALERT:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 05a1700f-d56a-4dfa-86ba-164daf675ef9
      iscommand: false
      name: Alert Type Selected?
      type: condition
      version: -1
    taskid: 05a1700f-d56a-4dfa-86ba-164daf675ef9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 650,
          "y": 340
        }
      }
  "21":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: asset.vulnerability
          operator: isEqualString
          right:
            value:
              simple: "yes"
      label: VULNERABILITY
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      VULNERABILITY:
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a2d8ee3e-d65f-4dee-8349-8f6b3fb522a6
      iscommand: false
      name: Vulnerability Type Selected?
      type: condition
      version: -1
    taskid: a2d8ee3e-d65f-4dee-8349-8f6b3fb522a6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1120,
          "y": 340
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1395,
        "width": 2480,
        "x": 140,
        "y": -510
      }
    }
  }
