contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
dirtyInputs: true
id: 55f6e2be-64b3-4887-83c4-45d980ea6a9d
inputs: []
name: UnQuarantine Device in Forescout - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 86d00619-d4a6-4c08-8b00-86e96b1f62ca
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b895cec5-481d-4566-8c48-e604d042eb45
      iscommand: false
      name: ""
      version: -1
    taskid: b895cec5-481d-4566-8c48-e604d042eb45
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      brand_name:
        simple: PANW IoT 3rd Party Integration - Forescout
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9fa201da-55d0-42c0-830a-b407f3c267c0
      iscommand: false
      name: Is Forescout enabled?
      script: 292ae09c-ada1-4d3c-840a-add10bfefa5a
      type: condition
      version: -1
    taskid: 9fa201da-55d0-42c0-830a-b407f3c267c0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: forescout
      message:
        simple: The Forescout Integration Instance is Disabled
      playbook_name:
        simple: UnQuarantine Device in Forescout - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 13564b7e-d403-4469-833f-ac66d7e4bcd4
      iscommand: true
      name: Send disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 13564b7e-d403-4469-833f-ac66d7e4bcd4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 380
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: UnQuarantine
      field:
        simple: PanwIoTQuarantine
      integration:
        simple: forescout
      mac_address:
        simple: ${incident.macAddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7fa6a72b-8034-4843-895c-15f844f6e5b1
      iscommand: false
      name: UnQuarantine device using Forescout
      script: QuarantinePANWIoTDeviceOnForescout
      type: regular
      version: -1
    taskid: 7fa6a72b-8034-4843-895c-15f844f6e5b1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 814ff588-387e-4fa6-876a-6f53b7643a27
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 814ff588-387e-4fa6-876a-6f53b7643a27
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 570
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 615,
        "width": 925,
        "x": 150,
        "y": 50
      }
    }
  }
