contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This Playbook pushes dacl/sgacls from IoT cloud to Cisco ISE integration
id: 97b30c69-0797-453b-80c3-6b2ffdaee432
inputs: []
name: ACL Push to Cisco ISE-PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 527825c6-e714-4315-8b68-e78621934be6
      iscommand: false
      name: ""
      version: -1
    taskid: 527825c6-e714-4315-8b68-e78621934be6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      acl_type:
        simple: ${incident.ACLType}
      acls:
        simple: ${incident.aclContent}
      active_ise_instance:
        simple: ${PaloAltoIoTIntegrationBase.ActiveNodeInstance}
      authorization_profile:
        simple: ${incident.authorizationProfileNames}
      jobId:
        simple: ${incident.jobId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Creates or Updates ACLs in Cisco ISE.
      id: 45aed6b6-986f-43ab-8828-2dbd7caac32b
      iscommand: false
      name: CreateOrUpdateACLs
      script: CreateOrUpdatePANWIoTACLsToCiscoISE
      type: regular
      version: -1
    taskid: 45aed6b6-986f-43ab-8828-2dbd7caac32b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 370
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: f92cdfe4-def3-4276-8dbf-c91dd7e13180
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f92cdfe4-def3-4276-8dbf-c91dd7e13180
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 895
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobId}
      message:
        simple: successfully pushed acls to Cisco ISE
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Reports ACLs sync status
      id: fb70ccbd-0074-4b58-8b57-d87e16ed25b3
      iscommand: true
      name: Report ACL sync status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-aclsync-status'
      type: regular
      version: -1
    taskid: fb70ccbd-0074-4b58-8b57-d87e16ed25b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobId}
      message:
        simple: Failed to push acl sync status
      status:
        simple: failed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Reports ACLs sync status
      id: 425d918a-a684-4dcc-8203-04c8cde3705c
      iscommand: true
      name: Report failed ACL sync status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-aclsync-status'
      type: regular
      version: -1
    taskid: 425d918a-a684-4dcc-8203-04c8cde3705c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      - "11"
      "yes":
      - "4"
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: c8e52cdc-831a-426a-86c4-165b34f90e16
      iscommand: false
      name: Is there any error?
      script: isError
      type: condition
      version: -1
    taskid: c8e52cdc-831a-426a-86c4-165b34f90e16
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 545
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      - "13"
      "yes":
      - "1"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Cisco ISE
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 45cf9395-53dd-4c07-8d75-97de855341f3
      iscommand: false
      name: Is Cisco ISE enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 45cf9395-53dd-4c07-8d75-97de855341f3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${PaloAltoIoTIntegrationBase.ActiveNodeInstance}
      integration_name:
        simple: ise
      message:
        simple: Cisco ISE instance is not enabled
      playbook_name:
        simple: ACL Push to Cisco ISE-PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 75469b70-60e7-4dc4-8bf3-d651b1341ff3
      iscommand: true
      name: Send disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 75469b70-60e7-4dc4-8bf3-d651b1341ff3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${PaloAltoIoTIntegrationBase.ActiveNodeInstance}
      integration_name:
        simple: ise
      message:
        simple: ACLs are successfully pushed to Cisco ISE
      playbook_name:
        simple: ACL Push to Cisco ISE-PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: e84864bc-a321-44b7-81e0-2fa6e2b9b55f
      iscommand: true
      name: Send success status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e84864bc-a321-44b7-81e0-2fa6e2b9b55f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${PaloAltoIoTIntegrationBase.ActiveNodeInstance}
      integration_name:
        simple: ise
      message:
        simple: Error while pushing the ACLs to Cisco ISE
      playbook_name:
        simple: ACL Push to Cisco ISE-PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 600c7ca8-7c01-49e9-88fd-4a7958bb359b
      iscommand: true
      name: Send error status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 600c7ca8-7c01-49e9-88fd-4a7958bb359b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 720
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobId}
      message:
        simple: Cisco ISE instance is disabled
      status:
        simple: failed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Reports ACLs sync status
      id: 14e664e8-e49f-4ee4-8199-13f4c71c22f8
      iscommand: true
      name: Report failed ACL sync status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-aclsync-status'
      type: regular
      version: -1
    taskid: 14e664e8-e49f-4ee4-8199-13f4c71c22f8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 2530,
        "x": 50,
        "y": 50
      }
    }
  }
