contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 1.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5fde057b-bb45-4a90-8db4-5873a3419115
inputs: []
name: Tenable Scan Launch - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c57ad967-9dd7-4eec-8ea7-cb7d73a859da
      iscommand: false
      name: ""
      version: -1
    taskid: c57ad967-9dd7-4eec-8ea7-cb7d73a859da
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 562.5,
          "y": -110
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "9"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Tenable.io
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 45c7ffa9-56e9-4ace-8b27-b3ca5c758d37
      iscommand: false
      name: Is Tenable Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 45c7ffa9-56e9-4ace-8b27-b3ca5c758d37
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 570,
          "y": 40
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      scanId:
        simple: ${Tenable.scanId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Launches a scan with existing or custom targets. You can specify
        custom targets in the command arguments.
      id: cfc26afe-45f7-4371-84de-b8d2f94a6db4
      iscommand: true
      name: Launch Tenable.io vulnerability Scan
      script: '|||tenable-io-launch-scan'
      type: regular
      version: -1
    taskid: cfc26afe-45f7-4371-84de-b8d2f94a6db4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 930
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Tenable integration is not enabled
      playbook_name:
        simple: Tenable Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: f0bbc4c8-ec6b-4d57-8339-e6800b1bda66
      iscommand: true
      name: Report disabled status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: f0bbc4c8-ec6b-4d57-8339-e6800b1bda66
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -210,
          "y": 1920
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "5"
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
      path:
        simple: Tenable.scanLaunchfailStatus
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks for errors in a given task. If found, write it to the path
        provided as an argument.
      id: 19531632-a5dc-4d54-8744-f597aa512f47
      iscommand: false
      name: Did the Scan Launch Fail?
      script: GetPANWIoTTenableErrors
      type: condition
      version: -1
    taskid: 19531632-a5dc-4d54-8744-f597aa512f47
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 1095
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: The Tenable scan launch failed for ip - ${incident.ip}
      playbook_name:
        simple: Tenable Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 27151219-9d7b-4d5f-8be8-f32f867b7668
      iscommand: true
      name: Report Scan Launch Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 27151219-9d7b-4d5f-8be8-f32f867b7668
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 640,
          "y": 1920
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: TenableLaunchedScans
      operation:
        simple: insert
      value:
        simple: ${Tenable.scanId}_${Tenable.scanUUID}_${incident.ip}_${incident.jobid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: List operations, will create a new list if list does not exist
      id: 58f86eb7-541a-4726-8aad-71a50c5b043e
      iscommand: false
      name: Update Tenable launched scan cache
      script: 546f3d11-a5cf-488e-8952-87e66e17e951
      type: regular
      version: -1
    taskid: 58f86eb7-541a-4726-8aad-71a50c5b043e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1137.5,
          "y": 1310
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Successfully launched scan for ip - ${incident.ip}
      playbook_name:
        simple: Tenable Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: e277ba6d-ad01-4760-83da-69030fa7e8b7
      iscommand: true
      name: Report Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e277ba6d-ad01-4760-83da-69030fa7e8b7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1460,
          "y": 1900
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 285e92da-0656-41a0-8fe5-479406db3370
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 285e92da-0656-41a0-8fe5-479406db3370
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 2130
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      IP:
        simple: ${incident.ip}
      job_id:
        simple: ${incident.jobid}
      profile_Id:
        simple: ${incident.profileId}
      scan_name:
        simple: ${incident.ip}_panw_iot_scan
      scanner_Id:
        simple: ${incident.scannerId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Initiate scan '
      id: df7d4ce2-3ad8-48e2-83da-8d215c50ab47
      iscommand: true
      name: Initiate Tenable.io vulnerability Scan
      script: '|||tenable-io-initiate-scan'
      type: regular
      version: -1
    taskid: df7d4ce2-3ad8-48e2-83da-8d215c50ab47
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 220
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "10"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 1b89779d-e1e9-40a3-84ca-9ab323595596
      iscommand: false
      name: Wait for 10 sec
      script: Sleep
      type: regular
      version: -1
    taskid: 1b89779d-e1e9-40a3-84ca-9ab323595596
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 780
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 0c6530f0-1944-434e-8b7a-726a7381e92b
      iscommand: false
      name: Was there any error in updating the Tenable Launched scan cache?
      script: isError
      type: condition
      version: -1
    taskid: 0c6530f0-1944-434e-8b7a-726a7381e92b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1137.5,
          "y": 1460
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobid}
      message:
        simple: ${Tenable.scanLaunchfailStatus}
      scan_type:
        simple: tenable
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Upload reports (PDF + XML) for specified scan to IoT Cloud
      id: 03619852-e7ab-4633-8c03-c2347051f117
      iscommand: true
      name: Report Scan Launch Error As Event
      script: '|||panw-iot-3rd-party-upload-vulnerability-scan-report'
      type: regular
      version: -1
    taskid: 03619852-e7ab-4633-8c03-c2347051f117
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 212.5,
          "y": 1920
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Tenable.scanLaunchfailStatus
      value:
        simple: Unable to update XSOAR scan cache list for IP ${incident.ip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 0326ef43-62cf-473f-8a42-4fb119fa5e3b
      iscommand: false
      name: Format error message for launch cache update
      script: Set
      type: regular
      version: -1
    taskid: 0326ef43-62cf-473f-8a42-4fb119fa5e3b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 1740
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "12"
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: f5dad7f8-66d1-479c-8346-592efac22755
      iscommand: false
      name: Did the Scan Initiation fail?
      script: isError
      type: condition
      version: -1
    taskid: f5dad7f8-66d1-479c-8346-592efac22755
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 565
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      contextKey:
        simple: Tenable.scanLaunchfailStatus
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Takes the comments of a given entry ID and stores them in the
        incident context, under a provided context key. \nFor accessing the last executed
        task's comments, provide ${lastCompletedTaskEntries.[0]} as the value for
        the entryId input parameter."
      id: bd2b4297-e68a-47b2-8102-f7bdc2f3a769
      iscommand: false
      name: Add output to error message
      script: commentsToContext
      type: regular
      version: -1
    taskid: bd2b4297-e68a-47b2-8102-f7bdc2f3a769
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2335,
        "width": 2050,
        "x": -210,
        "y": -110
      }
    }
  }
