contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 55f6e2be-64b3-4887-83c4-45d980ea6a9d
inputs: []
name: UnQuarantine Device in Forescout - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 86d00619-d4a6-4c08-8b00-86e96b1f62ca
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: db419c63-cfa2-4789-8d4d-d437497dcd87
      iscommand: false
      name: ""
      version: -1
    taskid: db419c63-cfa2-4789-8d4d-d437497dcd87
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      brand_name:
        simple: PANW IoT 3rd Party Integration - Forescout
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a630a9f8-62f0-41bd-819c-950229f652bf
      iscommand: false
      name: Is Forescout enabled?
      script: 292ae09c-ada1-4d3c-840a-add10bfefa5a
      type: condition
      version: -1
    taskid: a630a9f8-62f0-41bd-819c-950229f652bf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: forescout
      message:
        simple: The Forescout Integration Instance is Disabled
      playbook_name:
        simple: UnQuarantine Device in Forescout - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 61301645-3a04-4f1f-8c16-7cd5a6849561
      iscommand: true
      name: Send disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 61301645-3a04-4f1f-8c16-7cd5a6849561
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 380
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: UnQuarantine
      field:
        simple: PanwIoTQuarantine
      integration:
        simple: forescout
      mac_address:
        simple: ${incident.macAddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 32a91719-5f7b-49e9-83b3-c30b12aea569
      iscommand: false
      name: UnQuarantine device using Forescout
      script: QuarantinePANWIoTDeviceOnForescout
      type: regular
      version: -1
    taskid: 32a91719-5f7b-49e9-83b3-c30b12aea569
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 9cebc7af-c0be-49c8-89a2-8415d2c08e18
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 9cebc7af-c0be-49c8-89a2-8415d2c08e18
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 570
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 615,
        "width": 925,
        "x": 150,
        "y": 50
      }
    }
  }
