contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 1.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
dirtyInputs: true
id: 0498dd6c-9db3-4020-8515-37a9e9774c60
inputs: []
name: Incremental Export of Cortex XDR - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: af2c1125-ca1e-4f4d-8a8b-aea23b5f044a
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0698c1e4-edd8-45c5-855d-bb048180ea4d
      iscommand: false
      name: ""
      version: -1
    taskid: 0698c1e4-edd8-45c5-855d-bb048180ea4d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "20"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Cortex XDR - IR
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: eaaedf50-83d1-42d7-8ff9-8bd4b15db7b8
      iscommand: false
      name: Is Cortex XDR integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: eaaedf50-83d1-42d7-8ff9-8bd4b15db7b8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cortex_xdr
      message:
        simple: Cortex XDR Instance is not available
      playbook_name:
        simple: Incremental Export from Cortex XDR- PANW IoT 3rd Party Integration
      playbookName:
        simple: Cisco Prime Clients
      status:
        simple: disabled
      type:
        simple: device
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 7402dadb-db37-4704-8116-1f715175dbc1
      iscommand: true
      name: Send Disable Status to IOT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 7402dadb-db37-4704-8116-1f715175dbc1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      active_range:
        simple: ${incident.playbookpollinterval}
      execution-timeout:
        simple: "172800"
      pageLength:
        simple: "100"
      siteids:
        simple: ${incident.sitenames}
      xdr_instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      id: 52806bf2-7359-4168-8d3d-69c833198244
      iscommand: false
      name: Export Device Attributes from Cortex XDR to PANW
      script: ExportDeviceAttributesFromCortexXDRToPANWIoTCloud
      type: regular
      version: -1
    taskid: 52806bf2-7359-4168-8d3d-69c833198244
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: cbcf2391-af2d-42b7-80a6-615576e2b522
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: cbcf2391-af2d-42b7-80a6-615576e2b522
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "21"
      "no":
      - "22"
      "yes":
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - Cortex XDR - IR
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a70a3a46-b727-4fda-83fa-a0b83d61916b
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: a70a3a46-b727-4fda-83fa-a0b83d61916b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cortex_xdr
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Incremental Export from Cortex XDR- PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 1e7231c6-146f-4dcf-83d6-3c1a7c48a06a
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 1e7231c6-146f-4dcf-83d6-3c1a7c48a06a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cortex_xdr
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Incremental Export from Cortex XDR- PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: a56ba0c5-d4db-4eac-8632-ec4f1a382761
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: a56ba0c5-d4db-4eac-8632-ec4f1a382761
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 569451cf-d73a-45ec-8c75-4598bd30fb89
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 569451cf-d73a-45ec-8c75-4598bd30fb89
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 895
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "25"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 39b542bb-4f0a-41ea-8045-0cda732ee426
      iscommand: false
      name: Is Cortex XDR Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: 39b542bb-4f0a-41ea-8045-0cda732ee426
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cortex_xdr
      message:
        simple: No Cortex XDR integration instance passed
      playbook_name:
        simple: Incremental Import of Cortex XDR - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 0e29b3fe-fe2d-4c66-8901-0bc3c2f58ddd
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 0e29b3fe-fe2d-4c66-8901-0bc3c2f58ddd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -370,
          "y": 600
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 2090,
        "x": -370,
        "y": 50
      }
    }
  }
