contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 227ab96f-0b0e-411b-8db6-1d3344925246
inputs: []
name: Update Integration Status - PANW IoT 3rd Party Integrations
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76e4ac58-e3c0-4f77-8a4f-e9e68efa99ea
      iscommand: false
      name: ""
      version: -1
    taskid: 76e4ac58-e3c0-4f77-8a4f-e9e68efa99ea
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 630,
          "y": -10
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0d0b45b8-84b5-4a50-89bc-ee3aafa282bf
      iscommand: false
      name: UpdatePANWIoTIntegrationStatus
      script: UpdatePANWIoTIntegrationStatus
      type: regular
      version: -1
    taskid: 0d0b45b8-84b5-4a50-89bc-ee3aafa282bf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 630,
          "y": 170
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 95811e13-04fa-4c37-894a-63a8edd46c24
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 95811e13-04fa-4c37-894a-63a8edd46c24
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 630,
          "y": 350
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 630,
        "y": -10
      }
    }
  }
