contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: a98b48c2-dc25-4664-876f-32e246916b2c
inputs: []
name: zssdf
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9c5bfad0-25c7-4f16-8632-38293aedcc6f
      iscommand: false
      name: ""
      version: -1
    taskid: 9c5bfad0-25c7-4f16-8632-38293aedcc6f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 0
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b1db6d57-d00f-47a3-87ea-ab70fe292e93
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: b1db6d57-d00f-47a3-87ea-ab70fe292e93
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 160
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 255,
        "width": 380,
        "x": 450,
        "y": 0
      }
    }
  }
