contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.13
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook is meant to be triggered by incident type from PANW IoT
  Cloud. The custom fields (jobid, ip, site, engine, scanType and template) are used
  to launch a scan on Rapid7
id: 184fda38-0a70-41a7-87b6-f3a34f3a5505
inputs: []
name: Rapid7 Nexpose Scan Launch - PANW IoT 3rd Party Integration
outputs:
- contextPath: incident
  type: unknown
sourceplaybookid: 38d9fa0d-80ca-4d0b-8424-4d388ebce25b
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0d3034e6-20b7-4769-8cf2-056eb0132e47
      iscommand: false
      name: ""
      version: -1
    taskid: 0d3034e6-20b7-4769-8cf2-056eb0132e47
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 87804d7e-495d-4885-82a5-fd71334b7cce
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 87804d7e-495d-4885-82a5-fd71334b7cce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Rapid7 Nexpose
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 7423e637-f132-4249-8163-694a6cff28d7
      iscommand: false
      name: Is Rapid7 Nexpose Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 7423e637-f132-4249-8163-694a6cff28d7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: rapid7
      message:
        simple: Rapid7 Nexpose integration is not enabled
      playbook_name:
        simple: Rapid7 Nexpose Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: c4cf6f4d-cdd8-47d7-8bc5-2b6c6f20d8bd
      iscommand: true
      name: Report disabled status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: c4cf6f4d-cdd8-47d7-8bc5-2b6c6f20d8bd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      engine:
        simple: ${incident.scannerid}
      hosts:
        simple: ${incident.ip}
      name:
        simple: ${incident.jobid}
      site:
        simple: ${incident.siteid}
      template:
        simple: ${incident.profileid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Starts a scan for the specified engine and template.
      id: 7ff612d1-56f3-4cca-809a-70bb0035064c
      iscommand: true
      name: Launch Rapid7 vulnerability Scan
      script: '|||nexpose-start-scan-using-template-engine'
      type: regular
      version: -1
    taskid: 7ff612d1-56f3-4cca-809a-70bb0035064c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: rapid7
      message:
        simple: ${Nexpose.scanLaunchfailStatus}
      playbook_name:
        simple: Rapid7 Nexpose Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: de747511-f25f-476c-8e3c-6186d990039b
      iscommand: true
      name: Report Scan Launch Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: de747511-f25f-476c-8e3c-6186d990039b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: Rapid7LaunchedScans
      operation:
        simple: insert
      value:
        simple: ${Nexpose.Scan.Id}_${incident.ip}_${incident.jobid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: List operations, will create a new list if list does not exist
      id: e354a68b-5509-4928-813e-e6c3bfb6311a
      iscommand: false
      name: Update Rapid7 launched scan cache
      script: PANWIoTLaunchedVulnerabilityScanCacheOperations
      type: regular
      version: -1
    taskid: e354a68b-5509-4928-813e-e6c3bfb6311a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "12"
      "yes":
      - "9"
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
      path:
        simple: Nexpose.scanLaunchfailStatus
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks for errors in a given task. If found, write it to the path
        provided as an argument.
      id: c8d8bfb6-1cc2-48f9-8b75-6b6c96852b09
      iscommand: false
      name: Did the Scan Launch Fail?
      script: ba739f62-3f46-417e-809b-3c73715e062d
      type: condition
      version: -1
    taskid: c8d8bfb6-1cc2-48f9-8b75-6b6c96852b09
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${incident.ip}
      job_id:
        simple: ${incident.jobid}
      message:
        simple: ${Nexpose.scanLaunchfailStatus}
      scan_type:
        simple: rapid7
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Upload reports (PDF + XML) for specified scan to IoT Cloud
      id: 90d27aa6-b56b-4181-8b78-772e8322a08e
      iscommand: true
      name: Report Scan Launch Error As Event
      script: '|||panw-iot-3rd-party-upload-vulnerability-scan-report'
      type: regular
      version: -1
    taskid: 90d27aa6-b56b-4181-8b78-772e8322a08e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 895
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: rapid7
      message:
        simple: Successfully launched scan for ip ${incident.ip} with job id ${incident.jobid}
      playbook_name:
        simple: Rapid7 Nexpose Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 8da66a20-3252-42c8-8601-926188137fe0
      iscommand: true
      name: Report Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 8da66a20-3252-42c8-8601-926188137fe0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
