contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Export single alert or vulnerability as work order in AIMS
id: 91a6bd11-8c73-4b25-83b4-e8fad47f03fb
inputs: []
name: Export single alert or vulnerability as work order in AIMS - PANW IoT 3rd Party
  Integration
outputs: []
sourceplaybookid: Export single alert or vulnerability as work order in AIMS - PANW
  IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 40942843-845b-447a-8340-2776cf4c13ab
      iscommand: false
      name: ""
      version: -1
    taskid: 40942843-845b-447a-8340-2776cf4c13ab
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "9"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - AIMS
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 9fa783e8-80c4-4215-883a-316cd24da978
      iscommand: false
      name: Is AIMS Integration enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 9fa783e8-80c4-4215-883a-316cd24da978
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: aims
      message:
        simple: AIMS instance is not enabled
      playbook_name:
        simple: Export single alert or vulnerability as work order in AIMS - PANW
          IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: cf7870d2-3906-4e8a-893f-be034fddc107
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: cf7870d2-3906-4e8a-893f-be034fddc107
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 11cae241-7021-42b6-868f-749900dc0e35
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 11cae241-7021-42b6-868f-749900dc0e35
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 450e7811-3b42-4a2f-860a-039a589ee5d0
      iscommand: false
      name: Was there an error creating work order in AIMS?
      script: isError
      type: condition
      version: -1
    taskid: 450e7811-3b42-4a2f-860a-039a589ee5d0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: aims
      message:
        simple: Successfully created work order in AIMS
      playbook_name:
        simple: Export single alert or vulnerability as work order in AIMS - PANW
          IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 54eb206f-2b0d-47d9-836f-1d8d73e7a764
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 54eb206f-2b0d-47d9-836f-1d8d73e7a764
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: aims
      message:
        simple: Error while creating work order in AIMS
      playbook_name:
        simple: Export single alert or vulnerability as work order in AIMS - PANW
          IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 86e61abe-d3c0-4f92-8e57-40e856f0c861
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 86e61abe-d3c0-4f92-8e57-40e856f0c861
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      AssignedTo:
        simple: ${incident.assignedTo}
      Contact:
        simple: ${incident.contact}
      Facility:
        simple: ${incident.facility}
      Notes:
        simple: ${incident.notes}
      Priority:
        simple: ${incident.priority}
      Problem:
        simple: ${incident.problem}
      Reason:
        simple: ${incident.reason}
      Requester:
        simple: ${incident.requester}
      Requster:
        simple: ${incident.requester}
      Tag:
        simple: ${incident.tag}
      UserEmail:
        simple: ${incident.user_email}
      ZbTicketId:
        simple: ${incident.zb_ticketid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Create work order in AIMS
      id: 3f8618f1-936e-43f7-8a3e-b9fd691e8a1b
      iscommand: true
      name: Create work order in AIMS
      script: '|||aims-create-work-order'
      type: regular
      version: -1
    taskid: 3f8618f1-936e-43f7-8a3e-b9fd691e8a1b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      IntegrationName:
        simple: aims
      MetaData:
        simple: ${CommandOutput.WorkOrderResponse}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send metadata to PANW IOT cloud
      id: a83b9ea2-718c-47d4-8487-256dd6279595
      iscommand: true
      name: Send response metadata to PANW IoT
      script: '|||panw-iot-3rd-party-report-metadata'
      type: regular
      version: -1
    taskid: a83b9ea2-718c-47d4-8487-256dd6279595
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 720
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 830c7c00-d743-4fc7-8b9f-8831b90551ba
      iscommand: false
      name: Was there an error reporting details to PANW IoT?
      script: isError
      type: condition
      version: -1
    taskid: 830c7c00-d743-4fc7-8b9f-8831b90551ba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 490,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_8_yes": 0.38,
      "1_2_no": 0.52,
      "1_9_yes": 0.54,
      "6_10_no": 0.5,
      "6_8_yes": 0.36
    },
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
