contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Export AIMS facilities, vendors, employees, work order priority list
  mappings and devices data to PANW IoT cloud
id: Export AIMS maps and devices to PANW IoT
inputs: []
name: Export AIMS maps and devices to PANW IoT
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 49a9cb25-a8b8-424b-8f8c-f09ac5c61b5a
      iscommand: false
      name: ""
      version: -1
    taskid: 49a9cb25-a8b8-424b-8f8c-f09ac5c61b5a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 930,
          "y": 70
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the facilities mapping details from AIMS
      id: 32b39ed5-b9c0-4ea0-8115-d412cfaf59af
      iscommand: true
      name: Get facility maps
      script: '|||aims-get-facility-maps'
      type: regular
      version: -1
    taskid: 32b39ed5-b9c0-4ea0-8115-d412cfaf59af
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 285,
          "y": 370
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: AIMS instance is not enabled
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: e971fab4-54ef-4183-8f62-1d2e325f8cb0
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e971fab4-54ef-4183-8f62-1d2e325f8cb0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385,
          "y": 730
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Error while getting data from AIMS
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 49626b7a-cbba-476c-8203-ade55b1e5a59
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 49626b7a-cbba-476c-8203-ade55b1e5a59
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Successfully received data from AIMS
      playbook_name:
        simple: Export AIMS maps and devices to PANW IoT
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: ea3e00bc-c55c-44e2-8b3d-d2d29dc76b06
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: ea3e00bc-c55c-44e2-8b3d-d2d29dc76b06
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 1070
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the vendors mapping details from AIMS
      id: 31824e41-238f-4f43-844b-1704b4728858
      iscommand: true
      name: Get vendor maps
      script: '|||aims-get-vendor-maps'
      type: regular
      version: -1
    taskid: 31824e41-238f-4f43-844b-1704b4728858
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 715,
          "y": 370
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the equipment type mapping details from AIMS
      id: 63a1a0bf-ee52-4d4e-80fd-1f39a7780f1c
      iscommand: true
      name: Get equipment type maps
      script: '|||aims-get-equipment-type-maps'
      type: regular
      version: -1
    taskid: 63a1a0bf-ee52-4d4e-80fd-1f39a7780f1c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1145,
          "y": 370
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the cost center mapping details from AIMS
      id: e60a6c06-026b-4fee-88b7-feaba58dd781
      iscommand: true
      name: Get cost center maps
      script: '|||aims-get-cost-center-maps'
      type: regular
      version: -1
    taskid: e60a6c06-026b-4fee-88b7-feaba58dd781
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1575,
          "y": 370
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all available devices from the AIMS and send them to PANW
        IoT cloud using the custom attributes.
      id: fa4d2e40-53ec-4337-8054-621f427712cb
      iscommand: false
      name: Send AIMS devices to PANW IoT
      script: SendAIMSDevicesToPANWIoT
      type: regular
      version: -1
    taskid: fa4d2e40-53ec-4337-8054-621f427712cb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 1220
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      IntegrationName:
        simple: aims
      MetaData:
        simple: '{"FacilityMaps": ${CommandOutput.FacilityMaps}, "VendorMaps": ${CommandOutput.VendorMaps},
          "EquipmentTypeMaps": ${CommandOutput.EquipmentTypeMaps}, "CostCenterMaps":
          ${CommandOutput.CostCenterMaps}}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send metadata to PANW IOT cloud
      id: 29a2f2e3-431c-4a93-89b2-6af49823c678
      iscommand: true
      name: Send AIMS metadata to PANW IoT
      script: '|||panw-iot-3rd-party-report-metadata'
      type: regular
      version: -1
    taskid: 29a2f2e3-431c-4a93-89b2-6af49823c678
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 730
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 00d1a058-34f5-4ecc-839b-b19b5de206b4
      iscommand: false
      name: Was there an error sending metadata to PANW IoT?
      script: isError
      type: condition
      version: -1
    taskid: 00d1a058-34f5-4ecc-839b-b19b5de206b4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 890
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "17"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 707b5772-4be0-49ad-8826-68e52247ee13
      iscommand: false
      name: Was there an error getting data from AIMS?
      script: isError
      type: condition
      version: -1
    taskid: 707b5772-4be0-49ad-8826-68e52247ee13
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 570
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: fbe93868-e290-411b-8964-a2e20dd7da23
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: fbe93868-e290-411b-8964-a2e20dd7da23
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385,
          "y": 880
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "3"
      - "13"
      - "14"
      - "15"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - AIMS
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 597f9ed1-d7e0-49ff-800b-38a6c7aca106
      iscommand: false
      name: Is AIMS Integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 597f9ed1-d7e0-49ff-800b-38a6c7aca106
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 185
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: f7345657-caf9-43ef-8e6d-94215808d1e2
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f7345657-caf9-43ef-8e6d-94215808d1e2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1480
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "20_11_no": 0.41,
      "25_10_yes": 0.69
    },
    "paper": {
      "dimensions": {
        "height": 1505,
        "width": 1670,
        "x": 285,
        "y": 70
      }
    }
  }
