contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8d3c3eb4-1852-4bc3-8b3e-93c93ea33bdf
inputs: []
name: Incremental Export Devices to Nuvolo - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 8d3c3eb4-1852-4bc3-8b3e-93c93ea33bdf
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ba0bce7c-bccd-42bb-87c6-9e7e69c792c9
      iscommand: false
      name: ""
      version: -1
    taskid: ba0bce7c-bccd-42bb-87c6-9e7e69c792c9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": -330
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      increment_time:
        simple: "15"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Returns a list of assets for the specified asset type.
      id: 375955b2-8491-465c-8018-fc111b83d3bb
      iscommand: true
      name: Get incremental device list
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-asset-list
      type: regular
      version: -1
    taskid: 375955b2-8491-465c-8018-fc111b83d3bb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      customer_id:
        simple: ${PanwIot3rdParty.customerid}
      device_list:
        simple: ${PanwIot3rdParty.Devices}
      operation_type:
        simple: insert
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5d9ece8f-dbbb-416c-8a0c-35db0e4efd04
      iscommand: false
      name: Upsert devices to Nuvolo
      script: cd49735a-a76c-4fbe-823b-810394c5296d
      type: regular
      version: -1
    taskid: 5d9ece8f-dbbb-416c-8a0c-35db0e4efd04
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 9d252835-0671-4ca6-80c9-c9642451585d
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 9d252835-0671-4ca6-80c9-c9642451585d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      "yes":
      - "18"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Nuvolo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 934173ce-f461-48fb-8cbb-7fe87d13fee1
      iscommand: false
      name: Is Nuvolo integration enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 934173ce-f461-48fb-8cbb-7fe87d13fee1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": -135
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Return the PANW IoT customer id.
      id: f1da6c9c-e0d1-47b5-8a09-402e1b7d5e29
      iscommand: true
      name: Get PANW IoT Customer Id
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-customerid
      type: regular
      version: -1
    taskid: f1da6c9c-e0d1-47b5-8a09-402e1b7d5e29
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: Nuvolo Integration is not enabled
      playbook_name:
        simple: Incremental Export Devices to Nuvolo - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 2ee01751-daeb-47f1-8cb4-f3f9544297aa
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 2ee01751-daeb-47f1-8cb4-f3f9544297aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: c5c9cc4e-2373-4d05-80fb-1915a490530e
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: c5c9cc4e-2373-4d05-80fb-1915a490530e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "12"
      "yes":
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.Devices}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 29a00044-6b49-4687-89a4-50ecd6798e41
      iscommand: false
      name: Does incremental device list exists?
      script: Exists
      type: condition
      version: -1
    taskid: 29a00044-6b49-4687-89a4-50ecd6798e41
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: Incremental device list doesn't exist
      playbook_name:
        simple: Incremental Export Devices to Nuvolo - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 9ab02487-e3cd-413f-84ab-8055e00a54ac
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 9ab02487-e3cd-413f-84ab-8055e00a54ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 8c97b70e-3fcd-43a8-8a3a-f0d941223fc2
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8c97b70e-3fcd-43a8-8a3a-f0d941223fc2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "15"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 122b1c06-1ec7-4cab-8683-188827600be3
      iscommand: false
      name: Was there an error when upserting to Nuvolo?
      script: isError
      type: condition
      version: -1
    taskid: 122b1c06-1ec7-4cab-8683-188827600be3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: facility count is ${Nuvolo-IoT.numOfExportDevices.facility_count},
          meidical count is ${Nuvolo-IoT.numOfExportDevices.medical_count}, unmatched
          count is ${Nuvolo-IoT.numOfExportDevices.unmatch_count}, skipped count is
          ${Nuvolo-IoT.numOfExportDevices.skip_count}
      playbook_name:
        simple: Incremental Export Devices to Nuvolo - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 8afa0f56-536d-40ad-81eb-1adfe65760d4
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 8afa0f56-536d-40ad-81eb-1adfe65760d4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: Failed to export devices to Nuvolo
      playbook_name:
        simple: Incremental Export Devices to Nuvolo - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: ec6c4fa3-f589-40a5-8836-09e50f9685c4
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: ec6c4fa3-f589-40a5-8836-09e50f9685c4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 19b38d82-46d9-4409-8f78-44c18b7f02b9
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 19b38d82-46d9-4409-8f78-44c18b7f02b9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "19"
      "no":
      - "20"
      "yes":
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Nuvolo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 46c47cca-d8fa-4384-8959-1138b545a701
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 46c47cca-d8fa-4384-8959-1138b545a701
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 100
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Incremental Export Devices to Nuvolo - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: eae6b439-ed85-42f4-8bd9-43a65ef5d6c5
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: eae6b439-ed85-42f4-8bd9-43a65ef5d6c5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 370
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Incremental Export Devices to Nuvolo - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 535ab808-4026-4a12-8d94-49b3dfc5679f
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 535ab808-4026-4a12-8d94-49b3dfc5679f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 370
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 73ea034d-53d3-4b35-83db-6dd47d6b7535
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 73ea034d-53d3-4b35-83db-6dd47d6b7535
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 580
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1845,
        "width": 1680,
        "x": 50,
        "y": -330
      }
    }
  }
