contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.3
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to be run every 15 minutes via a job. Each run will get incremental
  updates for devices to send to ServiceNow server.
id: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c9a3478f-5349-4050-8459-99d4db828728
      iscommand: false
      name: ""
      version: -1
    taskid: c9a3478f-5349-4050-8459-99d4db828728
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "42"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 31293ed5-61e0-47cc-8f91-c220176d2e65
      iscommand: false
      name: Is ServiceNow integration enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 31293ed5-61e0-47cc-8f91-c220176d2e65
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: ServiceNow Integration is not enabled
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: bfee817b-0371-488b-8107-29378989a4ed
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: bfee817b-0371-488b-8107-29378989a4ed
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 901f133a-d83f-4f7c-832a-523bc5432fba
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 901f133a-d83f-4f7c-832a-523bc5432fba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: ${SN-IoT.incrementResult}
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 698aa1a6-e367-4fab-8434-f5306936acd2
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 698aa1a6-e367-4fab-8434-f5306936acd2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1770
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 6afee278-022c-4cb6-85e3-0eebfe0a6e37
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 6afee278-022c-4cb6-85e3-0eebfe0a6e37
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1945
        }
      }
  "35":
    continueonerror: true
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "41"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get PANW IoT and ServiceNow category mapping
      id: 45674a39-402f-47fb-8f97-7304a1345698
      iscommand: false
      name: Get PANW IoT ServiceNow Category Mapping
      script: GetPANWIoTServiceNowCategoryMapping
      type: regular
      version: -1
    taskid: 45674a39-402f-47fb-8f97-7304a1345698
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1070
        }
      }
  "36":
    continueonerror: true
    continueonerrortype: ""
    id: "36"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all customized table and column names in the customers' ServiceNow.
      id: f319d31f-d746-49c4-823f-ba6443dcf410
      iscommand: false
      name: Get ServiceNow Customized Configuration
      script: GetServiceNowCustomizedConfiguration
      type: regular
      version: -1
    taskid: f319d31f-d746-49c4-823f-ba6443dcf410
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 895
        }
      }
  "37":
    continueonerror: true
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "38"
    note: false
    quietmode: 0
    scriptarguments:
      customized_servicenow_config:
        simple: ${PanwIot3rdParty.SNConfig}
      device_list:
        simple: ${PanwIot3rdParty.Devices}
      iot_servicenow_category_map:
        simple: ${PanwIot3rdParty.SNCategoryMapping}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send Incremental PANW IoT Devices To ServiceNow
      id: 82244229-8531-4556-8252-ebd2d166e411
      iscommand: false
      name: Send Incremental PANW IoT Devices To ServiceNow
      script: SendIncrementalPANWIoTDevicesToServiceNow
      type: regular
      version: -1
    taskid: 82244229-8531-4556-8252-ebd2d166e411
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1420
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "26"
      "yes":
      - "39"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: e1f3d9b2-858e-4fc4-83bf-ce557d379594
      iscommand: false
      name: Was there an error when sending devices to servicenow?
      script: isError
      type: condition
      version: -1
    taskid: e1f3d9b2-858e-4fc4-83bf-ce557d379594
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1595
        }
      }
  "39":
    continueonerror: true
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "40"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to do incremental device sync to ServiceNow. Please
          see the detailed error message from the playbook.'
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: a90ac062-e2c2-4557-83e9-9ebc1e14f436
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: a90ac062-e2c2-4557-83e9-9ebc1e14f436
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1770
        }
      }
  "40":
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 15876413-cedb-4eee-8d50-8b2e21581943
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 15876413-cedb-4eee-8d50-8b2e21581943
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1945
        }
      }
  "41":
    continueonerror: true
    continueonerrortype: ""
    id: "41"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      increment_time:
        simple: "15"
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Returns a list of assets for the specified asset type.
      id: 57170c5e-d256-466b-8897-33526ebc05c0
      iscommand: true
      name: Get PANW IoT Devices
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-asset-list
      type: regular
      version: -1
    taskid: 57170c5e-d256-466b-8897-33526ebc05c0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1245
        }
      }
  "42":
    continueonerror: true
    continueonerrortype: ""
    id: "42"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "43"
      "no":
      - "44"
      "yes":
      - "46"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1cef200c-7d1f-4e58-8819-fc7d89480ed1
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 1cef200c-7d1f-4e58-8819-fc7d89480ed1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "43":
    continueonerror: true
    continueonerrortype: ""
    id: "43"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 43484a44-d802-4abc-848d-495dddbd3d16
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 43484a44-d802-4abc-848d-495dddbd3d16
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "44":
    continueonerror: true
    continueonerrortype: ""
    id: "44"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 0c2a5184-65bf-40cc-8416-01ab45f09d0d
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 0c2a5184-65bf-40cc-8416-01ab45f09d0d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "45":
    continueonerror: true
    continueonerrortype: ""
    id: "45"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 0aeb0edf-8e03-404a-8bd2-2ea857ec7e71
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 0aeb0edf-8e03-404a-8bd2-2ea857ec7e71
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "46":
    continueonerrortype: ""
    id: "46"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "47"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get ServiceNow Table Mapping Method
      id: 85d86862-9f12-4c3c-8bd6-e6954d6a0150
      iscommand: true
      name: Get ServiceNow Mapping Method
      script: '|||get-mapping-method'
      type: regular
      version: -1
    taskid: 85d86862-9f12-4c3c-8bd6-e6954d6a0150
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "47":
    continueonerrortype: ""
    id: "47"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "36"
      "yes":
      - "48"
    note: false
    quietmode: 0
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${SN.MappingMethod}
      right:
        simple: Use ServiceNow Classes
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 8f7dfa1e-bee8-4de1-8d95-fe4eff7a565b
      iscommand: false
      name: Is ServiceNow OT Mapping?
      script: AreValuesEqual
      type: condition
      version: -1
    taskid: 8f7dfa1e-bee8-4de1-8d95-fe4eff7a565b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "48":
    continueonerror: true
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "38"
    note: false
    quietmode: 0
    scriptarguments:
      increment_time:
        simple: ${incident.playbookpollinterval}
      panw_sn_category_mapping:
        simple: ${incident.panwservicenowcategorymap}
      servicenow_instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e5f0a5da-c296-4331-84ba-a0ae2b5fd9fd
      iscommand: false
      name: SendIncrementalPANWIoTDevicesToServiceNowOTClasses
      script: 7d7e97a4-d562-4abe-8428-1943618082dc
      type: regular
      version: -1
    taskid: e5f0a5da-c296-4331-84ba-a0ae2b5fd9fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1420
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1990,
        "width": 1885,
        "x": 50,
        "y": 50
      }
    }
  }
