contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 1.0.5
    packID: TestPack
    packName: TestPack
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
dirtyInputs: true
id: menachemtest1
inputSections:
- description: Generic group for inputs
  inputs:
  - aaaa
  name: General (Inputs group)
inputs:
- description: ""
  key: aaaa
  playbookInputQuery: null
  required: false
  value:
    simple: "2222"
name: menachemtest1
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8a91275c-7c0d-43ba-8a72-46ba6e6b5116
      iscommand: false
      name: ""
      version: -1
    taskid: 8a91275c-7c0d-43ba-8a72-46ba6e6b5116
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: test
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 1cc267d7-5f1a-46c7-81d1-f05effa0508e
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 1cc267d7-5f1a-46c7-81d1-f05effa0508e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
