contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    itemVersion: 1.1.3
    packID: AlibabaActionTrail
    packName: Alibaba Action Trail
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook investigates an “Alibaba ActionTrail - multiple unauthorized action attempts detected by a user” alert by gathering user and IP information and performing remediation based on the information gathered and received from the user.

  Used Sub-playbooks:
  * Enrichment for Verdict
  * Block IP - Generic v3

  To link this playbook to the relevant alerts automatically, we recommend using the following filters when configuring the playbook triggers:
  Alert Source = Correlation
  Alert Name = Alibaba ActionTrail - multiple unauthorized action attempts detected by a user
id: Alibaba ActionTrail - multiple unauthorized action attempts detected by a user
inputs:
- description: List of internal IP ranges
  key: InternalRange
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: PrivateIPs
      root: lists
      transformers:
      - args:
          error_if_no_match: {}
          ignore_case: {}
          multi_line: {}
          period_matches_newline: {}
          regex:
            value:
              simple: (\b(?:\d{1,3}\.){3}\d{1,3}\b/\d{1,2})
          unpack_matches: {}
        operator: RegexExtractAll
      - args:
          separator:
            value:
              simple: ','
        operator: join
name: Alibaba ActionTrail - multiple unauthorized action attempts detected by a user
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 030169ce-04fe-4391-8693-fa341acba921
      iscommand: false
      name: ""
      version: -1
    taskid: 030169ce-04fe-4391-8693-fa341acba921
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 370,
          "y": -110
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a515b62e-f38d-4134-8724-53130ed9ce09
      iscommand: false
      name: Enrich Indicators
      type: title
      version: -1
    taskid: a515b62e-f38d-4134-8724-53130ed9ce09
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 370,
          "y": 60
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8b64df8e-8740-4ca1-8e05-15f9e0966a18
      iscommand: false
      name: False Positive
      type: title
      version: -1
    taskid: 8b64df8e-8740-4ca1-8e05-15f9e0966a18
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1050,
          "y": 940
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "36"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e505acd0-fec4-4348-8e9c-fd2b0bbb372b
      iscommand: false
      name: True Positive
      type: title
      version: -1
    taskid: e505acd0-fec4-4348-8e9c-fd2b0bbb372b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 370,
          "y": 940
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      closeNotes:
        simple: The user confirmed that he made these multiple unauthorized API call
          attempts.
      closeReason:
        simple: false  positive
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 7f6ba393-b5f7-4683-8075-73872337076d
      iscommand: true
      name: Close the alert as False Positive
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 7f6ba393-b5f7-4683-8075-73872337076d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1050,
          "y": 1290
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cfc1aef7-7f3d-46cc-8577-00b2ed6dc22e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: cfc1aef7-7f3d-46cc-8577-00b2ed6dc22e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 640,
          "y": 1670
        }
      }
  "28":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: IPVerdict
                    operator: isEqualString
                    right:
                      value:
                        simple: Malicious
                root: IPVerdict
          operator: isNotEmpty
          right:
            value: {}
      label: Malicious IP
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "29"
      Malicious IP:
      - "20"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Continue based on verdict.
      id: abaa1e4a-e07b-4487-8acc-26952324d2a0
      iscommand: false
      name: Continue based on verdict
      type: condition
      version: -1
    taskid: abaa1e4a-e07b-4487-8acc-26952324d2a0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 370,
          "y": 390
        }
      }
  "29":
    continueonerrortype: ""
    form:
      description: 'We identified multiple unauthorized API call attempts initiated
        by your Alibaba user. Please confirm or deny that you initiated these activities. '
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Were the unauthorized action attempts made by you?
        options: []
        optionsarg:
        - simple: "No"
        - simple: "Yes"
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      sender: Your SOC team
      title: Unauthorized API call attempts were detected
      totalanswers: 0
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: "Hello,\n\nWe identified multiple unauthorized API call attempts initiated
          by your Alibaba user. Please confirm or deny that you initiated these activities. "
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: Unauthorized API call attempts were detected
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        complex:
          accessor: employeeemail
          root: alert
    nexttasks:
      '#none#':
      - "33"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: EmailAsk asks the user to confirm the multiple unauthorized API
        call attempts.
      id: dae4ed4a-afd2-4f74-8b1a-dc0673bfb02a
      iscommand: false
      name: EmailAsk User
      type: collection
      version: -1
    taskid: dae4ed4a-afd2-4f74-8b1a-dc0673bfb02a
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 700,
          "y": 570
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Continue investigating the alert manually and check whether:\n1-
        Additional activities initiated from the IP address and user account.\n2-
        Any successful API calls initiated by the user or IP address?\n3- The Alibaba
        user account has high privileges. "
      id: 090360c1-4876-422c-8de9-89b307901a11
      iscommand: false
      name: Continue Manual Investigation
      type: regular
      version: -1
    taskid: 090360c1-4876-422c-8de9-89b307901a11
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 370,
          "y": 1475
        }
      }
  "31":
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      CloseReason:
        simple: Resolved - False Positive,Resolved - Duplicate Incident,Resolved -
          Known Issue
      Domain:
        complex:
          accessor: domainname
          root: alert
      FileSHA256:
        complex:
          accessor: '[0]'
          root: alert.initiatorsha256
      IP:
        complex:
          accessor: '[0]'
          root: alert.remoteip
          transformers:
          - operator: uniq
      InternalRange:
        complex:
          root: inputs.InternalRange
      URL:
        complex:
          accessor: url
          root: alert
      User:
        complex:
          accessor: username
          root: alert
          transformers:
          - operator: uniq
      query:
        simple: remoteip:${alert.remoteip.[0]} and alertsource:${alert.sourceBrand}
          and alertname:${alert.name}
      threshold:
        simple: "5"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This playbook checks prior alert closing reasons and performs enrichment
        and prevalence checks on different IOC types. It then returns the information
        needed to establish the alert's verdict.
      id: 6a7ff31b-1051-454b-8536-3ca9b6198f93
      iscommand: false
      name: Enrichment for Verdict
      playbookId: Enrichment for Verdict
      type: playbook
      version: -1
    taskid: 6a7ff31b-1051-454b-8536-3ca9b6198f93
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 370,
          "y": 210
        }
      }
  "33":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: "0"
                root: Unauthorized API call attempts were detected.Answers
          operator: isEqualString
          right:
            value:
              simple: "Yes"
      label: "yes"
    continueonerrortype: ""
    id: "33"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Check if the user confirmed the activity.
      id: 724f2b0a-67a9-4c5b-8c0d-f250ce07b30e
      iscommand: false
      name: User confirmed the activity?
      type: condition
      version: -1
    taskid: 724f2b0a-67a9-4c5b-8c0d-f250ce07b30e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 700,
          "y": 740
        }
      }
  "34":
    continueonerrortype: ""
    id: "34"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    scriptarguments:
      AutoCommit:
        simple: "No"
      CustomBlockRule:
        simple: "True"
      IP:
        complex:
          accessor: remoteip
          root: alert
          transformers:
          - operator: uniq
      InputEnrichment:
        simple: "False"
      InternalRange:
        complex:
          root: inputs.InternalRange
      RuleDirection:
        simple: inbound
      RuleName:
        simple: XSOAR - Block IP playbook - ${alert.alertid}
      UserVerification:
        simple: "False"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook blocks malicious IP addresses using all integrations
        that are enabled. The direction of the traffic that will be blocked is determined
        by the Cortex user (and set by default to outgoing).\nNote the following:\n-
        Some of those integrations require specific parameters to run, which are based
        on the playbook inputs. Also, certain integrations use FW rules or appended
        network objects.\n- Note that the appended network objects should be specified
        in blocking rules inside the system later on. \n\n\nSupported integrations
        for this playbook [Network security products such as FW/WAF/IPs/etc.]: \n\n*
        Check Point Firewall\n* Palo Alto Networks PAN-OS\n* Zscaler\n* FortiGate\n*
        Aria Packet Intelligence\n* Cisco Firepower \n* Cisco Secure Cloud Analytics\n*
        Cisco ASA\n* Akamai WAF\n* F5 SilverLine\n* ThreatX\n* Signal Sciences WAF\n*
        Sophos Firewall\n\n"
      id: b8b32205-818f-4cfa-8137-6f1498497e88
      iscommand: false
      name: Block IP - Generic v3
      playbookId: Block IP - Generic v3
      type: playbook
      version: -1
    taskid: b8b32205-818f-4cfa-8137-6f1498497e88
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 90,
          "y": 1280
        }
      }
  "35":
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      severity:
        simple: Low
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 7cc51070-069e-4761-80f6-9a4e25f1f6f2
      iscommand: true
      name: Lower alert severity
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: 7cc51070-069e-4761-80f6-9a4e25f1f6f2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1050,
          "y": 1110
        }
      }
  "36":
    continueonerrortype: ""
    id: "36"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "30"
      "Yes":
      - "34"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Approve or deny automated remediation.
      id: 89662d70-5716-459a-8743-b4b3e974e784
      iscommand: false
      name: Should block IP?
      type: condition
      version: -1
    taskid: 89662d70-5716-459a-8743-b4b3e974e784
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 370,
          "y": 1110
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "28_20_Malicious IP": 0.38,
      "28_29_#default#": 0.53,
      "33_20_#default#": 0.49,
      "36_30_#default#": 0.54,
      "36_34_Yes": 0.6
    },
    "paper": {
      "dimensions": {
        "height": 1845,
        "width": 1340,
        "x": 90,
        "y": -110
      }
    }
  }
