contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.3
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to be run every 15 minutes via a job. Each run will get incremental
  updates for devices to send to ServiceNow server.
id: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eae012f6-9d8f-44da-893b-0eec057f25a2
      iscommand: false
      name: ""
      version: -1
    taskid: eae012f6-9d8f-44da-893b-0eec057f25a2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "42"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 5c093121-4c6c-4787-8218-05dca8369b9d
      iscommand: false
      name: Is ServiceNow integration enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 5c093121-4c6c-4787-8218-05dca8369b9d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: ServiceNow Integration is not enabled
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: b2892988-91ca-4322-83d3-f04071f37879
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: b2892988-91ca-4322-83d3-f04071f37879
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 76416a97-ed11-4bc2-838b-c4591653d6c9
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 76416a97-ed11-4bc2-838b-c4591653d6c9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: ${SN-IoT.incrementResult}
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: d46fcaa3-18df-48b5-89b0-3c49edc561b6
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: d46fcaa3-18df-48b5-89b0-3c49edc561b6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1770
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: c3a3f02e-1cc3-4869-8ab4-dbe0c77f86ea
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: c3a3f02e-1cc3-4869-8ab4-dbe0c77f86ea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1945
        }
      }
  "35":
    continueonerror: true
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "41"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get PANW IoT and ServiceNow category mapping
      id: 6a4f1a17-9103-484e-89eb-68e27a7b0f4c
      iscommand: false
      name: Get PANW IoT ServiceNow Category Mapping
      script: GetPANWIoTServiceNowCategoryMapping
      type: regular
      version: -1
    taskid: 6a4f1a17-9103-484e-89eb-68e27a7b0f4c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1070
        }
      }
  "36":
    continueonerror: true
    continueonerrortype: ""
    id: "36"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all customized table and column names in the customers' ServiceNow.
      id: 24525709-7a67-42ee-85bc-b347211f69bf
      iscommand: false
      name: Get ServiceNow Customized Configuration
      script: GetServiceNowCustomizedConfiguration
      type: regular
      version: -1
    taskid: 24525709-7a67-42ee-85bc-b347211f69bf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 895
        }
      }
  "37":
    continueonerror: true
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "38"
    note: false
    quietmode: 0
    scriptarguments:
      customized_servicenow_config:
        simple: ${PanwIot3rdParty.SNConfig}
      device_list:
        simple: ${PanwIot3rdParty.Devices}
      iot_servicenow_category_map:
        simple: ${PanwIot3rdParty.SNCategoryMapping}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send Incremental PANW IoT Devices To ServiceNow
      id: 6c999fc3-6fc9-4634-8c92-31afa688f4f3
      iscommand: false
      name: Send Incremental PANW IoT Devices To ServiceNow
      script: SendIncrementalPANWIoTDevicesToServiceNow
      type: regular
      version: -1
    taskid: 6c999fc3-6fc9-4634-8c92-31afa688f4f3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1420
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "26"
      "yes":
      - "39"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 23e37dd1-96e0-4bfe-84f5-c3dc61cd3709
      iscommand: false
      name: Was there an error when sending devices to servicenow?
      script: isError
      type: condition
      version: -1
    taskid: 23e37dd1-96e0-4bfe-84f5-c3dc61cd3709
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1595
        }
      }
  "39":
    continueonerror: true
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "40"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to do incremental device sync to ServiceNow. Please
          see the detailed error message from the playbook.'
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 5119d1ee-faca-436b-8b58-2da3ff003f25
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 5119d1ee-faca-436b-8b58-2da3ff003f25
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1770
        }
      }
  "40":
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 28f2756a-63b3-4918-8bf5-1c9f88b142df
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 28f2756a-63b3-4918-8bf5-1c9f88b142df
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1945
        }
      }
  "41":
    continueonerror: true
    continueonerrortype: ""
    id: "41"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      increment_time:
        simple: "15"
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Returns a list of assets for the specified asset type.
      id: a9f441fc-8eaf-477b-8145-9d140fb17c9d
      iscommand: true
      name: Get PANW IoT Devices
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-asset-list
      type: regular
      version: -1
    taskid: a9f441fc-8eaf-477b-8145-9d140fb17c9d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1245
        }
      }
  "42":
    continueonerror: true
    continueonerrortype: ""
    id: "42"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "43"
      "no":
      - "44"
      "yes":
      - "46"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1702c79e-ddae-4a8d-8589-5d531fbcf893
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 1702c79e-ddae-4a8d-8589-5d531fbcf893
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "43":
    continueonerror: true
    continueonerrortype: ""
    id: "43"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: de5b4dbe-c8ad-4987-8a5a-ea4b17bb29ac
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: de5b4dbe-c8ad-4987-8a5a-ea4b17bb29ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "44":
    continueonerror: true
    continueonerrortype: ""
    id: "44"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 14fc5555-0413-4890-89b8-ce36e1ae0705
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 14fc5555-0413-4890-89b8-ce36e1ae0705
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "45":
    continueonerror: true
    continueonerrortype: ""
    id: "45"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 52d9bbfe-f3a9-4598-8142-793b21ffe069
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 52d9bbfe-f3a9-4598-8142-793b21ffe069
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "46":
    continueonerrortype: ""
    id: "46"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "47"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get ServiceNow Table Mapping Method
      id: 98eba808-88eb-41e2-8650-74ef802554aa
      iscommand: true
      name: Get ServiceNow Mapping Method
      script: '|||get-mapping-method'
      type: regular
      version: -1
    taskid: 98eba808-88eb-41e2-8650-74ef802554aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "47":
    continueonerrortype: ""
    id: "47"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "36"
      "yes":
      - "48"
    note: false
    quietmode: 0
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${SN.MappingMethod}
      right:
        simple: Use ServiceNow Classes
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 894f7171-1087-491f-810a-6ec72e2c74ba
      iscommand: false
      name: Is ServiceNow OT Mapping?
      script: AreValuesEqual
      type: condition
      version: -1
    taskid: 894f7171-1087-491f-810a-6ec72e2c74ba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "48":
    continueonerror: true
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "38"
    note: false
    quietmode: 0
    scriptarguments:
      increment_time:
        simple: ${incident.playbookpollinterval}
      panw_sn_category_mapping:
        simple: ${incident.panwservicenowcategorymap}
      servicenow_instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9d17842a-c7bf-4d39-8272-254853047050
      iscommand: false
      name: SendIncrementalPANWIoTDevicesToServiceNowOTClasses
      script: 7d7e97a4-d562-4abe-8428-1943618082dc
      type: regular
      version: -1
    taskid: 9d17842a-c7bf-4d39-8272-254853047050
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1420
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1990,
        "width": 1885,
        "x": 50,
        "y": 50
      }
    }
  }
