contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Vulnerability to ServiceNow.
id: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3c9f2361-e0ce-4f85-8614-b174c7466671
      iscommand: false
      name: ""
      version: -1
    taskid: 3c9f2361-e0ce-4f85-8614-b174c7466671
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: ae828322-fac2-4ee1-8d4f-edf1070783ba
      iscommand: false
      name: Is ServiceNow available
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: ae828322-fac2-4ee1-8d4f-edf1070783ba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Servicenow instance is not enabled
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: b720b094-ad99-401e-8ede-30406569486c
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: b720b094-ad99-401e-8ede-30406569486c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 54ff53de-679f-402f-8317-46c5b644eb1c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 54ff53de-679f-402f-8317-46c5b644eb1c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${incident.correlation_id}
      asset_type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given a asset ID (alert-id, vulnerability-id or mac-address)
        returns the asset details.
      id: afb12b51-d51b-4719-8c50-12e690accaea
      iscommand: true
      name: Get single vulnerability instance
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-single-asset
      type: regular
      version: -1
    taskid: afb12b51-d51b-4719-8c50-12e690accaea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 448b081d-4c99-448b-89fc-e14ef6a3dc72
      iscommand: false
      name: Does the vulnerability exist?
      script: Exists
      type: condition
      version: -1
    taskid: 448b081d-4c99-448b-89fc-e14ef6a3dc72
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Cannot find vulnerability with zb_ticketid ${incident.correlation_id}
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: b5fef316-2c9e-45a6-8955-9475716f22aa
      iscommand: true
      name: Send error status back to PANW IoT
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: b5fef316-2c9e-45a6-8955-9475716f22aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 71595a59-aac3-4e24-849d-9b8d01e1ae8a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 71595a59-aac3-4e24-849d-9b8d01e1ae8a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_list:
        simple: ${PanwIot3rdParty.SingleAsset}
      asset_type:
        simple: vulnerability
      incident:
        simple: ${incident}
      output_format:
        simple: ServiceNow
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given asset (alert, device, vuln) converts it to 3rd party
        format.
      id: 8d10cf6d-1654-4143-896f-10462f54aea2
      iscommand: true
      name: Convert vulnerability to ServiceNow format
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-convert-assets-to-external-format
      type: regular
      version: -1
    taskid: 8d10cf6d-1654-4143-896f-10462f54aea2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "12"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 2434f423-e7b2-4fc7-85a6-31ae0f7c73e2
      iscommand: false
      name: Was there an error when converting format?
      script: isError
      type: condition
      version: -1
    taskid: 2434f423-e7b2-4fc7-85a6-31ae0f7c73e2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Cannot convert vulnerability to servicenow data format
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: c1b56aca-3df3-45c2-8094-c71baaba6178
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: c1b56aca-3df3-45c2-8094-c71baaba6178
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 869f50b3-f976-408c-80b3-2fddd9c33273
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 869f50b3-f976-408c-80b3-2fddd9c33273
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      fields:
        simple: ${PanwIot3rdParty.VulnerabilityServiceNow}
      table_name:
        simple: u_zingbox_alerts_vulnerability_incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: PANW IoT 3rd Party Integration - ServiceNow v2
      description: Creates a new record in the specified ServiceNow table.
      id: 033f5e44-b11e-4222-8957-557c12af7532
      iscommand: true
      name: Create Servicenow record
      script: PANW IoT 3rd Party Integration - ServiceNow v2|||servicenow-create-record
      type: regular
      version: -1
    taskid: 033f5e44-b11e-4222-8957-557c12af7532
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "16"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: be43154c-daf3-4fb2-83ea-1fbfbaf5998f
      iscommand: false
      name: Was there an error when creating the record in Servicenow?
      script: isError
      type: condition
      version: -1
    taskid: be43154c-daf3-4fb2-83ea-1fbfbaf5998f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1245
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Failed to send vulnerability to ServiceNow
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 4e67d36e-6853-4c4c-8722-be6fe29a597c
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 4e67d36e-6853-4c4c-8722-be6fe29a597c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1420
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 566c4a44-1088-4cc8-8639-a380ee0e78fd
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 566c4a44-1088-4cc8-8639-a380ee0e78fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1595
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Success to send vulnerability instance zb_ticket id ${incident.correlation_id}
          to ServiceNow
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: db282233-2412-4618-83d3-83869cf96ae1
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: db282233-2412-4618-83d3-83869cf96ae1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1420
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 9493b571-1181-443c-868f-19856f2caef4
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 9493b571-1181-443c-868f-19856f2caef4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1595
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1640,
        "width": 1455,
        "x": 50,
        "y": 50
      }
    }
  }
