contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.15
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 1ddb7f09-edae-429e-89fc-e98279e60fd2
inputs: []
name: Get Nexpose Engines, Sites and Templates - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 1ddb7f09-edae-429e-89fc-e98279e60fd2
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9448cf78-b3a4-423a-801b-6512af20ba2f
      iscommand: false
      name: ""
      version: -1
    taskid: 9448cf78-b3a4-423a-801b-6512af20ba2f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 600,
          "y": -510
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "15"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Rapid7 Nexpose
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 2519f3b2-38c6-4d9a-80bb-ba695de99808
      iscommand: false
      name: Is Rapid7 Nexpose Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 2519f3b2-38c6-4d9a-80bb-ba695de99808
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 590,
          "y": -370
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: rapid7
      message:
        simple: Rapid7 Nexpose Integration is not enabled
      playbook_name:
        simple: Get Nexpose Engines, Sites and Templates - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 05fd857b-3565-4b1d-8635-480ee8f4f1d8
      iscommand: true
      name: Send Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 05fd857b-3565-4b1d-8635-480ee8f4f1d8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      rapid7_instance:
        simple: ${incident.integrationinstancename}
      scanner_sync:
        simple: ${incident.automaticallysynchronizescannerswithiotsecuritytoavoidfalsesecurityalerts}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get list of Rapid7 Sites, Templates and  Engines and write to context
      id: 49695c62-10ab-403f-830b-89cab4c72723
      iscommand: false
      name: Get list of Rapid7 Sites, Engines and Templates Options
      script: GetRapid7SitesTemplatesAndEngines
      type: regular
      version: -1
    taskid: 49695c62-10ab-403f-830b-89cab4c72723
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 6fcdadcb-ee23-46ed-8850-c7b61a3124d1
      iscommand: false
      name: Was There an Error Getting Engine, Site and Template Lists?
      script: isError
      type: condition
      version: -1
    taskid: 6fcdadcb-ee23-46ed-8850-c7b61a3124d1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: rapid7
      message:
        simple: Error while getting engine, site and template list
      playbook_name:
        simple: Get Nexpose Engines, Sites and Templates - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: c2913428-0883-401e-89bf-d2bfb69a0892
      iscommand: true
      name: Send Error Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: c2913428-0883-401e-89bf-d2bfb69a0892
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: rapid7
      message:
        simple: Rapid7 Nexpose Engine, Site and Templates are updated successfully
      playbook_name:
        simple: Get Nexpose Engines, Sites and Templates - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 988d750c-1c75-4d82-85c0-639702a61d28
      iscommand: true
      name: Send Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 988d750c-1c75-4d82-85c0-639702a61d28
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1070
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 04eb097c-b6ab-4945-8d91-099060695e1a
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 04eb097c-b6ab-4945-8d91-099060695e1a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1245
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "12"
      "no":
      - "13"
      "yes":
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Rapid7 Nexpose
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 21fe7617-2a92-4de4-8a68-a4b0277fb0a1
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 21fe7617-2a92-4de4-8a68-a4b0277fb0a1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 120
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: rapid7
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Get Nexpose Engines, Sites and Templates - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: c1d6faa8-b430-4f19-8435-8a985bae7783
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: c1d6faa8-b430-4f19-8435-8a985bae7783
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1370,
          "y": 370
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: rapid7
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Get Nexpose Engines, Sites and Templates - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 0b1715ed-f9ee-4b39-8bd8-0255bce4bab3
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 0b1715ed-f9ee-4b39-8bd8-0255bce4bab3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1790,
          "y": 370
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 0e548821-a7d3-4642-84ac-89c34d9e871c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 0e548821-a7d3-4642-84ac-89c34d9e871c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1570,
          "y": 545
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "16"
      "yes":
      - "11"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Rapid7 Nexpose
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: e8b9acd4-ce8b-4eca-8eab-917865acb4e2
      iscommand: false
      name: Is Rapid7 Nexpose  Integration Instance Enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: e8b9acd4-ce8b-4eca-8eab-917865acb4e2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": -80
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: rapid7
      message:
        simple: Rapid7 Nexpose Integration is not enabled
      playbook_name:
        simple: Get Nexpose Engines, Sites and Templates - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 9455fa25-347a-448e-89ea-783e05f5de17
      iscommand: true
      name: Send Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 9455fa25-347a-448e-89ea-783e05f5de17
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1850,
        "width": 2530,
        "x": 50,
        "y": -510
      }
    }
  }
