contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 53b142cd-d8f2-4d84-874c-2c6ccbb9f891
inputs: []
name: Import Aruba AirWave VisualRF Floor Plans to PANW IoT
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2ed5c3ab-2020-4a72-8c0f-c4d96377dc6e
      iscommand: false
      name: ""
      version: -1
    taskid: 2ed5c3ab-2020-4a72-8c0f-c4d96377dc6e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b45a6831-b425-4091-8216-e6a2b7225db1
      iscommand: false
      name: Import Aruba AirWave Location Data
      script: 701bf9e6-3948-41b8-8aa9-b9098d069049
      type: regular
      version: -1
    taskid: b45a6831-b425-4091-8216-e6a2b7225db1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1677.5,
          "y": 720
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      file_list:
        simple: ${InfoFile}
      instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 87763278-021a-4753-830a-1f672ad9d15c
      iscommand: false
      name: Upload Floor Plans to IoT
      script: d04b33ef-792c-48bb-84c4-fa6f1b3a3bf1
      type: regular
      version: -1
    taskid: 87763278-021a-4753-830a-1f672ad9d15c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1677.5,
          "y": 895
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "no":
      - "9"
      "yes":
      - "10"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba AirWave
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 0611a432-ed7f-4db3-87d8-0f41ebbe65f0
      iscommand: false
      name: Is Aruba AirWave integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 0611a432-ed7f-4db3-87d8-0f41ebbe65f0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 370
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: ad3bee86-0cf2-452e-8f60-cff0b321d52a
      iscommand: false
      name: Is Aruba AirWave Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: ad3bee86-0cf2-452e-8f60-cff0b321d52a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: aruba_airwave
      message:
        simple: No SolarWinds Integration instance passed
      playbook_name:
        simple: Import Aruba AirWave assets to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 7958ad23-6a10-4f0e-810e-e71b064fd73c
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 7958ad23-6a10-4f0e-810e-e71b064fd73c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: Invalid integration instance name provided
      playbook_name:
        simple: Import Aruba AirWave FloorPlans to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 3e8d68db-1a64-4072-83ce-dafd156b38f2
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 3e8d68db-1a64-4072-83ce-dafd156b38f2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: SolarWinds UDT integration is not enabled
      playbook_name:
        simple: Import Aruba AirWave VisualRF Floor Plans to PANW IoT
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 8ddc5baf-9c5a-4c47-83a9-b0431b0d8787
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 8ddc5baf-9c5a-4c47-83a9-b0431b0d8787
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "13"
      "no":
      - "12"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - Aruba AirWave
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dc941cb1-8391-4399-89b7-6a9b58b5f138
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: dc941cb1-8391-4399-89b7-6a9b58b5f138
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: f4ff8e30-db0f-439f-8d97-586e431ca53d
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f4ff8e30-db0f-439f-8d97-586e431ca53d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import Aruba AirWave VisualRF Floor Plans to PANW IoT
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: be0fbfcf-eada-449a-8b72-b7646e592e32
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: be0fbfcf-eada-449a-8b72-b7646e592e32
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1247.5,
          "y": 720
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import Aruba AirWave VisualRF Floor Plans to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 5f0ed799-2e76-436c-8785-de3ee0cee8b3
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 5f0ed799-2e76-436c-8785-de3ee0cee8b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1022.5,
          "y": 895
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 531822a5-62d1-4941-8bed-5d12fb267595
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 531822a5-62d1-4941-8bed-5d12fb267595
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1462.5,
          "y": 1070
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 2007.5,
        "x": 50,
        "y": 50
      }
    }
  }
