contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 6c5ee2fe-98bf-40ab-8ab0-c624a765cab3
inputs: []
name: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT Cloud
outputs: []
sourceplaybookid: 985135c8-3cc9-43b1-8783-926b487a076d
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 33b139e2-7711-4470-865e-8a3b3c8721df
      iscommand: false
      name: ""
      version: -1
    taskid: 33b139e2-7711-4470-865e-8a3b3c8721df
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 20
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "11"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - BlueCat IPAM
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: b3a53301-603a-472d-8358-3f4ffae1f3d8
      iscommand: false
      name: Is BlueCat enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: b3a53301-603a-472d-8358-3f4ffae1f3d8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 960,
          "y": 400
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ipam_bluecat
      message:
        simple: BlueCat IPAM integration is not enabled
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 0525ed45-4e49-46cf-8e34-9fdeac940f8d
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 0525ed45-4e49-46cf-8e34-9fdeac940f8d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 280,
          "y": 570
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 969df54d-a1a5-4baa-867b-a2650b6e5cae
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 969df54d-a1a5-4baa-867b-a2650b6e5cae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": 770
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      bluecat_instance_name:
        simple: ${incident.integrationinstancename}
      data_overwrite:
        simple: ${incident.useipamnonsitedataifthesameblockorsubnetisiniotsecurity}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a193d4c6-3a4d-4f8e-8b17-386604d5e80d
      iscommand: false
      name: Export BlueCat Subnet Info and Update PANW IoT cloud
      script: BlueCatIPAMGetSubnetNetwork
      type: regular
      version: -1
    taskid: a193d4c6-3a4d-4f8e-8b17-386604d5e80d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 720
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: fd586e7b-ddc1-4f93-88b5-29b5799761ac
      iscommand: false
      name: Was there an error when sending devices to PANW IoT Cloud?
      script: isError
      type: condition
      version: -1
    taskid: fd586e7b-ddc1-4f93-88b5-29b5799761ac
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 895
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ipam_bluecat
      message:
        simple: 'Error: Failed to do a bulk export BlueCat IPAM Data'
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: d598ff33-115b-4afe-8b08-ed75a3d2cc64
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: d598ff33-115b-4afe-8b08-ed75a3d2cc64
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 1070
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 56e9b7bc-b929-4ffa-8b3f-7979d3a71552
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 56e9b7bc-b929-4ffa-8b3f-7979d3a71552
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 1245
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 8fc18bc3-8efb-42ab-863d-6af9521b8c5a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8fc18bc3-8efb-42ab-863d-6af9521b8c5a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1245
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ipam_bluecat
      message:
        simple: Successfully exported BlueCat IPAM Data
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: fb5e4fda-858a-4c80-86c2-6b3e10346574
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: fb5e4fda-858a-4c80-86c2-6b3e10346574
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1070
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "no":
      - "12"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - BlueCat IPAM
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f122f9cc-1bc2-411d-84ab-2a815b98ce33
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: f122f9cc-1bc2-411d-84ab-2a815b98ce33
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 980,
          "y": 610
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ipam_bluecat
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Bulk Import of subnet network info from BlueCat IPAM to PANW IoT Cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 28428619-eded-4dea-8281-5ecd75352fd0
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 28428619-eded-4dea-8281-5ecd75352fd0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 850
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 27c3be20-28d7-4941-8cf9-663b101adc5c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 27c3be20-28d7-4941-8cf9-663b101adc5c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1020
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ipam_bluecat
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Bulk Import of subnet network info from BlueCat IPAM to PANW IoT Cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 40fdf414-bfe8-4a19-8ff4-79f764b8abad
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 40fdf414-bfe8-4a19-8ff4-79f764b8abad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 670,
          "y": 850
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "16"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: ac19f08b-8f67-4aff-88c1-f757618249fb
      iscommand: false
      name: Is BlueCat IPAM Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: ac19f08b-8f67-4aff-88c1-f757618249fb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 175
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ipam_bluecat
      message:
        simple: No BlueCat IPAM integration is passed
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: cb82afc2-f7f6-41bc-863c-1167d22493b5
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: cb82afc2-f7f6-41bc-863c-1167d22493b5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -140,
          "y": 530
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "15_16_no": 0.14
    },
    "paper": {
      "dimensions": {
        "height": 1320,
        "width": 2300,
        "x": -140,
        "y": 20
      }
    }
  }
