contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.11
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Fetch data from Aruba Central and send it to PANW IoT Platform
id: 4a533dc2-f0c7-4819-8250-bf12743d5270
inputs: []
name: Import Aruba Central devices to PANW IoT cloud
outputs: []
sourceplaybookid: Import Aruba WLC devices to PANW IoT cloud
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 39776879-2080-4658-8590-1d7769c305c0
      iscommand: false
      name: ""
      version: -1
    taskid: 39776879-2080-4658-8590-1d7769c305c0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "no":
      - "2"
      "yes":
      - "19"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba Central
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 5e5ef922-7a5c-44ea-8fcd-27d2835b6170
      iscommand: false
      name: Is Aruba Central integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 5e5ef922-7a5c-44ea-8fcd-27d2835b6170
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 370
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_central
      message:
        simple: Aruba Central integration is not enabled
      playbook_name:
        simple: Import Aruba Central devices to PANW IoT cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: d0fb7673-b781-404e-8b35-83a971ce5ec7
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: d0fb7673-b781-404e-8b35-83a971ce5ec7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 545
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 59fd0535-5f1e-4121-8eb6-f257650abb8d
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 59fd0535-5f1e-4121-8eb6-f257650abb8d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1902.5,
          "y": 895
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      active_aruba_central_instance:
        simple: ${incident.integrationinstancename}
      get_wired_clients:
        simple: ${incident.importarubacentralwiredclientdetailstoiotsecurity}
      limit:
        simple: "1000"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 027257b5-aa87-4925-8575-960278e2dcfa
      iscommand: false
      name: Send Aruba Central clients to PANW IoT
      script: 5616fc46-082b-46ac-86d9-f1f317c8aed8
      type: regular
      version: -1
    taskid: 027257b5-aa87-4925-8575-960278e2dcfa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1902.5,
          "y": 720
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_central
      message:
        simple: Invalid integration instance name provided
      playbook_name:
        simple: Import Aruba Central devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 0cd18740-e737-4c10-8711-18782bc93768
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 0cd18740-e737-4c10-8711-18782bc93768
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 545
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "20"
      "no":
      - "21"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - Aruba Central
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9e9b064b-7df6-4055-8877-7a00e01a1b58
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 9e9b064b-7df6-4055-8877-7a00e01a1b58
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1462.5,
          "y": 545
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_central
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import Aruba Central devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: feb1548c-8af3-4ae5-835f-189efece30ad
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: feb1548c-8af3-4ae5-835f-189efece30ad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1032.5,
          "y": 720
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_central
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import Aruba Central devices to PANW IoT cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: ca60a5c5-b770-46ef-8a95-ee687813d38a
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: ca60a5c5-b770-46ef-8a95-ee687813d38a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1462.5,
          "y": 720
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 28b72edb-ebf7-4d98-8758-efeaa32e18dd
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 28b72edb-ebf7-4d98-8758-efeaa32e18dd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1227.5,
          "y": 895
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: d5445a9d-7e85-4b3c-87d7-edf0bce8c532
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d5445a9d-7e85-4b3c-87d7-edf0bce8c532
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 720
        }
      }
  "24":
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "25"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: a5b469d6-f0bd-4996-8340-b66b7bb0d065
      iscommand: false
      name: Is Aruba Central Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: a5b469d6-f0bd-4996-8340-b66b7bb0d065
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: aruba_central
      message:
        simple: No Aruba Central Integration instance passed
      playbook_name:
        simple: Import Aruba Central devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 029c3e7b-01cd-46f9-8e93-700a8cfbd420
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 029c3e7b-01cd-46f9-8e93-700a8cfbd420
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_18_#default#": 0.66,
      "1_2_no": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 2232.5,
        "x": 50,
        "y": 50
      }
    }
  }
