contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to be run every 15 minutes via a job. Each run will get incremental
  updates for devices, and will update or create new endpoints in Aruba ClearPass
  with PANW IOT discovered attributes (ClearPass custom attributes).
dirtyInputs: true
id: d9127f9b-79ad-4be1-8f6d-8947eac4405d
inputs: []
name: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: Incremental Export to Cisco ISE - PANW IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 61f67a95-f67d-4d43-89d4-55771cd4574c
      iscommand: false
      name: ""
      version: -1
    taskid: 61f67a95-f67d-4d43-89d4-55771cd4574c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "20"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba ClearPass
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 62caf471-a41b-425f-8eac-22264eb67a35
      iscommand: false
      name: Is Aruba ClearPass enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 62caf471-a41b-425f-8eac-22264eb67a35
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: clearpass
      message:
        simple: Aruba ClearPass instance is not configured
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 90ccd560-232e-4536-8bb6-4612f8b174da
      iscommand: true
      name: Send disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 90ccd560-232e-4536-8bb6-4612f8b174da
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      active_aruba_cp_instance:
        simple: ${incident.integrationinstancename}
      custom_attributes:
        simple: ${incident.panwiotdevicecustomattributes}
      device_maps:
        simple: ${PanwIot3rdParty.ArubaClearPassAttributes}
      increment_time:
        simple: ${incident.playbookpollinterval}
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
      sites:
        simple: ${incident.sitenames}
      tags:
        simple: ${incident.panwiotinscopetagenforcement}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d0ff32b2-ceed-4442-8161-a048b8976cc0
      iscommand: false
      name: Send devices to Aruba ClearPass
      script: SendPANWIoTDevicesToArubaClearPass
      type: regular
      version: -1
    taskid: d0ff32b2-ceed-4442-8161-a048b8976cc0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 545
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "17"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: f09b1303-35ca-4d5d-85ac-3206c91e5d3c
      iscommand: false
      name: Was there an error while exporting devices?
      script: isError
      type: condition
      version: -1
    taskid: f09b1303-35ca-4d5d-85ac-3206c91e5d3c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 720
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: clearpass
      message:
        simple: 'Failed to export PANW IoT devices to  Aruba ClearPass '
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 6c604f20-c1dc-4c3f-8c41-4ddc27f87f36
      iscommand: true
      name: Send error status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 6c604f20-c1dc-4c3f-8c41-4ddc27f87f36
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 895
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: clearpass
      message:
        simple: ${PaloAltoIoTIntegrationBase.Status}
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 89274fa1-61e9-48b1-81e1-1a823b8d14aa
      iscommand: true
      name: Send success status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 89274fa1-61e9-48b1-81e1-1a823b8d14aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 895
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: da968724-bbf8-40f5-8925-3d265a2845de
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: da968724-bbf8-40f5-8925-3d265a2845de
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 1070
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "21"
      "no":
      - "22"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Aruba ClearPass
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f5bf3e5e-6bfc-4c5a-8df5-a45386cb1a81
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: f5bf3e5e-6bfc-4c5a-8df5-a45386cb1a81
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 705,
          "y": 370
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: clearpass
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 8179dc62-05f7-4da9-83f4-161d1a26e231
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 8179dc62-05f7-4da9-83f4-161d1a26e231
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: clearpass
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 4c7799d5-142a-473c-8739-957ef6224ff1
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 4c7799d5-142a-473c-8739-957ef6224ff1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 545
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 778d7259-dbb8-44c9-8c07-9c618d94f35a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 778d7259-dbb8-44c9-8c07-9c618d94f35a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1680,
        "x": 50,
        "y": 50
      }
    }
  }
