contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This Playbook pushes dacl/sgacls from IoT cloud to Cisco ISE integration
dirtyInputs: true
id: 97b30c69-0797-453b-80c3-6b2ffdaee432
inputs: []
name: ACL Push to Cisco ISE-PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b46d4c26-839d-4931-81c6-289fe05baf26
      iscommand: false
      name: ""
      version: -1
    taskid: b46d4c26-839d-4931-81c6-289fe05baf26
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      acl_type:
        simple: ${incident.ACLType}
      acls:
        simple: ${incident.aclContent}
      active_ise_instance:
        simple: ${PaloAltoIoTIntegrationBase.ActiveNodeInstance}
      authorization_profile:
        simple: ${incident.authorizationProfileNames}
      jobId:
        simple: ${incident.jobId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Creates or Updates ACLs in Cisco ISE.
      id: d5169ec2-80f0-43bd-87df-c0aec9ad6775
      iscommand: false
      name: CreateOrUpdateACLs
      script: CreateOrUpdatePANWIoTACLsToCiscoISE
      type: regular
      version: -1
    taskid: d5169ec2-80f0-43bd-87df-c0aec9ad6775
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 370
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 67984f48-b304-4a4e-838b-a2bb527db7b9
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 67984f48-b304-4a4e-838b-a2bb527db7b9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 895
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobId}
      message:
        simple: successfully pushed acls to Cisco ISE
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Reports ACLs sync status
      id: 45030539-b417-44a9-8636-b4cccf44da84
      iscommand: true
      name: Report ACL sync status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-aclsync-status'
      type: regular
      version: -1
    taskid: 45030539-b417-44a9-8636-b4cccf44da84
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobId}
      message:
        simple: Failed to push acl sync status
      status:
        simple: failed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Reports ACLs sync status
      id: 4b36aac1-24a3-43be-8736-21bbb1567dab
      iscommand: true
      name: Report failed ACL sync status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-aclsync-status'
      type: regular
      version: -1
    taskid: 4b36aac1-24a3-43be-8736-21bbb1567dab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      - "11"
      "yes":
      - "4"
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 25d27be9-980e-43a9-82be-136b64a12fd4
      iscommand: false
      name: Is there any error?
      script: isError
      type: condition
      version: -1
    taskid: 25d27be9-980e-43a9-82be-136b64a12fd4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 545
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      - "13"
      "yes":
      - "1"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Cisco ISE
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 201741c9-ab7a-4736-8193-e70a3640134c
      iscommand: false
      name: Is Cisco ISE enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 201741c9-ab7a-4736-8193-e70a3640134c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${PaloAltoIoTIntegrationBase.ActiveNodeInstance}
      integration_name:
        simple: ise
      message:
        simple: Cisco ISE instance is not enabled
      playbook_name:
        simple: ACL Push to Cisco ISE-PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 6f614f76-c523-4286-8d50-fae0697c3989
      iscommand: true
      name: Send disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 6f614f76-c523-4286-8d50-fae0697c3989
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${PaloAltoIoTIntegrationBase.ActiveNodeInstance}
      integration_name:
        simple: ise
      message:
        simple: ACLs are successfully pushed to Cisco ISE
      playbook_name:
        simple: ACL Push to Cisco ISE-PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 527a5b62-89e7-4d3c-8246-0cf93d67e8df
      iscommand: true
      name: Send success status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 527a5b62-89e7-4d3c-8246-0cf93d67e8df
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${PaloAltoIoTIntegrationBase.ActiveNodeInstance}
      integration_name:
        simple: ise
      message:
        simple: Error while pushing the ACLs to Cisco ISE
      playbook_name:
        simple: ACL Push to Cisco ISE-PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 9ef22ea0-1055-41c2-8aae-afb760091a7a
      iscommand: true
      name: Send error status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 9ef22ea0-1055-41c2-8aae-afb760091a7a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 720
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobId}
      message:
        simple: Cisco ISE instance is disabled
      status:
        simple: failed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Reports ACLs sync status
      id: fac47ef8-1bf8-4272-898c-6af9ee0a20c1
      iscommand: true
      name: Report failed ACL sync status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-aclsync-status'
      type: regular
      version: -1
    taskid: fac47ef8-1bf8-4272-898c-6af9ee0a20c1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 2530,
        "x": 50,
        "y": 50
      }
    }
  }
