contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d898a03f-1c19-46a7-8a2d-0d3660a3c374
inputs: []
name: Import Aruba AirWave VisualRF Clients to PANW IoT
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6c361ec1-d60d-48f0-8e8a-6f403aa0fcf5
      iscommand: false
      name: ""
      version: -1
    taskid: 6c361ec1-d60d-48f0-8e8a-6f403aa0fcf5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 275,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 12289e41-870a-4bd8-852e-cbee6a237264
      iscommand: false
      name: Send Aruba AirWave VRF Clients to PANW IoT
      script: 2f11929a-9cbc-443b-8899-557fcdd0f227
      type: regular
      version: -1
    taskid: 12289e41-870a-4bd8-852e-cbee6a237264
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1790,
          "y": 720
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 93e38b77-772c-4a1b-8f28-02d841dbba0d
      iscommand: false
      name: Is Aruba AirWave Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: 93e38b77-772c-4a1b-8f28-02d841dbba0d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 195
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: aruba_airwave
      message:
        simple: No SolarWinds Integration instance passed
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 64a11ec2-1b04-42e5-86dd-5989d099b436
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 64a11ec2-1b04-42e5-86dd-5989d099b436
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "no":
      - "7"
      "yes":
      - "8"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba AirWave
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: e588ad5c-ace8-42e0-83c8-37779df9f71f
      iscommand: false
      name: Is Aruba AirWave integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: e588ad5c-ace8-42e0-83c8-37779df9f71f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 705,
          "y": 370
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: Invalid integration instance name provided
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: c15912df-4f4f-4724-8a67-7056bfe9450f
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: c15912df-4f4f-4724-8a67-7056bfe9450f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: SolarWinds UDT integration is not enabled
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 779ea7ae-83c2-4e6d-8a76-ce9c499960b9
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 779ea7ae-83c2-4e6d-8a76-ce9c499960b9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "13"
      "no":
      - "9"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - Aruba AirWave
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f7cddb5f-7625-432f-871a-d493171ed15d
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: f7cddb5f-7625-432f-871a-d493171ed15d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 545
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 58bf9182-bdca-4044-8455-88aac1b19291
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 58bf9182-bdca-4044-8455-88aac1b19291
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 720
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: b0378eb2-e9e7-4d88-88f8-91a3eacc58ce
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: b0378eb2-e9e7-4d88-88f8-91a3eacc58ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1565,
          "y": 895
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 7d12e5b5-af1b-489b-8e71-bb152192e2bd
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 7d12e5b5-af1b-489b-8e71-bb152192e2bd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 720
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 2787c36e-41d7-41ff-836d-ec1c32fd8478
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 2787c36e-41d7-41ff-836d-ec1c32fd8478
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 2120,
        "x": 50,
        "y": 50
      }
    }
  }
