contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: 'Playbook used to check pxGrid account status. '
id: 42657470-5b69-4793-8018-b3a746d7d11f
inputs: []
name: Setup pxGrid Account
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b941e8a2-7175-4584-8328-261841a227ed
      iscommand: false
      name: ""
      version: -1
    taskid: b941e8a2-7175-4584-8328-261841a227ed
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 410,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Cisco ISE pxGrid
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: c05ff546-4ea7-4e8f-8e6b-e1beeea1187b
      iscommand: false
      name: Is pxGrid Integration enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: c05ff546-4ea7-4e8f-8e6b-e1beeea1187b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 410,
          "y": 230
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: pxgrid
      message:
        simple: pxGrid integration is not enabled
      playbook_name:
        simple: Setup pxGrid Account
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: e698c89c-958b-4db3-8cc1-43844d6e7a38
      iscommand: true
      name: Report disabled status to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: e698c89c-958b-4db3-8cc1-43844d6e7a38
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 160,
          "y": 460
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets pxGrid account status
      id: 91792904-2bf7-4dbe-8cb5-6100e4e24c2b
      iscommand: true
      name: Get pxGrid Status
      script: '|||pxgrid-get-account-status'
      type: regular
      version: -1
    taskid: 91792904-2bf7-4dbe-8cb5-6100e4e24c2b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 640,
          "y": 460
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 832cae43-cf3e-4aa0-8da3-0306de4478ab
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 832cae43-cf3e-4aa0-8da3-0306de4478ab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 400,
          "y": 670
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 715,
        "width": 860,
        "x": 160,
        "y": 50
      }
    }
  }
