contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.3
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook gets all available device inventory from PANW IoT Cloud
  and updates/creates endpoints with custom attributes on ServiceNow.
id: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 98b05920-0d67-4721-813b-90a5d80f20fd
      iscommand: false
      name: ""
      version: -1
    taskid: 98b05920-0d67-4721-813b-90a5d80f20fd
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "12"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: b07b896a-11ac-4dde-87dc-afe9b21a1124
      iscommand: false
      name: Is ServiceNow enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: b07b896a-11ac-4dde-87dc-afe9b21a1124
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      customized_servicenow_config:
        simple: ${PanwIot3rdParty.SNConfig}
      iot_servicenow_category_map:
        simple: ${PanwIot3rdParty.SNCategoryMapping}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all available devices from the IoT cloud and sends it to the
        ServiceNow.
      id: a2f8a9f6-4d62-40a8-807a-c9e94059fe1d
      iscommand: false
      name: Send all PANW IoT devices to ServiceNow
      script: SendAllPANWIoTDevicesToServiceNow
      type: regular
      version: -1
    taskid: a2f8a9f6-4d62-40a8-807a-c9e94059fe1d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1245
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 22f53827-3bd0-422f-85ad-4ed4f25602b4
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 22f53827-3bd0-422f-85ad-4ed4f25602b4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1770
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: Servicenow integration is not enabled
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: cd5baced-8625-4b42-8069-1e1c5d525966
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: cd5baced-8625-4b42-8069-1e1c5d525966
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 05457556-9a00-49a1-86ed-ba50d4780f10
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 05457556-9a00-49a1-86ed-ba50d4780f10
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 79559bdd-0449-49c8-84e1-21f867821675
      iscommand: false
      name: Was there an error when sending devices to servicenow?
      script: isError
      type: condition
      version: -1
    taskid: 79559bdd-0449-49c8-84e1-21f867821675
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1420
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to do a bulk device sync to ServiceNow. Please see
          the detailed error message from the playbook'
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 0dbb4700-0e1a-4dab-89d4-6ed78fd07880
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 0dbb4700-0e1a-4dab-89d4-6ed78fd07880
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1595
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 68648b3e-35d0-4549-8ce3-a244ee589420
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 68648b3e-35d0-4549-8ce3-a244ee589420
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1770
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: ${SN-IoT.bulkResult}
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 266fc5d0-79dd-4829-8271-9d43e507a918
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 266fc5d0-79dd-4829-8271-9d43e507a918
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1595
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all customized table and column names in the customers' ServiceNow.
      id: b276e75b-45b4-4b43-8b92-24134df5e31d
      iscommand: false
      name: Get ServiceNow Customized Configuration
      script: GetServiceNowCustomizedConfiguration
      type: regular
      version: -1
    taskid: b276e75b-45b4-4b43-8b92-24134df5e31d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 895
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get PANW IoT and ServiceNow category mapping
      id: bab2d3ce-b112-4b00-8337-a67e14cc3512
      iscommand: false
      name: Get PANW IoT ServiceNow Category Mapping
      script: GetPANWIoTServiceNowCategoryMapping
      type: regular
      version: -1
    taskid: bab2d3ce-b112-4b00-8337-a67e14cc3512
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1070
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "no":
      - "13"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8fa7a691-60c8-48ec-8fe7-753592f3dde7
      iscommand: false
      name: is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 8fa7a691-60c8-48ec-8fe7-753592f3dde7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: servicenow
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 687aad4e-675a-46d7-8446-6a58f355257e
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 687aad4e-675a-46d7-8446-6a58f355257e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 2af260bc-b38c-4a49-8c5d-7384b480adae
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 2af260bc-b38c-4a49-8c5d-7384b480adae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 534ff8ca-a02f-485a-89e2-29431ba36730
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 534ff8ca-a02f-485a-89e2-29431ba36730
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get ServiceNow Table Mapping Method
      id: 518b1189-546d-441e-8be1-5f01e30b586b
      iscommand: true
      name: Get ServiceNow Mapping Method
      script: '|||get-mapping-method'
      type: regular
      version: -1
    taskid: 518b1189-546d-441e-8be1-5f01e30b586b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "18"
    note: false
    quietmode: 0
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${SN.MappingMethod}
      right:
        simple: Use ServiceNow Classes
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 99730a84-a47a-4e7c-8fad-d7525d13f183
      iscommand: false
      name: Is ServiceNow OT Mapping?
      script: AreValuesEqual
      type: condition
      version: -1
    taskid: 99730a84-a47a-4e7c-8fad-d7525d13f183
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      iot_servicenow_category_map:
        simple: ${incident.panwservicenowcategorymap}
      servicenow_instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all available devices from the IoT cloud and sends it to the
        ServiceNow OT Classes
      id: 7b8ec5a7-e192-4b15-8f00-533b3e4cb011
      iscommand: false
      name: SendAllPANWIoTDevicesToServiceNowOTClasses
      script: 9103572f-1d45-4ff6-8f2c-9ecc32bb2fd1
      type: regular
      version: -1
    taskid: 7b8ec5a7-e192-4b15-8f00-533b3e4cb011
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1860,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1815,
        "width": 2190,
        "x": 50,
        "y": 50
      }
    }
  }
