contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook check for finished PANW IoT initiated scans, generates
  reports.
id: 32228f80-b194-4e16-87bd-8693927c2fab
inputs: []
name: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 39ba7f39-a1da-44c0-863f-38ea540f24ea
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b029d5fc-1e7e-469a-89b5-e805127beced
      iscommand: false
      name: ""
      version: -1
    taskid: b029d5fc-1e7e-469a-89b5-e805127beced
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "26"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Rapid7 Nexpose
      using:
        simple: PANW IoT 3rd Party Rapid7 Nexpose Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 194d53b9-58b2-4d80-8e49-94c71224fb55
      iscommand: false
      name: Is Rapid7 Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 194d53b9-58b2-4d80-8e49-94c71224fb55
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: rapid7
      message:
        simple: Rapid7 integration is not enabled
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 4103fa30-7c91-4b47-837a-cb6218c2333d
      iscommand: true
      name: Report disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 4103fa30-7c91-4b47-837a-cb6218c2333d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 98eeac8c-b8ef-4784-8da0-03585ca9216b
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 98eeac8c-b8ef-4784-8da0-03585ca9216b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 1070
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      rapid7_instance:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ebbbb2d6-1078-4a0a-8b47-69c3b7ffd092
      iscommand: false
      name: Launch Rapid7 reports for finished scans
      script: LaunchReportsforFinishedPANWIoTRapid7VulnerabilityScans
      type: regular
      version: -1
    taskid: ebbbb2d6-1078-4a0a-8b47-69c3b7ffd092
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 545
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "30"
      "yes":
      - "20"
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
      path:
        simple: Nexpose.LaunchReportfailStatus
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks for errors in a given task. If found, write it to the path
        provided as an argument.
      id: df0d5645-5093-4a5a-8728-3fc464f468e9
      iscommand: false
      name: Did the Report Launch Fail?
      script: ba739f62-3f46-417e-809b-3c73715e062d
      type: condition
      version: -1
    taskid: df0d5645-5093-4a5a-8728-3fc464f468e9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 720
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobid}
      message:
        simple: ${Nexpose.LaunchReportfailStatus}
      scan_type:
        simple: rapid7
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Upload reports (PDF + XML) for specified scan to IoT Cloud
      id: 7ee8da65-3132-4887-8fef-c548bb2a1c3e
      iscommand: true
      name: Report Launch Error as Event
      script: '|||panw-iot-3rd-party-upload-vulnerability-scan-report'
      type: regular
      version: -1
    taskid: 7ee8da65-3132-4887-8fef-c548bb2a1c3e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1022.5,
          "y": 895
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: rapid7
      message:
        simple: ${Nexpose.LaunchReportfailStatus}
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: e64e588c-eab0-49e7-8895-6299aeb1b53b
      iscommand: true
      name: Report Launch Errors to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e64e588c-eab0-49e7-8895-6299aeb1b53b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1452.5,
          "y": 895
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: c47f8457-9057-4590-82aa-efcdc4f892f8
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: c47f8457-9057-4590-82aa-efcdc4f892f8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1070
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "27"
      "no":
      - "28"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Rapid7 Nexpose
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8aec78fc-c3b7-4bfa-8042-e0b051eff1d4
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 8aec78fc-c3b7-4bfa-8042-e0b051eff1d4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 370
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: rapid7
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: bf044a3f-58de-4460-8ade-5acac7234d32
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: bf044a3f-58de-4460-8ade-5acac7234d32
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "28":
    continueonerror: true
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: rapid7
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: f624c548-b040-46c1-878a-706662b83c37
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: f624c548-b040-46c1-878a-706662b83c37
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 545
        }
      }
  "29":
    continueonerror: true
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 91a3c0f1-c89a-4c6b-8a8c-0b88e169fc5c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 91a3c0f1-c89a-4c6b-8a8c-0b88e169fc5c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 720
        }
      }
  "30":
    continueonerror: true
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: rapid7
      message:
        simple: Report Launch success
      playbook_name:
        simple: Rapid7 Nexpose Report Generation - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: dfede9de-0bb5-4639-8773-61a82dfe579f
      iscommand: true
      name: Report Launch Success to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: dfede9de-0bb5-4639-8773-61a82dfe579f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1782.5,
        "x": 50,
        "y": 50
      }
    }
  }
