contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to be run every 15 minutes via a job. Each run will get incremental
  updates for devices, and will update or create new endpoints in Aruba ClearPass
  with PANW IOT discovered attributes (ClearPass custom attributes).
id: d9127f9b-79ad-4be1-8f6d-8947eac4405d
inputs: []
name: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: Incremental Export to Cisco ISE - PANW IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 492c56e0-fe1a-43eb-8cfe-3130b4c8a7bb
      iscommand: false
      name: ""
      version: -1
    taskid: 492c56e0-fe1a-43eb-8cfe-3130b4c8a7bb
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "20"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba ClearPass
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 07beb4aa-fe5a-4eda-8fd1-1568be6c10ba
      iscommand: false
      name: Is Aruba ClearPass enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 07beb4aa-fe5a-4eda-8fd1-1568be6c10ba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: clearpass
      message:
        simple: Aruba ClearPass instance is not configured
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 2959ceb3-23b3-4e1e-8c12-bc5342d1ecd0
      iscommand: true
      name: Send disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 2959ceb3-23b3-4e1e-8c12-bc5342d1ecd0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      active_aruba_cp_instance:
        simple: ${incident.integrationinstancename}
      custom_attributes:
        simple: ${incident.panwiotdevicecustomattributes}
      device_maps:
        simple: ${PanwIot3rdParty.ArubaClearPassAttributes}
      increment_time:
        simple: ${incident.playbookpollinterval}
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
      sites:
        simple: ${incident.sitenames}
      tags:
        simple: ${incident.panwiotinscopetagenforcement}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 395f5f38-f4a0-40c4-81ad-dbfe3e712798
      iscommand: false
      name: Send devices to Aruba ClearPass
      script: SendPANWIoTDevicesToArubaClearPass
      type: regular
      version: -1
    taskid: 395f5f38-f4a0-40c4-81ad-dbfe3e712798
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 545
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "17"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 5dcb88b4-20de-4dab-867d-16463f7fa7ba
      iscommand: false
      name: Was there an error while exporting devices?
      script: isError
      type: condition
      version: -1
    taskid: 5dcb88b4-20de-4dab-867d-16463f7fa7ba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 720
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: clearpass
      message:
        simple: 'Failed to export PANW IoT devices to  Aruba ClearPass '
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: b5fee47c-050c-40db-8d99-bd86bac187c5
      iscommand: true
      name: Send error status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: b5fee47c-050c-40db-8d99-bd86bac187c5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 895
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: clearpass
      message:
        simple: ${PaloAltoIoTIntegrationBase.Status}
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 4af0ec5b-4894-4f20-84ef-505d2b87a81b
      iscommand: true
      name: Send success status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 4af0ec5b-4894-4f20-84ef-505d2b87a81b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 895
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: a7578057-b1da-49c2-8570-b8f468eb1405
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: a7578057-b1da-49c2-8570-b8f468eb1405
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 1070
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "21"
      "no":
      - "22"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Aruba ClearPass
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1c41f349-d60f-4db5-8618-71ff900fe441
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 1c41f349-d60f-4db5-8618-71ff900fe441
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 705,
          "y": 370
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: clearpass
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: feb23423-648a-43c0-8ba1-092ca0969b6c
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: feb23423-648a-43c0-8ba1-092ca0969b6c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: clearpass
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Incremental Export to Aruba ClearPass- PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 0a53c001-aa08-4489-88cb-fbb0ba6b5a90
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 0a53c001-aa08-4489-88cb-fbb0ba6b5a90
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 545
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: cbe36883-06bb-47e5-8827-01b30bdff24f
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: cbe36883-06bb-47e5-8827-01b30bdff24f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1680,
        "x": 50,
        "y": 50
      }
    }
  }
