contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 840ba626-dac4-47f5-8cc6-bc892aea77f9
inputs: []
name: extract-dnac-clients
outputs: []
sourceplaybookid: 148aadac-6b17-442a-8d6b-26e9befd59e3
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 16b4e465-047c-4040-8295-434b056ff260
      iscommand: false
      name: ""
      version: -1
    taskid: 16b4e465-047c-4040-8295-434b056ff260
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      active_range:
        simple: ${incident.playbookpollinterval}
      dnac_instance_name:
        simple: ${incident.integrationinstancename}
      execution-timeout:
        simple: "172800"
      siteids:
        simple: ${incident.sitenames}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 653fcaaf-f38c-4150-846a-fd5d6f447169
      iscommand: false
      name: Send All PANW Device Attributes From DNAC to PANW
      script: ExportDeviceAttributesFromDnacToPANWIoTCloud
      type: regular
      version: -1
    taskid: 653fcaaf-f38c-4150-846a-fd5d6f447169
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "25"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - cisco-dnac-IoT
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 60a3c74e-175f-41bf-8dfd-428808e270d1
      iscommand: false
      name: Is DNA Center enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 60a3c74e-175f-41bf-8dfd-428808e270d1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_dnac
      message:
        simple: Cisco DNA Center instance is not enabled
      playbook_name:
        simple: extract-dnac-clients
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 3765da66-009e-4d78-8edb-34f371adcf98
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 3765da66-009e-4d78-8edb-34f371adcf98
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 31b2a1ef-348f-499c-8581-0773e610f5db
      iscommand: true
      name: close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 31b2a1ef-348f-499c-8581-0773e610f5db
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "26"
      "no":
      - "27"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - cisco-dnac-IoT
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 81db7321-fbe8-4539-8360-34feb5e41067
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 81db7321-fbe8-4539-8360-34feb5e41067
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_dnac
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: extract-dnac-clients
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 1012add0-8c2f-43d0-865e-f6fcad78067e
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 1012add0-8c2f-43d0-865e-f6fcad78067e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_dnac
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: extract-dnac-clients
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 69ebf68a-a584-4b59-8f0e-bbb7c2febc73
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 69ebf68a-a584-4b59-8f0e-bbb7c2febc73
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "28":
    continueonerror: true
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 88978a5e-bebc-4046-8e12-5d5c619be318
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 88978a5e-bebc-4046-8e12-5d5c619be318
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_11_no": 0.46
    },
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
