contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e1b1feff-b177-4ba8-8693-39d64724651d
inputs: []
name: dev-prod-test
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b265b54d-ed6d-4967-861e-43a627a90d90
      iscommand: false
      name: ""
      version: -1
    taskid: b265b54d-ed6d-4967-861e-43a627a90d90
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 25243128-815c-4341-8f24-4fddf5c3feab
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 25243128-815c-4341-8f24-4fddf5c3feab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 310
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 355,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
