contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 227ab96f-0b0e-411b-8db6-1d3344925246
inputs: []
name: Update Integration Status - PANW IoT 3rd Party Integrations
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 520f319b-15a5-41fa-8cea-a34bfefa8c3b
      iscommand: false
      name: ""
      version: -1
    taskid: 520f319b-15a5-41fa-8cea-a34bfefa8c3b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 630,
          "y": -10
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 378818db-30f6-4326-87f2-b7ad2d4525ce
      iscommand: false
      name: UpdatePANWIoTIntegrationStatus
      script: UpdatePANWIoTIntegrationStatus
      type: regular
      version: -1
    taskid: 378818db-30f6-4326-87f2-b7ad2d4525ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 630,
          "y": 170
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: e633ce73-ba8e-4af4-8e76-d3b5ec7d1d2e
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e633ce73-ba8e-4af4-8e76-d3b5ec7d1d2e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 630,
          "y": 350
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 630,
        "y": -10
      }
    }
  }
