contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 227ab96f-0b0e-411b-8db6-1d3344925246
inputs: []
name: Update Integration Status - PANW IoT 3rd Party Integrations
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 09f4fff2-15d0-439c-8e32-0949eb11da76
      iscommand: false
      name: ""
      version: -1
    taskid: 09f4fff2-15d0-439c-8e32-0949eb11da76
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 630,
          "y": -10
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3bd0b127-0fa8-498d-8957-ff286b7ad1fe
      iscommand: false
      name: UpdatePANWIoTIntegrationStatus
      script: UpdatePANWIoTIntegrationStatus
      type: regular
      version: -1
    taskid: 3bd0b127-0fa8-498d-8957-ff286b7ad1fe
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 630,
          "y": 170
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 895bcdcd-2604-4a8a-83cf-6c0b11d139cc
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 895bcdcd-2604-4a8a-83cf-6c0b11d139cc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 630,
          "y": 350
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 630,
        "y": -10
      }
    }
  }
