contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 52b8c005-fc87-4995-8c81-2efceebe8129
inputs: []
name: Cisco Prime Clients
outputs: []
sourceplaybookid: af2c1125-ca1e-4f4d-8a8b-aea23b5f044a
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 311ec46c-d5a0-49df-8592-dbf9a0041134
      iscommand: false
      name: ""
      version: -1
    taskid: 311ec46c-d5a0-49df-8592-dbf9a0041134
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 910,
          "y": -430
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "20"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Cisco Prime
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 5605fbd2-41de-427d-82f4-c31149f9d7fd
      iscommand: false
      name: Is Cisco Prime Available?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 5605fbd2-41de-427d-82f4-c31149f9d7fd
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": -295
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_prime
      message:
        simple: Cisco Prime Instance is not available
      playbook_name:
        simple: Cisco Prime Get Clients
      playbookName:
        simple: Cisco Prime Clients
      status:
        simple: disabled
      type:
        simple: device
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: de619ba1-1a83-4ea1-8035-99e743119166
      iscommand: true
      name: Send Disable Status to IOT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: de619ba1-1a83-4ea1-8035-99e743119166
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 370
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      active_range:
        simple: ${incident.playbookpollinterval}
      execution-timeout:
        simple: "172800"
      pageLength:
        simple: "1000"
      prime_instance_name:
        simple: ${incident.integrationinstancename}
      siteids:
        simple: ${incident.sitenames}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      id: 0008a121-e2f8-47d9-889d-3a7c6cf36667
      iscommand: false
      name: Export Device Attributes from Cisco Prime to PANW
      script: ExportDeviceAttributesFromPrimeToPANWIoTCloud
      type: regular
      version: -1
    taskid: 0008a121-e2f8-47d9-889d-3a7c6cf36667
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 8382ad3e-d16f-4c9d-8f80-edc078964bdc
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8382ad3e-d16f-4c9d-8f80-edc078964bdc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 545
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "21"
      "no":
      - "22"
      "yes":
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - Cisco Prime
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9f2926bd-cf89-4dda-845f-b0f3af6eff3f
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 9f2926bd-cf89-4dda-845f-b0f3af6eff3f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 30
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_prime
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Cisco Prime Get Clients
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 48589b27-7f18-436f-8957-27608a063f89
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 48589b27-7f18-436f-8957-27608a063f89
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -200,
          "y": 255
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_prime
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Cisco Prime Get Clients
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 3811fb4a-b85a-46b0-8b3b-266657e721a2
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 3811fb4a-b85a-46b0-8b3b-266657e721a2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 250,
          "y": 255
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: f7fc27e6-dbb7-4c3e-8578-74232a476a0d
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f7fc27e6-dbb7-4c3e-8578-74232a476a0d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 580
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1105,
        "width": 1705,
        "x": -200,
        "y": -430
      }
    }
  }
