contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Import devices in Nuvolo to PANW IoT cloud.
id: d94178ae-3e99-4efe-86ea-f73a8528b035
inputs: []
name: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 985135c8-3cc9-43b1-8783-926b487a076d
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3fe6ca99-7156-4197-8097-7d585623b119
      iscommand: false
      name: ""
      version: -1
    taskid: 3fe6ca99-7156-4197-8097-7d585623b119
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "11"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Nuvolo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: b4133bb9-348a-4a47-8b21-a3f387f65673
      iscommand: false
      name: Is Nuvolo enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: b4133bb9-348a-4a47-8b21-a3f387f65673
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: Nuvolo integration is not enabled
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 509ab19a-0c32-47b7-8661-0300c234eefe
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 509ab19a-0c32-47b7-8661-0300c234eefe
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 370
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 6cd3749e-7fd5-4d64-8df2-6ad4516dfd06
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 6cd3749e-7fd5-4d64-8df2-6ad4516dfd06
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 6b6138c1-3765-4a59-8be1-0d7c8069b5d1
      iscommand: false
      name: Was there an error when importing devices from Nuvolo?
      script: isError
      type: condition
      version: -1
    taskid: 6b6138c1-3765-4a59-8be1-0d7c8069b5d1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: 'Error: Failed to do a bulk device import from Nuvolo'
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: f7cfb219-b196-45aa-80bf-ea411ef18f31
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: f7cfb219-b196-45aa-80bf-ea411ef18f31
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 4567518e-feaf-4e78-8f54-f24ddba6f3c8
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4567518e-feaf-4e78-8f54-f24ddba6f3c8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: c9cdcd72-9909-40ba-8682-8cdbe9d52967
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: c9cdcd72-9909-40ba-8682-8cdbe9d52967
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: Successfully Importing devices from Nuvolo.
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 4c318a9d-8137-4846-8996-02a2b1e2e5bf
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 4c318a9d-8137-4846-8996-02a2b1e2e5bf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "no":
      - "12"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Nuvolo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e03f9fd4-ace7-47d2-83d9-a91d34059a2b
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: e03f9fd4-ace7-47d2-83d9-a91d34059a2b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: d32f6db8-7cd6-4f94-84e9-3e7735352139
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: d32f6db8-7cd6-4f94-84e9-3e7735352139
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 391352ef-af89-4b9d-8f74-bbd986abcfa7
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 391352ef-af89-4b9d-8f74-bbd986abcfa7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 720
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 4a4605b9-15f8-4628-8624-2935a17477b3
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 4a4605b9-15f8-4628-8624-2935a17477b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Pulling devices information from Nuvolo and send to PANW IoT Cloud
        Side.
      id: 385c1096-8e55-4be6-8063-f59a27ebde94
      iscommand: false
      name: Send Nuvolo Data To PANW IoT Cloud
      script: 74e93f5e-820a-463d-8f5d-741f45aa4cc4
      type: regular
      version: -1
    taskid: 385c1096-8e55-4be6-8063-f59a27ebde94
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "6_10_no": 0.66
    },
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
