contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.15
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook retrieves a list of Qualys scanner appliances and scan
  profile options and report them to PANW IoT Cloud.
id: 9f880b08-3b12-4a80-86ea-29c7511a40b2
inputs: []
name: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 9f880b08-3b12-4a80-86ea-29c7511a40b2
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: da192086-4469-4578-8e49-acd1ac4138f7
      iscommand: false
      name: ""
      version: -1
    taskid: da192086-4469-4578-8e49-acd1ac4138f7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 690,
          "y": -370
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "13"
      "yes":
      - "24"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Qualys
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: d0271c0e-e9b4-4ff9-8e4e-97901d046a27
      iscommand: false
      name: Is Qualys Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: d0271c0e-e9b4-4ff9-8e4e-97901d046a27
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 690,
          "y": -225
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 781b3e3b-6366-4343-8236-33006e2790d7
      iscommand: false
      name: Was There an Error Getting Scanner and Profile Lists?
      script: isError
      type: condition
      version: -1
    taskid: 781b3e3b-6366-4343-8236-33006e2790d7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 485
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: ba3490c6-8694-4df2-855b-77fe9325a560
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ba3490c6-8694-4df2-855b-77fe9325a560
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 845
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: Successfully sent scanner and appliance list to PANW IoT Cloud
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 2bb8b55d-cf00-4fd5-8fc1-b2a78932fd2f
      iscommand: true
      name: Report Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 2bb8b55d-cf00-4fd5-8fc1-b2a78932fd2f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 670
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: qualys
      message:
        simple: Qualys Integration is not enabled
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 1318ed66-cc64-4d81-876a-c827aef4111d
      iscommand: true
      name: Report Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 1318ed66-cc64-4d81-876a-c827aef4111d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 230,
          "y": -50
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: Failed to send scanner and appliance list to PANW IoT Cloud
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 54fbb0bf-ff84-4b72-8a72-74bac103edbf
      iscommand: true
      name: Report Error Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 54fbb0bf-ff84-4b72-8a72-74bac103edbf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 670
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      qualys_instance_name:
        simple: ${incident.integrationinstancename}
      scanner_sync:
        simple: ${incident.automaticallysynchronizescannerswithiotsecuritytoavoidfalsesecurityalerts}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Get list of Qualys Scanners and Profiles and write to context
      id: dc400466-efc3-4bb0-8e4e-bcf6daba1e6f
      iscommand: false
      name: Get A list of Qualys Scanners and Scan Profile Options
      script: GetQualysScannersAndProfiles
      type: regular
      version: -1
    taskid: dc400466-efc3-4bb0-8e4e-bcf6daba1e6f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 310
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "19"
      "no":
      - "20"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Qualys
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8132af99-e94a-4317-811c-4d70642210bf
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 8132af99-e94a-4317-811c-4d70642210bf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 880,
          "y": 130
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: da8a7aa7-5a90-4f3c-8040-7409942b3542
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: da8a7aa7-5a90-4f3c-8040-7409942b3542
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 310
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: qualys
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: d1ba87f3-026f-41f3-85f3-82d622f10907
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: d1ba87f3-026f-41f3-85f3-82d622f10907
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1250,
          "y": 310
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 8bd5e60d-a8a9-46e7-81e8-ec99b4bff39b
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8bd5e60d-a8a9-46e7-81e8-ec99b4bff39b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1060,
          "y": 500
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "27"
      "yes":
      - "18"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Qualys
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: ee6b5614-6d68-44cf-8eff-bbf5eecfdb7f
      iscommand: false
      name: Is Qualys  Integration Instance Enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: ee6b5614-6d68-44cf-8eff-bbf5eecfdb7f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 880,
          "y": -50
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: qualys
      message:
        simple: Qualys Integration is not enabled
      playbook_name:
        simple: Get Qualys Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 9469e956-1694-4cf9-8a1b-2e9905652685
      iscommand: true
      name: Report Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 9469e956-1694-4cf9-8a1b-2e9905652685
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1670,
          "y": 150
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1310,
        "width": 1820,
        "x": 230,
        "y": -370
      }
    }
  }
