contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 2.0.11
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Alert to SIEM.
id: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
inputs: []
name: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "PANW IoT 3rd Party
    SIEM Integration - Alert/Vulnerability"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bacb64da-7852-4042-8c2e-5c72a71419d4
      iscommand: false
      name: ""
      version: -1
    taskid: bacb64da-7852-4042-8c2e-5c72a71419d4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 440,
          "y": -250
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 4dfe3d9c-f5c2-424b-828d-fef7a25daa0a
      iscommand: false
      name: Is Syslog Sender(SIEM) Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 4dfe3d9c-f5c2-424b-828d-fef7a25daa0a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 110
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: Syslog Sender (SIEM) instance is not enabled
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 0a8442ff-5a74-428d-87af-fc4552ee9f99
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 0a8442ff-5a74-428d-87af-fc4552ee9f99
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 200,
          "y": 410
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${incident.zb_ticketid}
      asset_type:
        simple: ${incident.asset_type}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: For a given a asset ID (alert-id, vulnerability-id or mac-address)
        returns the asset details.
      id: ef0897da-3016-496e-8d30-de574a12351f
      iscommand: true
      name: Get PANW IoT Asset details
      script: '|||panw-iot-3rd-party-get-single-asset'
      type: regular
      version: -1
    taskid: ef0897da-3016-496e-8d30-de574a12351f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 660,
          "y": 400
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "5"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 5462e2c0-9598-4714-86d6-ba3afdd19519
      iscommand: false
      name: Was there an error getting asset details?
      script: isError
      type: condition
      version: -1
    taskid: 5462e2c0-9598-4714-86d6-ba3afdd19519
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 660,
          "y": 570
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 7c31d4f3-0b74-4854-8050-f67e2f5cc881
      iscommand: false
      name: Does the asset exist?
      script: Exists
      type: condition
      version: -1
    taskid: 7c31d4f3-0b74-4854-8050-f67e2f5cc881
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 880,
          "y": 750
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: Failed to get Alert (${incident.zb_ticketid}) from IoT cloud.
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: ba6b3d94-8e9e-4c0b-8c45-ced1b52c3bd3
      iscommand: true
      name: Send error status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: ba6b3d94-8e9e-4c0b-8c45-ced1b52c3bd3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 410,
          "y": 760
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_list:
        simple: ${PanwIot3rdParty.SingleAsset}
      asset_type:
        simple: ${incident.asset_type}
      output_format:
        simple: SIEM
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: For a given asset (alert, device, vuln) converts it to 3rd party
        format.
      id: bcad26b4-2873-4c01-8d4e-50ae6fa84aeb
      iscommand: true
      name: Convert asset to CEF format
      script: '|||panw-iot-3rd-party-convert-assets-to-external-format'
      type: regular
      version: -1
    taskid: bcad26b4-2873-4c01-8d4e-50ae6fa84aeb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1120
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: No Alert found with given ID  (${incident.zb_ticketid}).
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 11af55e7-a2bd-40f7-89fd-1212ddab3064
      iscommand: true
      name: send status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 11af55e7-a2bd-40f7-89fd-1212ddab3064
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 640,
          "y": 930
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.AlertCEFSyslogs}${PanwIot3rdParty.VulnerabilityCEFSyslogs}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 1b423387-b66f-427f-82ed-b0714290ea2c
      iscommand: false
      name: Is there any syslog (CEF) available?
      script: Exists
      type: condition
      version: -1
    taskid: 1b423387-b66f-427f-82ed-b0714290ea2c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1120,
          "y": 1280
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: ${PanwIot3rdParty.AlertCEFSyslogs}${PanwIot3rdParty.VulnerabilityCEFSyslogs}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a message to Syslog.
      id: 8a5a288c-e054-4b11-81d0-293ad5da85e5
      iscommand: true
      name: 'Send asset syslog '
      script: '|||syslog-send'
      type: regular
      version: -1
    taskid: 8a5a288c-e054-4b11-81d0-293ad5da85e5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1310,
          "y": 1460
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: Alert ID  (${incident.zb_ticketid}) not valid for CEF conversion.
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 411f93ae-cc5a-4e8b-8491-276e2356627a
      iscommand: true
      name: Send error status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 411f93ae-cc5a-4e8b-8491-276e2356627a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1460
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: siem
      message:
        simple: Successfully sent Alert (${incident.zb_ticketid}) to SIEM
      playbook_name:
        simple: Export Single Asset to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 56902206-418d-4afc-88e1-71716346934a
      iscommand: true
      name: Send success status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 56902206-418d-4afc-88e1-71716346934a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1310,
          "y": 1600
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 66c504e5-d059-4e97-8318-0bf33c013e92
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 66c504e5-d059-4e97-8318-0bf33c013e92
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1750
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "13"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      asset:
        simple: ${PanwIot3rdParty.SingleAsset}
      asset_type:
        simple: ${incident.asset_type}
      integration_name:
        simple: Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a920bb9e-b1d3-453f-86de-dc046a534280
      iscommand: false
      name: Does severity level match configuration filter?
      script: 2ef6f81e-1456-41a9-8ce5-3b6ebf04ea9d
      type: condition
      version: -1
    taskid: a920bb9e-b1d3-453f-86de-dc046a534280
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1120,
          "y": 920
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2095,
        "width": 1490,
        "x": 200,
        "y": -250
      }
    }
  }
