contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Export single alert or vulnerability as work order in AIMS
dirtyInputs: true
id: 91a6bd11-8c73-4b25-83b4-e8fad47f03fb
inputs: []
name: Export single alert or vulnerability as work order in AIMS - PANW IoT 3rd Party
  Integration
outputs: []
sourceplaybookid: Export single alert or vulnerability as work order in AIMS - PANW
  IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4fdd2777-2431-4f09-8808-4ae753b65572
      iscommand: false
      name: ""
      version: -1
    taskid: 4fdd2777-2431-4f09-8808-4ae753b65572
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "9"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - AIMS
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 7e720c78-f821-4fbc-8aed-bb2aa4cc94d4
      iscommand: false
      name: Is AIMS Integration enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 7e720c78-f821-4fbc-8aed-bb2aa4cc94d4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: aims
      message:
        simple: AIMS instance is not enabled
      playbook_name:
        simple: Export single alert or vulnerability as work order in AIMS - PANW
          IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 29d526dd-6928-4d2f-8fd9-6affdc559884
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 29d526dd-6928-4d2f-8fd9-6affdc559884
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 0ac14a56-e1fb-4ae0-8a54-26bccb8e32e8
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 0ac14a56-e1fb-4ae0-8a54-26bccb8e32e8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 9b8ad0f6-52df-4d26-857f-12c4a49f78c8
      iscommand: false
      name: Was there an error creating work order in AIMS?
      script: isError
      type: condition
      version: -1
    taskid: 9b8ad0f6-52df-4d26-857f-12c4a49f78c8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: aims
      message:
        simple: Successfully created work order in AIMS
      playbook_name:
        simple: Export single alert or vulnerability as work order in AIMS - PANW
          IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 9f0c8319-668f-4c63-855f-43d8a696d81e
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 9f0c8319-668f-4c63-855f-43d8a696d81e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: aims
      message:
        simple: Error while creating work order in AIMS
      playbook_name:
        simple: Export single alert or vulnerability as work order in AIMS - PANW
          IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 8350510a-cc75-450d-834e-d761758b2895
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 8350510a-cc75-450d-834e-d761758b2895
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      AssignedTo:
        simple: ${incident.assignedTo}
      Contact:
        simple: ${incident.contact}
      Facility:
        simple: ${incident.facility}
      Notes:
        simple: ${incident.notes}
      Priority:
        simple: ${incident.priority}
      Problem:
        simple: ${incident.problem}
      Reason:
        simple: ${incident.reason}
      Requester:
        simple: ${incident.requester}
      Requster:
        simple: ${incident.requester}
      Tag:
        simple: ${incident.tag}
      UserEmail:
        simple: ${incident.user_email}
      ZbTicketId:
        simple: ${incident.zb_ticketid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Create work order in AIMS
      id: d23ea78b-ee00-4993-8bea-d590cca0ddb5
      iscommand: true
      name: Create work order in AIMS
      script: '|||aims-create-work-order'
      type: regular
      version: -1
    taskid: d23ea78b-ee00-4993-8bea-d590cca0ddb5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      IntegrationName:
        simple: aims
      MetaData:
        simple: ${CommandOutput.WorkOrderResponse}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send metadata to PANW IOT cloud
      id: 08f681ad-c323-444f-8a71-2ee652dc476d
      iscommand: true
      name: Send response metadata to PANW IoT
      script: '|||panw-iot-3rd-party-report-metadata'
      type: regular
      version: -1
    taskid: 08f681ad-c323-444f-8a71-2ee652dc476d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 720
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: fd158847-3e69-415a-8f38-01809679eda4
      iscommand: false
      name: Was there an error reporting details to PANW IoT?
      script: isError
      type: condition
      version: -1
    taskid: fd158847-3e69-415a-8f38-01809679eda4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 490,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_8_yes": 0.38,
      "1_2_no": 0.52,
      "1_9_yes": 0.54,
      "6_10_no": 0.5,
      "6_8_yes": 0.36
    },
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
