contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.17
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Fetch data from SolarWinds UDT and send it to PANW IoT Platform
dirtyInputs: true
id: f0f6814a-7602-4d57-8499-2cb92daa72a4
inputs: []
name: Import Solarwinds UDT assets to PANW IoT cloud
outputs: []
sourceplaybookid: Import MS Defender devices to PANW IoT cloud
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fcf5c504-c668-4b9a-88bb-7186df993938
      iscommand: false
      name: ""
      version: -1
    taskid: fcf5c504-c668-4b9a-88bb-7186df993938
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "no":
      - "2"
      "yes":
      - "19"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - SolarWinds UDT
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 47587de4-5685-4ce7-8a24-8edaaaf002a2
      iscommand: false
      name: Is SolarWinds UDT integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 47587de4-5685-4ce7-8a24-8edaaaf002a2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 720,
          "y": 370
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: solarwinds_udt
      message:
        simple: SolarWinds UDT integration is not enabled
      playbook_name:
        simple: Import Solarwinds UDT assets to PANW IoT cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: ef9aec1f-3315-4696-8009-87120155789f
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: ef9aec1f-3315-4696-8009-87120155789f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 617.5,
          "y": 615
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: dfb0dd31-4c1b-4dfe-8955-148c202aaad5
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: dfb0dd31-4c1b-4dfe-8955-148c202aaad5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 1010
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 14e926b4-020b-48cf-8157-9c99f6d05785
      iscommand: false
      name: Send SolarWinds UDT Assets to PANW IoT
      script: d5a8fb65-8bef-43be-8b9c-2cded0949211
      type: regular
      version: -1
    taskid: 14e926b4-020b-48cf-8157-9c99f6d05785
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 800
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: solarwinds_udt
      message:
        simple: Invalid integration instance name provided
      playbook_name:
        simple: Import Solarwinds UDT assets to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 1061f6ac-8074-4159-8fe8-00ecf28a90ee
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 1061f6ac-8074-4159-8fe8-00ecf28a90ee
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 207.5,
          "y": 615
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "27"
      "no":
      - "21"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - SolarWinds UDT
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 22e3124b-0f76-4b26-8c5c-fe1545f079e8
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 22e3124b-0f76-4b26-8c5c-fe1545f079e8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1120,
          "y": 550
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: solarwinds_udt
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import Solarwinds UDT assets to PANW IoT cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: e0226496-6c30-4fc6-8572-eaa02b341c59
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e0226496-6c30-4fc6-8572-eaa02b341c59
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 920,
          "y": 810
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 09ef3d2e-8d19-47ef-8b6f-d27609aa7cf3
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 09ef3d2e-8d19-47ef-8b6f-d27609aa7cf3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 830,
          "y": 1220
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 34a8ca0e-61b5-4065-81a7-4773a875ee77
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 34a8ca0e-61b5-4065-81a7-4773a875ee77
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": 970
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "25"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: dad08604-a266-48b9-848b-16cb7da6fcc3
      iscommand: false
      name: Is Solarwinds UDT Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: dad08604-a266-48b9-848b-16cb7da6fcc3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: solarwinds_udt
      message:
        simple: No SolarWinds Integration instance passed
      playbook_name:
        simple: Import Solarwinds UDT assets to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 78f89606-f6a5-45a5-837b-c5a1b56c1074
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 78f89606-f6a5-45a5-837b-c5a1b56c1074
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -150,
          "y": 420
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: solarwinds_udt
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import Solarwinds UDT assets to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 95c3b442-3ccd-496b-8c43-79dbcd74d965
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 95c3b442-3ccd-496b-8c43-79dbcd74d965
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1790,
          "y": 800
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_18_#default#": 0.85,
      "1_2_no": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 1265,
        "width": 2320,
        "x": -150,
        "y": 50
      }
    }
  }
