contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.9.0
    itemVersion: 1.7.64
    packID: CortexAttackSurfaceManagement
    packName: Cortex Attack Surface Management
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook is used to create ServiceNow tickets directed toward service
  owners to notify them of their internet exposures.
id: Cortex ASM - ServiceNow Notification
inputSections:
- description: Generic group for inputs.
  inputs:
  - OwnerNotificationBody
  - NotificationTicketType
  - RemediationGuidance
  name: General (Inputs group)
inputs:
- description: Body of the notification (email or ticket) sent to the potential service
    owner.
  key: OwnerNotificationBody
  playbookInputQuery: null
  required: true
  value: {}
- description: The ticket type used by ticketing systems. The default is "incident"
    because ticketing systems such as ServiceNow and Cherwell use it as default.
  key: NotificationTicketType
  playbookInputQuery: null
  required: true
  value: {}
- description: Remediation Guidance of the Attack Surface Rule.
  key: RemediationGuidance
  playbookInputQuery: null
  required: true
  value: {}
name: Cortex ASM - ServiceNow Notification
outputSections:
- description: Generic group for outputs.
  name: General (Outputs group)
  outputs: []
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b2dad0cb-d59b-4656-8b00-45e7bf43e237
      iscommand: false
      name: ""
      version: -1
    taskid: b2dad0cb-d59b-4656-8b00-45e7bf43e237
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0dfcbaac-1689-4433-82a2-361344c6503f
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: 0dfcbaac-1689-4433-82a2-361344c6503f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 800
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      contact_type:
        simple: ASM
      correlation_id:
        simple: ${alert.id}
      description:
        complex:
          root: inputs.OwnerNotificationBody
          transformers:
          - args:
              prefix:
                value:
                  simple: ${predescription}
              suffix:
                iscontext: true
                value:
                  simple: inputs.RemediationGuidance
            operator: concat
          - args:
              limit: {}
              replaceWith: {}
              toReplace:
                value:
                  simple: <br>
            operator: replace
          - args:
              limit: {}
              replaceWith: {}
              toReplace:
                value:
                  simple: '["'
            operator: replace
          - args:
              limit: {}
              replaceWith: {}
              toReplace:
                value:
                  simple: '"]'
            operator: replace
          - args:
              limit: {}
              replaceWith:
                value:
                  simple: ','
              toReplace:
                value:
                  simple: '","'
            operator: replace
      extend-context:
        simple: 'ServiceNowDomain=.={"url": val.result.sys_domain.link.split(''api/now'')[0]}'
      short_description:
        complex:
          accessor: name
          root: alert
          transformers:
          - args:
              prefix:
                value:
                  simple: 'Cortex ASM Alert: '
              suffix: {}
            operator: concat
      ticket_type:
        complex:
          root: inputs.NotificationTicketType
    separatecontext: false
    skipunavailable: false
    task:
      brand: ServiceNow v2
      description: Creates new ServiceNow ticket.
      id: dd4851db-4755-4535-8057-c794b7836d2a
      iscommand: true
      name: Create ServiceNow alert
      script: ServiceNow v2|||servicenow-create-ticket
      type: regular
      version: -1
    taskid: dd4851db-4755-4535-8057-c794b7836d2a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmnotification
      keys:
        simple: type,value,url,timestamp
      val1:
        simple: ServiceNow
      val2:
        complex:
          accessor: ID
          root: ServiceNow.Ticket
      val3:
        complex:
          accessor: url
          root: ServiceNowDomain
          transformers:
          - args:
              prefix: {}
              suffix:
                value:
                  simple: nav_to.do?uri=alert.do?sysparm_query=number=
            operator: concat
          - args:
              prefix: {}
              suffix:
                iscontext: true
                value:
                  simple: ServiceNow.Ticket.Number
            operator: concat
      val4:
        complex:
          accessor: CreatedOn
          root: ServiceNow.Ticket
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      id: 89c90893-467e-4394-8e3e-46c4e5afc691
      iscommand: false
      name: Set notification grid field
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: 89c90893-467e-4394-8e3e-46c4e5afc691
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 620
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: predescription
      stringify:
        simple: "true"
      value:
        simple: |+
          Source: ASM

          Alert ID: ${alert.id}

          Cloud: ${alert.asmprovider}

          Severity: ${alert.severity}

          IP address: ${alert.remoteip}

          Hostname: ${alert.hostname}

          Tags: ${alert.tags}

          Attack surface rule: ${alert.asmattacksurfaceruleid.[0]}

          Excluded: ${alert.excluded}

          External ID: ${alert.external_id}

    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 80795fa8-8410-446c-8ce9-0ebe1d09a0b7
      iscommand: false
      name: Set predescription field
      script: Set
      type: regular
      version: -1
    taskid: 80795fa8-8410-446c-8ce9-0ebe1d09a0b7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
