contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Import devices in Nuvolo to PANW IoT cloud.
id: d94178ae-3e99-4efe-86ea-f73a8528b035
inputs: []
name: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 985135c8-3cc9-43b1-8783-926b487a076d
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: aae0f000-9db4-4867-8ff6-1f586dbc7fe4
      iscommand: false
      name: ""
      version: -1
    taskid: aae0f000-9db4-4867-8ff6-1f586dbc7fe4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "11"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Nuvolo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 660b0460-43f9-4e1d-81ea-d97883b001bf
      iscommand: false
      name: Is Nuvolo enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 660b0460-43f9-4e1d-81ea-d97883b001bf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: Nuvolo integration is not enabled
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: ec8b1f9c-3307-451c-882b-8430c2c7eef5
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: ec8b1f9c-3307-451c-882b-8430c2c7eef5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 370
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 56cbe03a-fd37-4536-8644-ae5d3b22d1ca
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 56cbe03a-fd37-4536-8644-ae5d3b22d1ca
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 343e9752-83ae-4fe5-82f4-99ed668ccb34
      iscommand: false
      name: Was there an error when importing devices from Nuvolo?
      script: isError
      type: condition
      version: -1
    taskid: 343e9752-83ae-4fe5-82f4-99ed668ccb34
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: 'Error: Failed to do a bulk device import from Nuvolo'
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: fe01260c-5f07-4e4b-8e2d-af7b91414511
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: fe01260c-5f07-4e4b-8e2d-af7b91414511
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: bbae7816-4e51-401e-8689-5f8f3da858bc
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: bbae7816-4e51-401e-8689-5f8f3da858bc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 1c06a369-b2b8-40a0-8d11-32f125ac34cd
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 1c06a369-b2b8-40a0-8d11-32f125ac34cd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: Successfully Importing devices from Nuvolo.
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 4275fbe5-fc9f-4f17-8efc-d72ac9c8005c
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 4275fbe5-fc9f-4f17-8efc-d72ac9c8005c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "no":
      - "12"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Nuvolo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 52868027-762a-479e-85c4-497bf3484f99
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 52868027-762a-479e-85c4-497bf3484f99
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: b7b5e763-1a1e-44e2-8510-3dd532f15f1e
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: b7b5e763-1a1e-44e2-8510-3dd532f15f1e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: ab8f4b96-32e8-46bb-8e49-110001af647c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ab8f4b96-32e8-46bb-8e49-110001af647c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 720
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: nuvolo
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Bulk Import Devices from Nuvolo to PANW IoT Cloud - PANW IoT 3rd Party
          Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 008d3f69-63d4-4a41-875f-1e3cb618e8f5
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 008d3f69-63d4-4a41-875f-1e3cb618e8f5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Pulling devices information from Nuvolo and send to PANW IoT Cloud
        Side.
      id: b5d0c9b5-44fb-4bf5-8a61-c920c5cd3e74
      iscommand: false
      name: Send Nuvolo Data To PANW IoT Cloud
      script: 74e93f5e-820a-463d-8f5d-741f45aa4cc4
      type: regular
      version: -1
    taskid: b5d0c9b5-44fb-4bf5-8a61-c920c5cd3e74
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "6_10_no": 0.66
    },
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
