contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.16
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d7efa8d1-69a3-41b6-817d-d9883f8ea24f
inputs: []
name: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: d7efa8d1-69a3-41b6-817d-d9883f8ea24f
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6d6b8476-0d01-45af-8937-983ea08763c9
      iscommand: false
      name: ""
      version: -1
    taskid: 6d6b8476-0d01-45af-8937-983ea08763c9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 80
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "16"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Tenable.io
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: ec311302-9fa9-46ef-8a17-7e800cbcdcbb
      iscommand: false
      name: Is Tenable Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: ec311302-9fa9-46ef-8a17-7e800cbcdcbb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Tenable Integration is not enabled.
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 8751fd47-27c7-48b3-8522-cc976223b299
      iscommand: true
      name: Report Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 8751fd47-27c7-48b3-8522-cc976223b299
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -20,
          "y": 1080
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: d148aff4-7d89-4cfd-8fc7-73cde8d4ad88
      iscommand: false
      name: Was There an Error Getting Scanner and Profile Lists?
      script: isError
      type: condition
      version: -1
    taskid: d148aff4-7d89-4cfd-8fc7-73cde8d4ad88
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 200,
          "y": 905
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Failed to fetch scanner and appliance list from Tenable
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: e96a809f-c46b-479c-8db8-73d195a019ce
      iscommand: true
      name: Report Error Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e96a809f-c46b-479c-8db8-73d195a019ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 390,
          "y": 1080
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Successfully sent scanner and appliance list to PANW IoT Cloud
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: acf09ae4-3cac-4117-883f-afa7928d5556
      iscommand: true
      name: Report Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: acf09ae4-3cac-4117-883f-afa7928d5556
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 800,
          "y": 1080
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 37d27945-1e41-4cde-8233-ee111e0efaf9
      iscommand: true
      name: close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 37d27945-1e41-4cde-8233-ee111e0efaf9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 390,
          "y": 1260
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "13"
      "no":
      - "14"
      "yes":
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Tenable.io
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7f81d4af-b634-4959-8e0b-871c54cc6ca2
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 7f81d4af-b634-4959-8e0b-871c54cc6ca2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 530
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 3e38dce5-dcb6-48e9-83b3-bf6f93baa635
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 3e38dce5-dcb6-48e9-83b3-bf6f93baa635
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 730
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: e459670b-1428-4807-8b34-efd36a6ba623
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: e459670b-1428-4807-8b34-efd36a6ba623
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 730
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 2e2c3fea-b511-49a3-8df0-e359db4a5ddf
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 2e2c3fea-b511-49a3-8df0-e359db4a5ddf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 905
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "19"
      "yes":
      - "12"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Tenable.io
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 31088b5c-54d4-470b-8586-c444ace74d15
      iscommand: false
      name: Is Tenable Integration Instance Enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 31088b5c-54d4-470b-8586-c444ace74d15
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 850,
          "y": 370
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      scanner_sync:
        simple: ${incident.automaticallysynchronizescannerswithiotsecuritytoavoidfalsesecurityalerts}
      tenable_instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Get list of Tenable Scanners and Profiles and Send to IoT
      id: d2b198f7-0488-451d-8602-7d4bf9c8bf31
      iscommand: false
      name: Get list of Tenable Scanners and Profiles and Send to IoT
      script: GetTenableScannersAndProfiles
      type: regular
      version: -1
    taskid: d2b198f7-0488-451d-8602-7d4bf9c8bf31
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 200,
          "y": 730
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Tenable Integration is not enabled.
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: e6ac8186-36e5-4cbe-80c9-9d1e0ad048c3
      iscommand: true
      name: Report Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e6ac8186-36e5-4cbe-80c9-9d1e0ad048c3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1390,
          "y": 730
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1275,
        "width": 1790,
        "x": -20,
        "y": 80
      }
    }
  }
