contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 840ba626-dac4-47f5-8cc6-bc892aea77f9
inputs: []
name: extract-dnac-clients
outputs: []
sourceplaybookid: 148aadac-6b17-442a-8d6b-26e9befd59e3
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0ce0a9d6-7b82-4c89-8eff-3c6224029b34
      iscommand: false
      name: ""
      version: -1
    taskid: 0ce0a9d6-7b82-4c89-8eff-3c6224029b34
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      active_range:
        simple: ${incident.playbookpollinterval}
      dnac_instance_name:
        simple: ${incident.integrationinstancename}
      execution-timeout:
        simple: "172800"
      siteids:
        simple: ${incident.sitenames}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 032f7a34-b51b-4db8-81e9-c72d170212bd
      iscommand: false
      name: Send All PANW Device Attributes From DNAC to PANW
      script: ExportDeviceAttributesFromDnacToPANWIoTCloud
      type: regular
      version: -1
    taskid: 032f7a34-b51b-4db8-81e9-c72d170212bd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "25"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - cisco-dnac-IoT
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: bd1bf2d1-0585-416c-8de0-9b9cae125de6
      iscommand: false
      name: Is DNA Center enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: bd1bf2d1-0585-416c-8de0-9b9cae125de6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_dnac
      message:
        simple: Cisco DNA Center instance is not enabled
      playbook_name:
        simple: extract-dnac-clients
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 181de2ef-3730-4fb4-8db4-c4b8edbb45b0
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 181de2ef-3730-4fb4-8db4-c4b8edbb45b0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 3dfae265-ef9e-4694-8698-f60b4b9535f2
      iscommand: true
      name: close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 3dfae265-ef9e-4694-8698-f60b4b9535f2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "26"
      "no":
      - "27"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - cisco-dnac-IoT
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3257f17a-d6ea-44c8-8ed1-d61c81b6df2d
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 3257f17a-d6ea-44c8-8ed1-d61c81b6df2d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_dnac
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: extract-dnac-clients
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: c717d840-2ba1-4a90-8a8b-d26c1bcd610c
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: c717d840-2ba1-4a90-8a8b-d26c1bcd610c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "27":
    continueonerror: true
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_dnac
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: extract-dnac-clients
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 5eda2dc0-d1c2-4de5-8e54-3705df15bdf8
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 5eda2dc0-d1c2-4de5-8e54-3705df15bdf8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "28":
    continueonerror: true
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 1f671323-4899-4f5f-86b9-06da065f357e
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 1f671323-4899-4f5f-86b9-06da065f357e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_11_no": 0.46
    },
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
