contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 1.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5fde057b-bb45-4a90-8db4-5873a3419115
inputs: []
name: Tenable Scan Launch - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f46ba439-ad4f-4866-854c-b79c27fb75f6
      iscommand: false
      name: ""
      version: -1
    taskid: f46ba439-ad4f-4866-854c-b79c27fb75f6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 562.5,
          "y": -110
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "9"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Tenable.io
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 85722706-01d4-477a-8313-7da042fc30b7
      iscommand: false
      name: Is Tenable Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 85722706-01d4-477a-8313-7da042fc30b7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 570,
          "y": 40
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      scanId:
        simple: ${Tenable.scanId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Launches a scan with existing or custom targets. You can specify
        custom targets in the command arguments.
      id: a536b1ab-2e0d-45d4-8655-c2399204a4fc
      iscommand: true
      name: Launch Tenable.io vulnerability Scan
      script: '|||tenable-io-launch-scan'
      type: regular
      version: -1
    taskid: a536b1ab-2e0d-45d4-8655-c2399204a4fc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 930
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Tenable integration is not enabled
      playbook_name:
        simple: Tenable Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: b5aa3c28-99ba-49be-834a-a8d537534597
      iscommand: true
      name: Report disabled status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: b5aa3c28-99ba-49be-834a-a8d537534597
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -210,
          "y": 1920
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "5"
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
      path:
        simple: Tenable.scanLaunchfailStatus
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks for errors in a given task. If found, write it to the path
        provided as an argument.
      id: b8688ce7-4fcf-4d20-867a-f8e55169ce28
      iscommand: false
      name: Did the Scan Launch Fail?
      script: GetPANWIoTTenableErrors
      type: condition
      version: -1
    taskid: b8688ce7-4fcf-4d20-867a-f8e55169ce28
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 1095
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: The Tenable scan launch failed for ip - ${incident.ip}
      playbook_name:
        simple: Tenable Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 4bbda9ae-6f40-4284-8396-b8fb9f8e1c58
      iscommand: true
      name: Report Scan Launch Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 4bbda9ae-6f40-4284-8396-b8fb9f8e1c58
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 640,
          "y": 1920
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: TenableLaunchedScans
      operation:
        simple: insert
      value:
        simple: ${Tenable.scanId}_${Tenable.scanUUID}_${incident.ip}_${incident.jobid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: List operations, will create a new list if list does not exist
      id: bf2ee15a-481c-4d84-8059-4205025012e1
      iscommand: false
      name: Update Tenable launched scan cache
      script: 546f3d11-a5cf-488e-8952-87e66e17e951
      type: regular
      version: -1
    taskid: bf2ee15a-481c-4d84-8059-4205025012e1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1137.5,
          "y": 1310
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Successfully launched scan for ip - ${incident.ip}
      playbook_name:
        simple: Tenable Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: f8e11a9a-da53-44f7-8ee0-96dcfa2c9ceb
      iscommand: true
      name: Report Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: f8e11a9a-da53-44f7-8ee0-96dcfa2c9ceb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1460,
          "y": 1900
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 9ece9fca-731c-4621-8f94-c11e36bb85fb
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 9ece9fca-731c-4621-8f94-c11e36bb85fb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 2130
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      IP:
        simple: ${incident.ip}
      job_id:
        simple: ${incident.jobid}
      profile_Id:
        simple: ${incident.profileId}
      scan_name:
        simple: ${incident.ip}_panw_iot_scan
      scanner_Id:
        simple: ${incident.scannerId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Initiate scan '
      id: 50e7dbc1-b1f9-4da6-85fb-d633c869a73c
      iscommand: true
      name: Initiate Tenable.io vulnerability Scan
      script: '|||tenable-io-initiate-scan'
      type: regular
      version: -1
    taskid: 50e7dbc1-b1f9-4da6-85fb-d633c869a73c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 220
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "10"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 19b4d21f-d933-4224-8b64-0c0aaabeb9eb
      iscommand: false
      name: Wait for 10 sec
      script: Sleep
      type: regular
      version: -1
    taskid: 19b4d21f-d933-4224-8b64-0c0aaabeb9eb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 780
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 406a17b0-7267-4c7a-8e3d-03d9fc6fff67
      iscommand: false
      name: Was there any error in updating the Tenable Launched scan cache?
      script: isError
      type: condition
      version: -1
    taskid: 406a17b0-7267-4c7a-8e3d-03d9fc6fff67
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1137.5,
          "y": 1460
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobid}
      message:
        simple: ${Tenable.scanLaunchfailStatus}
      scan_type:
        simple: tenable
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Upload reports (PDF + XML) for specified scan to IoT Cloud
      id: 772556d9-0dc6-495f-8350-091f1e5d3bc3
      iscommand: true
      name: Report Scan Launch Error As Event
      script: '|||panw-iot-3rd-party-upload-vulnerability-scan-report'
      type: regular
      version: -1
    taskid: 772556d9-0dc6-495f-8350-091f1e5d3bc3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 212.5,
          "y": 1920
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Tenable.scanLaunchfailStatus
      value:
        simple: Unable to update XSOAR scan cache list for IP ${incident.ip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 13f416d7-12d6-48dc-8469-22f4d8b66e7b
      iscommand: false
      name: Format error message for launch cache update
      script: Set
      type: regular
      version: -1
    taskid: 13f416d7-12d6-48dc-8469-22f4d8b66e7b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 1740
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "12"
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: fb34b8a0-1940-4de5-8a13-a0d66cce26f1
      iscommand: false
      name: Did the Scan Initiation fail?
      script: isError
      type: condition
      version: -1
    taskid: fb34b8a0-1940-4de5-8a13-a0d66cce26f1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 565
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      contextKey:
        simple: Tenable.scanLaunchfailStatus
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Takes the comments of a given entry ID and stores them in the
        incident context, under a provided context key. \nFor accessing the last executed
        task's comments, provide ${lastCompletedTaskEntries.[0]} as the value for
        the entryId input parameter."
      id: a6ca18b7-f43b-4c35-8581-5c571988ed73
      iscommand: false
      name: Add output to error message
      script: commentsToContext
      type: regular
      version: -1
    taskid: a6ca18b7-f43b-4c35-8581-5c571988ed73
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2335,
        "width": 2050,
        "x": -210,
        "y": -110
      }
    }
  }
