contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Alert to ServiceNow.
id: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: de5b1fe5-27a2-42ad-8d38-fb6dcca31fba
      iscommand: false
      name: ""
      version: -1
    taskid: de5b1fe5-27a2-42ad-8d38-fb6dcca31fba
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: ea4ee826-15ab-43d7-875b-9acc48f6394a
      iscommand: false
      name: Is ServiceNow enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: ea4ee826-15ab-43d7-875b-9acc48f6394a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        complex:
          root: incident
          transformers:
          - args:
              field:
                value:
                  simple: correlation_id
            operator: getField
      asset_type:
        simple: alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given a asset ID (alert-id, vulnerability-id or mac-address)
        returns the asset details.
      id: 12bb29b1-633d-43b9-8578-3c1da0bff6c7
      iscommand: true
      name: Get single alert instance
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-single-asset
      type: regular
      version: -1
    taskid: 12bb29b1-633d-43b9-8578-3c1da0bff6c7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: servicenow
      message:
        simple: ServiceNow instance is not enabled
      playbook_name:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 3bfb5bd0-884b-483f-8b93-567027f26a96
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 3bfb5bd0-884b-483f-8b93-567027f26a96
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 81d20c43-ebfd-443f-84ad-f4517c4eef88
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 81d20c43-ebfd-443f-84ad-f4517c4eef88
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 7e560345-c822-43a5-8b75-c62df122d444
      iscommand: false
      name: Does alert instance exist?
      script: Exists
      type: condition
      version: -1
    taskid: 7e560345-c822-43a5-8b75-c62df122d444
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset:
        complex:
          accessor: SingleAsset
          root: PanwIot3rdParty
          transformers:
          - args:
              index:
                value:
                  simple: "0"
            operator: atIndex
      asset_list:
        simple: ${PanwIot3rdParty.SingleAsset}
      asset_type:
        simple: alert
      incident:
        simple: ${incident}
      output_format:
        simple: ServiceNow
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given asset (alert, device, vuln) converts it to 3rd party
        format.
      id: 84b0869a-6201-4687-8811-28034ae89b85
      iscommand: true
      name: Convert alert to ServiceNow format
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-convert-assets-to-external-format
      type: regular
      version: -1
    taskid: 84b0869a-6201-4687-8811-28034ae89b85
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: servicenow
      message:
        simple: Failed to get alert instance zb_ticket id ${incident.correlation_id}
      playbook_name:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 8ebdfd5e-2a74-4b04-82d3-79490b422e5f
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 8ebdfd5e-2a74-4b04-82d3-79490b422e5f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 5f98439a-c1d7-460b-8915-d78e4d092138
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 5f98439a-c1d7-460b-8915-d78e4d092138
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "12"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: a00b979f-dcd2-4291-8763-123780bbbf5e
      iscommand: false
      name: Was there an error when converting alert to Servicenow format?
      script: isError
      type: condition
      version: -1
    taskid: a00b979f-dcd2-4291-8763-123780bbbf5e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: servicenow
      message:
        simple: Failed to convert alert to servicenow format
      playbook_name:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: e400ca9b-a508-4bfa-8170-660435028f85
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: e400ca9b-a508-4bfa-8170-660435028f85
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 3b7c200d-9f53-431a-8ff3-93ef02b6865a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 3b7c200d-9f53-431a-8ff3-93ef02b6865a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      fields:
        simple: ${PanwIot3rdParty.AlertServiceNow}
      table_name:
        simple: u_zingbox_alerts_vulnerability_incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: PANW IoT 3rd Party Integration - ServiceNow v2
      description: Creates a new record in the specified ServiceNow table.
      id: a72a0a9b-65c9-47de-8131-c9d27d6daa0d
      iscommand: true
      name: Create Servicenow record
      script: PANW IoT 3rd Party Integration - ServiceNow v2|||servicenow-create-record
      type: regular
      version: -1
    taskid: a72a0a9b-65c9-47de-8131-c9d27d6daa0d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: servicenow
      message:
        simple: Success to send alert instance zb_ticket id ${incident.correlation_id}
          to ServiceNow
      playbook_name:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 70e6c6a6-2279-4277-8342-ed6efd4eea3d
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 70e6c6a6-2279-4277-8342-ed6efd4eea3d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1420
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: d11bb6c1-51f8-4fa1-87e8-88b47cb1a8a4
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d11bb6c1-51f8-4fa1-87e8-88b47cb1a8a4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1595
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "13"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: c544e59b-7de7-4f08-8dfc-9bce8b28a2d0
      iscommand: false
      name: Was there an error when creating Servicenow record?
      script: isError
      type: condition
      version: -1
    taskid: c544e59b-7de7-4f08-8dfc-9bce8b28a2d0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1245
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: servicenow
      message:
        simple: Failed to create record in servicenow table
      playbook_name:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 5672d0f4-a590-40f2-8c9f-b4f7d9f71549
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 5672d0f4-a590-40f2-8c9f-b4f7d9f71549
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1420
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 93d52749-2ece-4bce-8c79-01f820e81c3f
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 93d52749-2ece-4bce-8c79-01f820e81c3f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1595
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1640,
        "width": 1455,
        "x": 50,
        "y": 50
      }
    }
  }
