contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d898a03f-1c19-46a7-8a2d-0d3660a3c374
inputs: []
name: Import Aruba AirWave VisualRF Clients to PANW IoT
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 472aa7a9-8813-4a89-8a0f-ebb6add1726e
      iscommand: false
      name: ""
      version: -1
    taskid: 472aa7a9-8813-4a89-8a0f-ebb6add1726e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 275,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8767b322-e113-435f-8d72-9dd37e7881bd
      iscommand: false
      name: Send Aruba AirWave VRF Clients to PANW IoT
      script: 2f11929a-9cbc-443b-8899-557fcdd0f227
      type: regular
      version: -1
    taskid: 8767b322-e113-435f-8d72-9dd37e7881bd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1790,
          "y": 720
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ${incident.integrationinstancename}
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 3c72e50b-1f10-4150-89cd-137d09a8e22d
      iscommand: false
      name: Is Aruba AirWave Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: 3c72e50b-1f10-4150-89cd-137d09a8e22d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 195
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: aruba_airwave
      message:
        simple: No SolarWinds Integration instance passed
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 879eadbe-786c-4681-8f5b-355da4ca570a
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 879eadbe-786c-4681-8f5b-355da4ca570a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "no":
      - "7"
      "yes":
      - "8"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba AirWave
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: bc19e208-e541-43b4-858f-1034e3200dab
      iscommand: false
      name: Is Aruba AirWave integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: bc19e208-e541-43b4-858f-1034e3200dab
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 705,
          "y": 370
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: Invalid integration instance name provided
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: dd511e04-5b8f-4945-8934-e4420b655e1b
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: dd511e04-5b8f-4945-8934-e4420b655e1b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: SolarWinds UDT integration is not enabled
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 725602a1-8289-40a8-8da1-fac36dd6afd0
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 725602a1-8289-40a8-8da1-fac36dd6afd0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "13"
      "no":
      - "9"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - Aruba AirWave
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 188433ae-60d6-4dd8-8f78-efbec0181a38
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 188433ae-60d6-4dd8-8f78-efbec0181a38
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 545
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: b72e0fc7-c6b5-4c35-88c9-e33320309237
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: b72e0fc7-c6b5-4c35-88c9-e33320309237
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 720
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: ae90b5ec-aaa4-42b8-8988-d45d145691cb
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ae90b5ec-aaa4-42b8-8988-d45d145691cb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1565,
          "y": 895
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aruba_airwave
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import Aruba AirWave VisualRF Clients to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 437bff5a-c704-46bf-8685-3787c3f99706
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 437bff5a-c704-46bf-8685-3787c3f99706
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 720
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: cf1a50c4-ec9b-4c26-8fd2-d72ebc701a81
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: cf1a50c4-ec9b-4c26-8fd2-d72ebc701a81
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 2120,
        "x": 50,
        "y": 50
      }
    }
  }
