contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Vulnerability to ServiceNow.
dirtyInputs: true
id: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: af3d8138-03e6-46bc-8fe0-132fb8971d5e
      iscommand: false
      name: ""
      version: -1
    taskid: af3d8138-03e6-46bc-8fe0-132fb8971d5e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: d81a6f9d-56bd-4051-8767-83a75cf1d884
      iscommand: false
      name: Is ServiceNow available
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: d81a6f9d-56bd-4051-8767-83a75cf1d884
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Servicenow instance is not enabled
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 566b8d44-d505-4a4a-84a1-148bfa38c1a8
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 566b8d44-d505-4a4a-84a1-148bfa38c1a8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: ee4d1f79-0dae-469b-84fa-77906e2e4727
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ee4d1f79-0dae-469b-84fa-77906e2e4727
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${incident.correlation_id}
      asset_type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given a asset ID (alert-id, vulnerability-id or mac-address)
        returns the asset details.
      id: 865a9912-7332-4760-89a5-e6506005754b
      iscommand: true
      name: Get single vulnerability instance
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-single-asset
      type: regular
      version: -1
    taskid: 865a9912-7332-4760-89a5-e6506005754b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 44fc62aa-8cc1-470f-8752-d2c54ca9915b
      iscommand: false
      name: Does the vulnerability exist?
      script: Exists
      type: condition
      version: -1
    taskid: 44fc62aa-8cc1-470f-8752-d2c54ca9915b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Cannot find vulnerability with zb_ticketid ${incident.correlation_id}
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 3facf0ba-c82f-4c11-8d5e-15c759e1d007
      iscommand: true
      name: Send error status back to PANW IoT
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 3facf0ba-c82f-4c11-8d5e-15c759e1d007
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 8fccae52-b8d5-4357-8ba5-6fbd20f44e08
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8fccae52-b8d5-4357-8ba5-6fbd20f44e08
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_list:
        simple: ${PanwIot3rdParty.SingleAsset}
      asset_type:
        simple: vulnerability
      incident:
        simple: ${incident}
      output_format:
        simple: ServiceNow
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given asset (alert, device, vuln) converts it to 3rd party
        format.
      id: 01c7f77b-2143-49e2-86d3-9bf6cfd50f6f
      iscommand: true
      name: Convert vulnerability to ServiceNow format
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-convert-assets-to-external-format
      type: regular
      version: -1
    taskid: 01c7f77b-2143-49e2-86d3-9bf6cfd50f6f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "12"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 8e733533-f660-4b18-820c-b2f0ea30a3c4
      iscommand: false
      name: Was there an error when converting format?
      script: isError
      type: condition
      version: -1
    taskid: 8e733533-f660-4b18-820c-b2f0ea30a3c4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Cannot convert vulnerability to servicenow data format
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 95d47538-e392-475a-8767-4fa2f0789b3a
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 95d47538-e392-475a-8767-4fa2f0789b3a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: dcab8997-6328-4d49-8d65-a398e1b2041a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: dcab8997-6328-4d49-8d65-a398e1b2041a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      fields:
        simple: ${PanwIot3rdParty.VulnerabilityServiceNow}
      table_name:
        simple: u_zingbox_alerts_vulnerability_incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: PANW IoT 3rd Party Integration - ServiceNow v2
      description: Creates a new record in the specified ServiceNow table.
      id: 3d67c87a-8495-43c9-85dc-8fab7080651e
      iscommand: true
      name: Create Servicenow record
      script: PANW IoT 3rd Party Integration - ServiceNow v2|||servicenow-create-record
      type: regular
      version: -1
    taskid: 3d67c87a-8495-43c9-85dc-8fab7080651e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "16"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: e9b4b76f-adb9-4fcd-82f2-9ad42fe3364a
      iscommand: false
      name: Was there an error when creating the record in Servicenow?
      script: isError
      type: condition
      version: -1
    taskid: e9b4b76f-adb9-4fcd-82f2-9ad42fe3364a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1245
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Failed to send vulnerability to ServiceNow
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: cff667f8-665f-46e3-8aca-173f40876630
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: cff667f8-665f-46e3-8aca-173f40876630
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1420
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 10dcd0ec-ba41-4e6a-8e81-26c8da023681
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 10dcd0ec-ba41-4e6a-8e81-26c8da023681
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1595
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      integration_name:
        simple: servicenow
      message:
        simple: Success to send vulnerability instance zb_ticket id ${incident.correlation_id}
          to ServiceNow
      playbook_name:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: cee4c9e1-523a-4ccd-870f-7debf0d04354
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: cee4c9e1-523a-4ccd-870f-7debf0d04354
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1420
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 23c0ad34-4476-4706-83c2-f81d50b62dda
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 23c0ad34-4476-4706-83c2-f81d50b62dda
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1595
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1640,
        "width": 1455,
        "x": 50,
        "y": 50
      }
    }
  }
