contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.7.65
    packID: CortexAttackSurfaceManagement
    packName: Cortex Attack Surface Management
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Identifies and recommends the most likely owners of the service, additionally
  citing an explanation and ranking score for each.
id: Cortex ASM - Service Ownership
inputs: []
name: Cortex ASM - Service Ownership
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      id: c2b9f9a3-1791-4bae-88fa-218fb9363813
      iscommand: false
      name: ""
      version: -1
    taskid: c2b9f9a3-1791-4bae-88fa-218fb9363813
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": -50,
          "y": -150
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asmsystemids:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.asmsystemids.type
              operator: containsString
              right:
                value:
                  simple: ASSET-NAME
          root: alert.asmsystemids
          transformers:
          - args:
              field:
                value:
                  simple: id
            operator: getField
      owners:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.asmserviceownerunrankedraw.accounttype
              operator: isNotExists
            - left:
                iscontext: true
                value:
                  simple: alert.asmserviceownerunrankedraw.accounttype
              operator: isNotEqualString
              right:
                value:
                  simple: SERVICE-ACCOUNT
          root: alert.asmserviceownerunrankedraw
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Recommend most likely service owners from those surfaced by Cortex
        ASM Enrichment.
      id: fa87fb97-33f7-4e96-8c0a-2bcaa794b242
      iscommand: false
      name: Normalize and rank likely service owners
      script: RankServiceOwners
      type: regular
      version: -1
    taskid: fa87fb97-33f7-4e96-8c0a-2bcaa794b242
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -50,
          "y": 400
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: alert.asmserviceownerunrankedraw
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: alert.asmserviceownerunrankedraw.email
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: alert.asmserviceownerunrankedraw.name
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: alert.asmserviceownerunrankedraw.source
          operator: isNotEmpty
      label: unranked raw
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      unranked raw:
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if the asmserviceowner or asmserviceownerunrankedraw
        fields have been populated to continue.
      id: 3c890c55-0002-44ef-8205-1027ca45d05f
      iscommand: false
      name: Is asmserviceownerunrankedraw populated?
      type: condition
      version: -1
    taskid: 3c890c55-0002-44ef-8205-1027ca45d05f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -50,
          "y": 0
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 18ae13e1-3413-44ba-82be-078c4c18fa9e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 18ae13e1-3413-44ba-82be-078c4c18fa9e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 190,
          "y": 570
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      external_service:
        simple: ${alert.asmprovider}
      owners:
        simple: ${alert.asmserviceownerunrankedraw}
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Parse a GCP service account email for the project name, then lookup
        project owners and add them to a list of potential service owners for ranking.
      id: 06c23e12-3c68-49cc-81cb-37141b08c56d
      iscommand: false
      name: Look up project owners for service account
      script: GetProjectOwners
      type: regular
      version: -1
    taskid: 06c23e12-3c68-49cc-81cb-37141b08c56d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -50,
          "y": 225
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "9_10_#default#": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 785,
        "width": 620,
        "x": -50,
        "y": -150
      }
    }
  }
