contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 1.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5fde057b-bb45-4a90-8db4-5873a3419115
inputs: []
name: Tenable Scan Launch - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dc94aab7-771f-4355-8677-56e6e2f6e270
      iscommand: false
      name: ""
      version: -1
    taskid: dc94aab7-771f-4355-8677-56e6e2f6e270
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 562.5,
          "y": -110
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "9"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Tenable.io
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 7bc63e06-706c-4359-8606-e04e93b18c07
      iscommand: false
      name: Is Tenable Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 7bc63e06-706c-4359-8606-e04e93b18c07
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 570,
          "y": 40
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      scanId:
        simple: ${Tenable.scanId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Launches a scan with existing or custom targets. You can specify
        custom targets in the command arguments.
      id: b095111e-dc68-4cbe-8b65-2c80541c5cc6
      iscommand: true
      name: Launch Tenable.io vulnerability Scan
      script: '|||tenable-io-launch-scan'
      type: regular
      version: -1
    taskid: b095111e-dc68-4cbe-8b65-2c80541c5cc6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 930
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Tenable integration is not enabled
      playbook_name:
        simple: Tenable Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: abb735d0-76e4-47cb-8a83-720ff02d8c3d
      iscommand: true
      name: Report disabled status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: abb735d0-76e4-47cb-8a83-720ff02d8c3d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -210,
          "y": 1920
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "5"
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
      path:
        simple: Tenable.scanLaunchfailStatus
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks for errors in a given task. If found, write it to the path
        provided as an argument.
      id: d4d9cb0f-082b-4749-8605-ccd9da070614
      iscommand: false
      name: Did the Scan Launch Fail?
      script: GetPANWIoTTenableErrors
      type: condition
      version: -1
    taskid: d4d9cb0f-082b-4749-8605-ccd9da070614
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 1095
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: The Tenable scan launch failed for ip - ${incident.ip}
      playbook_name:
        simple: Tenable Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 84a8e7db-75cc-4573-8ba6-ee8aa68fe040
      iscommand: true
      name: Report Scan Launch Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 84a8e7db-75cc-4573-8ba6-ee8aa68fe040
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 640,
          "y": 1920
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: TenableLaunchedScans
      operation:
        simple: insert
      value:
        simple: ${Tenable.scanId}_${Tenable.scanUUID}_${incident.ip}_${incident.jobid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: List operations, will create a new list if list does not exist
      id: 3da2c86f-da3e-4299-839c-d2dfb908635a
      iscommand: false
      name: Update Tenable launched scan cache
      script: 546f3d11-a5cf-488e-8952-87e66e17e951
      type: regular
      version: -1
    taskid: 3da2c86f-da3e-4299-839c-d2dfb908635a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1137.5,
          "y": 1310
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Successfully launched scan for ip - ${incident.ip}
      playbook_name:
        simple: Tenable Scan Launch - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 17568e29-1283-40c6-86df-e08e4406aa93
      iscommand: true
      name: Report Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 17568e29-1283-40c6-86df-e08e4406aa93
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1460,
          "y": 1900
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 407d02f7-be71-4818-832b-1c2f17b58eba
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 407d02f7-be71-4818-832b-1c2f17b58eba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 2130
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      IP:
        simple: ${incident.ip}
      job_id:
        simple: ${incident.jobid}
      profile_Id:
        simple: ${incident.profileId}
      scan_name:
        simple: ${incident.ip}_panw_iot_scan
      scanner_Id:
        simple: ${incident.scannerId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Initiate scan '
      id: e501df63-d073-4fca-8b21-47c6b3f6079f
      iscommand: true
      name: Initiate Tenable.io vulnerability Scan
      script: '|||tenable-io-initiate-scan'
      type: regular
      version: -1
    taskid: e501df63-d073-4fca-8b21-47c6b3f6079f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 220
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "10"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: aa542943-113c-4b4a-826a-d2947ba6bc63
      iscommand: false
      name: Wait for 10 sec
      script: Sleep
      type: regular
      version: -1
    taskid: aa542943-113c-4b4a-826a-d2947ba6bc63
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 780
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 8f62ea54-3454-4ba8-8ff5-990b2a733b2e
      iscommand: false
      name: Was there any error in updating the Tenable Launched scan cache?
      script: isError
      type: condition
      version: -1
    taskid: 8f62ea54-3454-4ba8-8ff5-990b2a733b2e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1137.5,
          "y": 1460
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${incident.jobid}
      message:
        simple: ${Tenable.scanLaunchfailStatus}
      scan_type:
        simple: tenable
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Upload reports (PDF + XML) for specified scan to IoT Cloud
      id: 23835ffa-6048-4ca9-8663-370b938d58e5
      iscommand: true
      name: Report Scan Launch Error As Event
      script: '|||panw-iot-3rd-party-upload-vulnerability-scan-report'
      type: regular
      version: -1
    taskid: 23835ffa-6048-4ca9-8663-370b938d58e5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 212.5,
          "y": 1920
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Tenable.scanLaunchfailStatus
      value:
        simple: Unable to update XSOAR scan cache list for IP ${incident.ip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 3d3fe75e-a48a-407c-8c59-035191660969
      iscommand: false
      name: Format error message for launch cache update
      script: Set
      type: regular
      version: -1
    taskid: 3d3fe75e-a48a-407c-8c59-035191660969
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 1740
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "12"
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 4576d616-4bc6-424b-8cb6-06bd76d66ef6
      iscommand: false
      name: Did the Scan Initiation fail?
      script: isError
      type: condition
      version: -1
    taskid: 4576d616-4bc6-424b-8cb6-06bd76d66ef6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 777.5,
          "y": 565
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      contextKey:
        simple: Tenable.scanLaunchfailStatus
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Takes the comments of a given entry ID and stores them in the
        incident context, under a provided context key. \nFor accessing the last executed
        task's comments, provide ${lastCompletedTaskEntries.[0]} as the value for
        the entryId input parameter."
      id: 13c4fc88-7718-4613-88ad-ff696c8b1855
      iscommand: false
      name: Add output to error message
      script: commentsToContext
      type: regular
      version: -1
    taskid: 13c4fc88-7718-4613-88ad-ff696c8b1855
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2335,
        "width": 2050,
        "x": -210,
        "y": -110
      }
    }
  }
