contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Fetch data from Cisco WLAN Controller and send it to PANW IoT Platform
id: 502bf805-0a86-43a3-8955-f5ba18746dac
inputs: []
name: Import Cisco WLC devices to PANW IoT cloud
outputs: []
sourceplaybookid: Import Cisco WLC devices to PANW IoT cloud
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 848bf7e9-3862-4acf-8c81-5482f397d0b5
      iscommand: false
      name: ""
      version: -1
    taskid: 848bf7e9-3862-4acf-8c81-5482f397d0b5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -340
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "no":
      - "2"
      "yes":
      - "20"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Cisco WLAN Controller
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 81af863a-4075-4d6d-8c75-6f3d638193fb
      iscommand: false
      name: Is Cisco WLC integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 81af863a-4075-4d6d-8c75-6f3d638193fb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": -160
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_wlc
      message:
        simple: Cisco WLAN Controller integration is not enabled
      playbook_name:
        simple: Import Cisco WLC devices to PANW IoT cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: dce18aa4-472e-4797-8770-2b93c66a6769
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: dce18aa4-472e-4797-8770-2b93c66a6769
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 140
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: f2fb2af8-fbd6-448a-8e32-817ba6c174f2
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f2fb2af8-fbd6-448a-8e32-817ba6c174f2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 650,
          "y": 850
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      cisco_wlc_instance:
        simple: ${incident.integrationinstancename}
      device_type:
        simple: wifi
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b5d62ca4-08fb-413a-8fe8-0b643f5f0095
      iscommand: false
      name: Send Cisco WiFi clients to PanW IoT
      script: 832854c5-330c-49f0-85b3-318cea69d589
      type: regular
      version: -1
    taskid: b5d62ca4-08fb-413a-8fe8-0b643f5f0095
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 650,
          "y": 540
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      cisco_wlc_instance:
        simple: ${incident.integrationinstancename}
      device_type:
        simple: bluetooth
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ec664470-ce41-49a0-8488-b0ced4d604d5
      iscommand: false
      name: Send Cisco Bluetooth clients to PanW IoT
      script: 832854c5-330c-49f0-85b3-318cea69d589
      type: regular
      version: -1
    taskid: ec664470-ce41-49a0-8488-b0ced4d604d5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 650,
          "y": 705
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_wlc
      message:
        simple: Invalid integration name provided
      playbook_name:
        simple: Import Cisco WLC devices to PANW IoT cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 7aa9a087-123f-4f3b-8b84-16ca93c2a51b
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 7aa9a087-123f-4f3b-8b84-16ca93c2a51b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -260,
          "y": 140
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 4898cb36-29b1-470b-8d6f-524f1d97282c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4898cb36-29b1-470b-8d6f-524f1d97282c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -30,
          "y": 350
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "21"
      "no":
      - "22"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration_instance_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: PANW IoT 3rd Party Integration - Cisco WLAN Controller
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 25ee1c04-96d0-49d3-8573-66fbf55645d5
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 25ee1c04-96d0-49d3-8573-66fbf55645d5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 650,
          "y": 140
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_wlc
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Import Cisco WLC devices to PANW IoT cloud
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 29eb6eaf-13a4-4fa0-87c0-62a57978fac9
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 29eb6eaf-13a4-4fa0-87c0-62a57978fac9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 980,
          "y": 350
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: cisco_wlc
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Import Cisco WLC devices to PANW IoT cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: ade547d8-322d-4a26-805c-7e3851ca1ee9
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: ade547d8-322d-4a26-805c-7e3851ca1ee9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 350
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 4703f556-6d28-4f95-8f61-f722f025d50c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4703f556-6d28-4f95-8f61-f722f025d50c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1210,
          "y": 540
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      cisco_wlc_instance:
        simple: ${incident.integrationinstancename}
      device_type:
        simple: AP
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c48d78a7-57e2-4b7d-8068-cd14a67f239a
      iscommand: false
      name: Send Cisco Access Points to PanW IoT
      script: 832854c5-330c-49f0-85b3-318cea69d589
      type: regular
      version: -1
    taskid: c48d78a7-57e2-4b7d-8068-cd14a67f239a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 650,
          "y": 875
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1285,
        "width": 2040,
        "x": -260,
        "y": -340
      }
    }
  }
