contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
dirtyInputs: true
id: 67b384a4-542e-4c6b-88b5-01585f061ed3
inputSections:
- description: Generic group for inputs
  inputs:
  - test
  - should-close-investigation
  name: General (Inputs group)
inputs:
- description: ""
  key: test
  playbookInputQuery: null
  required: false
  value:
    simple: test!
- description: ""
  key: should-close-investigation
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
name: Read-Write-Context-Playbook
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dce70522-9347-434d-89f1-495f5c895816
      iscommand: false
      name: ""
      version: -1
    taskid: dce70522-9347-434d-89f1-495f5c895816
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: test
      value:
        simple: ${inputs.test}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 32a1d55a-b96d-4ce7-85ef-28b63da7fdb0
      iscommand: false
      name: Set Context
      script: Set
      type: regular
      version: -1
    taskid: 32a1d55a-b96d-4ce7-85ef-28b63da7fdb0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 260
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      data:
        simple: ${test}
      newValue:
        simple: replaced-value-test!
      regex:
        simple: test!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Replaces regex match/es in string.
        Returns the string after replace was preformed.
      id: 6ac5e509-e1c9-42f8-88f9-73704f827cfc
      iscommand: false
      name: replace context string
      script: StringReplace
      type: regular
      version: -1
    taskid: 6ac5e509-e1c9-42f8-88f9-73704f827cfc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1270,
          "y": 835
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "2"
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      left:
        simple: ${test}
      right:
        simple: test!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: b6d37acd-697d-4ba1-82b3-14c0800f6d40
      iscommand: false
      name: Check if String equals test!
      script: AreValuesEqual
      type: condition
      version: -1
    taskid: b6d37acd-697d-4ba1-82b3-14c0800f6d40
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 480
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      data:
        simple: ${test}
      newValue:
        simple: replaced-value-test
      regex:
        simple: test
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Replaces regex match/es in string.
        Returns the string after replace was preformed.
      id: 4c724472-6626-46c9-8232-3ae333f849ba
      iscommand: false
      name: replace context string
      script: StringReplace
      type: regular
      version: -1
    taskid: 4c724472-6626-46c9-8232-3ae333f849ba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 770,
          "y": 835
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.should-close-investigation
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 25650a3a-f2b8-4f05-8620-9afd8f93cf35
      iscommand: false
      name: Should Close Investigation
      type: condition
      version: -1
    taskid: 25650a3a-f2b8-4f05-8620-9afd8f93cf35
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 120,
          "y": 835
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${incident.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: a96712f0-b30b-4717-8d9a-59eb749f6982
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: a96712f0-b30b-4717-8d9a-59eb749f6982
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1090
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1135,
        "width": 1530,
        "x": 120,
        "y": 50
      }
    }
  }
