contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Export assignee list and work order priority list from AIMS to PANW IoT
  cloud
id: Export AIMS assignee and priority lists to PANW IoT
inputs: []
name: Export AIMS assignee and priority lists to PANW IoT
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b255cfa1-0109-4f52-81b7-1443a407e9c1
      iscommand: false
      name: ""
      version: -1
    taskid: b255cfa1-0109-4f52-81b7-1443a407e9c1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 70
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get a list of all employees in the AIMS server
      id: 24343066-ea14-4d30-8d69-eb20a9419f7c
      iscommand: true
      name: Get employee list
      script: '|||aims-get-employee-list'
      type: regular
      version: -1
    taskid: 24343066-ea14-4d30-8d69-eb20a9419f7c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 380
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: AIMS instance is not enabled
      playbook_name:
        simple: Export AIMS assignee and priority lists to PANW IoT
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 363a480b-78da-4cc0-8867-741dd4191b4c
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 363a480b-78da-4cc0-8867-741dd4191b4c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 130,
          "y": 720
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: c48040da-5ae2-4f17-8eb3-f36b88103752
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: c48040da-5ae2-4f17-8eb3-f36b88103752
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1245
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Error while getting data from AIMS
      playbook_name:
        simple: Export AIMS assignee and priority lists to PANW IoT
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: c6e6c441-c44c-4a06-8787-20f4364cfdd0
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: c6e6c441-c44c-4a06-8787-20f4364cfdd0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1060
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: aims
      message:
        simple: Successfully received data from AIMS
      playbook_name:
        simple: Export AIMS assignee and priority lists to PANW IoT
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 930c55aa-2991-4c7d-878f-b0b18bddb0b3
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 930c55aa-2991-4c7d-878f-b0b18bddb0b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1060
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the priority list for work orders in AIMS
      id: 1169ef7b-d669-4bdf-84ed-aaa67614f9f0
      iscommand: true
      name: Get work order priority list
      script: '|||aims-get-work-order-priority-list'
      type: regular
      version: -1
    taskid: 1169ef7b-d669-4bdf-84ed-aaa67614f9f0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 380
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "22"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: c69d3648-682f-4334-8df4-5c23ac3b13dc
      iscommand: false
      name: Was there an error getting data from AIMS?
      script: isError
      type: condition
      version: -1
    taskid: c69d3648-682f-4334-8df4-5c23ac3b13dc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 690,
          "y": 550
        }
      }
  "22":
    continueonerror: true
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      IntegrationName:
        simple: aims
      MetaData:
        simple: '{"EmployeeList": ${CommandOutput.EmployeeList}, "WorkOrderPriorityList":
          ${CommandOutput.WorkOrderPriorityList}}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send AIMS maps and list data to PANW IOT cloud
      id: b063bb5c-8fdb-41e8-8b95-7d4ab1511200
      iscommand: true
      name: Send assignee and priority lists to PANW IoT
      script: '|||panw-iot-3rd-party-report-metadata'
      type: regular
      version: -1
    taskid: b063bb5c-8fdb-41e8-8b95-7d4ab1511200
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 720
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 9fb2771f-ff82-4b75-8698-7a6190e8fb69
      iscommand: false
      name: Was there an error sending data to PANW IoT?
      script: isError
      type: condition
      version: -1
    taskid: 9fb2771f-ff82-4b75-8698-7a6190e8fb69
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 900,
          "y": 890
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "3"
      - "13"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - AIMS
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: 28275a16-86ac-4984-86a9-a9ff858eea1f
      iscommand: false
      name: Is AIMS Integration enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: 28275a16-86ac-4984-86a9-a9ff858eea1f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 205
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "21_10_yes": 0.3,
      "21_22_no": 0.54,
      "23_10_yes": 0.31,
      "24_13_yes": 0.48,
      "24_3_yes": 0.72
    },
    "paper": {
      "dimensions": {
        "height": 1270,
        "width": 1240,
        "x": 130,
        "y": 70
      }
    }
  }
