contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.3
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook to be run every 15 minutes via a job. Each run will get incremental
  updates for devices to send to ServiceNow server.
id: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8518886f-5b25-42ca-8708-d94b020a49ba
      iscommand: false
      name: ""
      version: -1
    taskid: 8518886f-5b25-42ca-8708-d94b020a49ba
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "42"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: cfbc9be5-680f-420c-8fcc-93a4c95b9c4b
      iscommand: false
      name: Is ServiceNow integration enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: cfbc9be5-680f-420c-8fcc-93a4c95b9c4b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: ServiceNow Integration is not enabled
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 87a0f077-ff1e-4cd8-8990-9c8fa999f468
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 87a0f077-ff1e-4cd8-8990-9c8fa999f468
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 0ed7306a-c8ed-46e1-8adb-b61ea7b83275
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 0ed7306a-c8ed-46e1-8adb-b61ea7b83275
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: ${SN-IoT.incrementResult}
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: f9e7b4e0-ac20-4959-84ff-8b527c310818
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: f9e7b4e0-ac20-4959-84ff-8b527c310818
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1770
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 4471748e-361c-4fe0-861e-79dd2d6faa1e
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4471748e-361c-4fe0-861e-79dd2d6faa1e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1945
        }
      }
  "35":
    continueonerror: true
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "41"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get PANW IoT and ServiceNow category mapping
      id: 2982ecdb-1794-49d4-8bb6-bad66d1d89b1
      iscommand: false
      name: Get PANW IoT ServiceNow Category Mapping
      script: GetPANWIoTServiceNowCategoryMapping
      type: regular
      version: -1
    taskid: 2982ecdb-1794-49d4-8bb6-bad66d1d89b1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1070
        }
      }
  "36":
    continueonerror: true
    continueonerrortype: ""
    id: "36"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all customized table and column names in the customers' ServiceNow.
      id: 5d3b7a64-a5d6-4ad5-8d7f-80b6b9936a26
      iscommand: false
      name: Get ServiceNow Customized Configuration
      script: GetServiceNowCustomizedConfiguration
      type: regular
      version: -1
    taskid: 5d3b7a64-a5d6-4ad5-8d7f-80b6b9936a26
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 895
        }
      }
  "37":
    continueonerror: true
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "38"
    note: false
    quietmode: 0
    scriptarguments:
      customized_servicenow_config:
        simple: ${PanwIot3rdParty.SNConfig}
      device_list:
        simple: ${PanwIot3rdParty.Devices}
      iot_servicenow_category_map:
        simple: ${PanwIot3rdParty.SNCategoryMapping}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send Incremental PANW IoT Devices To ServiceNow
      id: 61a6efe6-c43c-4a1e-8f33-5664b2662d72
      iscommand: false
      name: Send Incremental PANW IoT Devices To ServiceNow
      script: SendIncrementalPANWIoTDevicesToServiceNow
      type: regular
      version: -1
    taskid: 61a6efe6-c43c-4a1e-8f33-5664b2662d72
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1420
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "26"
      "yes":
      - "39"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 36a64aff-c7d2-426e-8219-730c9eebc2d9
      iscommand: false
      name: Was there an error when sending devices to servicenow?
      script: isError
      type: condition
      version: -1
    taskid: 36a64aff-c7d2-426e-8219-730c9eebc2d9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1595
        }
      }
  "39":
    continueonerror: true
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "40"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to do incremental device sync to ServiceNow. Please
          see the detailed error message from the playbook.'
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: e8aaaa00-012a-4c3e-82b5-6beb10aec679
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: e8aaaa00-012a-4c3e-82b5-6beb10aec679
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1770
        }
      }
  "40":
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 5a722e52-0671-4771-8913-c83ed780e9cb
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 5a722e52-0671-4771-8913-c83ed780e9cb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1945
        }
      }
  "41":
    continueonerror: true
    continueonerrortype: ""
    id: "41"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      increment_time:
        simple: "15"
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Returns a list of assets for the specified asset type.
      id: fdaeaa8c-31fd-4a02-8cd9-aea8ee623699
      iscommand: true
      name: Get PANW IoT Devices
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-asset-list
      type: regular
      version: -1
    taskid: fdaeaa8c-31fd-4a02-8cd9-aea8ee623699
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1245
        }
      }
  "42":
    continueonerror: true
    continueonerrortype: ""
    id: "42"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "43"
      "no":
      - "44"
      "yes":
      - "46"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 98485a18-ea66-46b7-8fc4-15cc08c60751
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 98485a18-ea66-46b7-8fc4-15cc08c60751
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "43":
    continueonerror: true
    continueonerrortype: ""
    id: "43"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 4a086032-88a0-4189-831c-4deff26b0913
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 4a086032-88a0-4189-831c-4deff26b0913
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "44":
    continueonerror: true
    continueonerrortype: ""
    id: "44"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Incremental Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 8a368857-840f-41ce-8f5a-f27c3d7982ad
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 8a368857-840f-41ce-8f5a-f27c3d7982ad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "45":
    continueonerror: true
    continueonerrortype: ""
    id: "45"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 8bca8a84-a1e1-48f5-8fa3-3219c2d84876
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8bca8a84-a1e1-48f5-8fa3-3219c2d84876
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "46":
    continueonerrortype: ""
    id: "46"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "47"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get ServiceNow Table Mapping Method
      id: c187cc68-f6a8-4106-8bfd-30fe68975ee9
      iscommand: true
      name: Get ServiceNow Mapping Method
      script: '|||get-mapping-method'
      type: regular
      version: -1
    taskid: c187cc68-f6a8-4106-8bfd-30fe68975ee9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "47":
    continueonerrortype: ""
    id: "47"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "36"
      "yes":
      - "48"
    note: false
    quietmode: 0
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${SN.MappingMethod}
      right:
        simple: Use ServiceNow Classes
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: b75e98f0-eacf-401b-8214-e1fe91a905d7
      iscommand: false
      name: Is ServiceNow OT Mapping?
      script: AreValuesEqual
      type: condition
      version: -1
    taskid: b75e98f0-eacf-401b-8214-e1fe91a905d7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "48":
    continueonerror: true
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "38"
    note: false
    quietmode: 0
    scriptarguments:
      increment_time:
        simple: ${incident.playbookpollinterval}
      panw_sn_category_mapping:
        simple: ${incident.panwservicenowcategorymap}
      servicenow_instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8119bacd-df7d-4321-84b2-82704f33bfd7
      iscommand: false
      name: SendIncrementalPANWIoTDevicesToServiceNowOTClasses
      script: 7d7e97a4-d562-4abe-8428-1943618082dc
      type: regular
      version: -1
    taskid: 8119bacd-df7d-4321-84b2-82704f33bfd7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1420
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1990,
        "width": 1885,
        "x": 50,
        "y": 50
      }
    }
  }
