contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: acee6fd5-71eb-4d99-832c-c30aa7961004
inputs: []
name: Export Single Alert to Nuvolo - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fa70a6ec-a4b9-49a5-8b44-441460097757
      iscommand: false
      name: ""
      version: -1
    taskid: fa70a6ec-a4b9-49a5-8b44-441460097757
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "12"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Nuvolo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: d98382b9-5c03-443d-897c-30c22f4d180d
      iscommand: false
      name: Is Nuvolo enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: d98382b9-5c03-443d-897c-30c22f4d180d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: nuvolo
      message:
        simple: Nuvolo instance is not enabled
      playbook_name:
        simple: Export Single Alert to Nuvolo - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 4dba8ca9-ed08-43be-8ab8-a6f38d59b2fc
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 4dba8ca9-ed08-43be-8ab8-a6f38d59b2fc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: f42481b4-e100-4f2a-8639-f70ffbdcc87b
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f42481b4-e100-4f2a-8639-f70ffbdcc87b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: nuvolo
      message:
        simple: 'Error: Failed to get alert instance zb_ticket id ${incident.correlation_id}.
          ${Nuvolo-IoT.sendData}'
      playbook_name:
        simple: Export Single Alert to Nuvolo - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 52423d7c-e7ea-4a10-8920-3890abe467c4
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 52423d7c-e7ea-4a10-8920-3890abe467c4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 0bf15ba6-19c4-44a9-8fa7-2e47a1af52fc
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 0bf15ba6-19c4-44a9-8fa7-2e47a1af52fc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      correlation_id:
        simple: ${incident.correlation_id}
      customer_id:
        simple: ${PanwIot3rdParty.customerid}
      device_id:
        simple: d4:f4:be:b0:c3:10
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b95f9fe1-d077-4763-859d-5eafbe641438
      iscommand: false
      name: Send alert to Nuvolo
      script: 89c1450e-b144-4b38-8559-11ecbd629c1f
      type: regular
      version: -1
    taskid: b95f9fe1-d077-4763-859d-5eafbe641438
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: ca8207f3-9020-4cca-836a-bfa66c6cde68
      iscommand: false
      name: Was there an error when get alert details?
      script: isError
      type: condition
      version: -1
    taskid: ca8207f3-9020-4cca-836a-bfa66c6cde68
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: nuvolo
      message:
        simple: Successfully send alert ${incident.correlation_id} to Nuvolo. ${Nuvolo-IoT.sendData}
      playbook_name:
        simple: Export Single Alert to Nuvolo - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 305e1f76-f02d-4cf4-8b8d-e0b4a2f06aa1
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 305e1f76-f02d-4cf4-8b8d-e0b4a2f06aa1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: ca1cc225-fe70-4a29-8529-cd58283f7d6c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ca1cc225-fe70-4a29-8529-cd58283f7d6c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Return the PANW IoT customer id.
      id: 6115a39a-3285-4a0e-89a6-406a10ccbc66
      iscommand: true
      name: Get PANW IoT customer id.
      script: panw-iot-3rd-party-get-customerid
      type: regular
      version: -1
    taskid: 6115a39a-3285-4a0e-89a6-406a10ccbc66
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1025,
        "x": 50,
        "y": 50
      }
    }
  }
