contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.16
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d7efa8d1-69a3-41b6-817d-d9883f8ea24f
inputs: []
name: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: d7efa8d1-69a3-41b6-817d-d9883f8ea24f
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a07a8e35-c61a-41e9-81f3-3899625dd38e
      iscommand: false
      name: ""
      version: -1
    taskid: a07a8e35-c61a-41e9-81f3-3899625dd38e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 80
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "16"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Tenable.io
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 68d763c9-1705-4513-87ec-9aa2e8ff6f37
      iscommand: false
      name: Is Tenable Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 68d763c9-1705-4513-87ec-9aa2e8ff6f37
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Tenable Integration is not enabled.
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 0c5414ae-0b36-41f3-849a-71b50d476f9f
      iscommand: true
      name: Report Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 0c5414ae-0b36-41f3-849a-71b50d476f9f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -20,
          "y": 1080
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: c9dbe00c-cf1a-4a35-8ef7-ce99ceed2c6a
      iscommand: false
      name: Was There an Error Getting Scanner and Profile Lists?
      script: isError
      type: condition
      version: -1
    taskid: c9dbe00c-cf1a-4a35-8ef7-ce99ceed2c6a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 200,
          "y": 905
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Failed to fetch scanner and appliance list from Tenable
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 1e2e79c4-f26d-4bb4-8b5c-f898f74601e5
      iscommand: true
      name: Report Error Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 1e2e79c4-f26d-4bb4-8b5c-f898f74601e5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 390,
          "y": 1080
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Successfully sent scanner and appliance list to PANW IoT Cloud
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 6ee434f0-29d9-4fe2-881e-81c4c0f4da7f
      iscommand: true
      name: Report Success Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 6ee434f0-29d9-4fe2-881e-81c4c0f4da7f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 800,
          "y": 1080
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: bcd6e44d-4b1a-4f87-8384-c9161c6f445a
      iscommand: true
      name: close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: bcd6e44d-4b1a-4f87-8384-c9161c6f445a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 390,
          "y": 1260
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "13"
      "no":
      - "14"
      "yes":
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Tenable.io
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 257dd8bc-01a0-49a8-8b41-17033b735aa5
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 257dd8bc-01a0-49a8-8b41-17033b735aa5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 530
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 7b8d6b4d-5af6-4e21-820e-c6f2ea4110be
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 7b8d6b4d-5af6-4e21-820e-c6f2ea4110be
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 730
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: f732174b-5fed-497b-82eb-d0ab72b020f4
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: f732174b-5fed-497b-82eb-d0ab72b020f4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 730
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 7c5674c0-676d-4e01-8974-97d9d05a88f2
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 7c5674c0-676d-4e01-8974-97d9d05a88f2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 905
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "19"
      "yes":
      - "12"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Tenable.io
      instancename:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available and provided instance
        is Active. Otherwise returns 'no'.
      id: d5b45070-c400-4177-83ee-14e952a6e578
      iscommand: false
      name: Is Tenable Integration Instance Enabled?
      script: 366ccb9c-4c22-4ebb-8a47-18faef8f67ec
      type: condition
      version: -1
    taskid: d5b45070-c400-4177-83ee-14e952a6e578
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 850,
          "y": 370
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      scanner_sync:
        simple: ${incident.automaticallysynchronizescannerswithiotsecuritytoavoidfalsesecurityalerts}
      tenable_instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Get list of Tenable Scanners and Profiles and Send to IoT
      id: ee384121-2c0d-412e-8ccb-43d99c5a8027
      iscommand: false
      name: Get list of Tenable Scanners and Profiles and Send to IoT
      script: GetTenableScannersAndProfiles
      type: regular
      version: -1
    taskid: ee384121-2c0d-412e-8ccb-43d99c5a8027
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 200,
          "y": 730
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: tenable
      message:
        simple: Tenable Integration is not enabled.
      playbook_name:
        simple: PANW IoT Get Tenable Scanners and Profiles - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message to PANW IOT cloud.
      id: 436df733-e7dc-4b71-88cb-e06b04e6f140
      iscommand: true
      name: Report Disabled Status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 436df733-e7dc-4b71-88cb-e06b04e6f140
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1390,
          "y": 730
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1275,
        "width": 1790,
        "x": -20,
        "y": 80
      }
    }
  }
