contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 51b91d3d-6af3-40d3-8ba2-ae257b80dd72
inputs: []
name: Quarantine Device in Aruba ClearPass - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4ae3d742-4e72-418f-8d68-e70b048f9ec9
      iscommand: false
      name: ""
      version: -1
    taskid: 4ae3d742-4e72-418f-8d68-e70b048f9ec9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba ClearPass
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 2e0d17b4-bfe5-4334-8b49-b75f29a4c3b0
      iscommand: false
      name: Is Aruba ClearPass Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 2e0d17b4-bfe5-4334-8b49-b75f29a4c3b0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: Quarantine
      alert_severity:
        simple: ${incident.alertSeverity}
      alert_type:
        simple: ${incident.alertType}
      integration:
        simple: clearpass
      mac_address:
        simple: ${incident.macAddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9d3746e7-95d5-40e2-87c9-61479779cca2
      iscommand: false
      name: Create AlertType and AlertSeverity Custom Attributes for endpoint
      script: QuarantinePANWIoTDevice
      type: regular
      version: -1
    taskid: 9d3746e7-95d5-40e2-87c9-61479779cca2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: clearpass
      message:
        simple: Aruba ClearPass  instance is not configured
      playbook_name:
        simple: Quarantine Device in Aruba ClearPass - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: afd31625-f39d-42d1-8446-012cd23ff5de
      iscommand: true
      name: Send disable status to IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: afd31625-f39d-42d1-8446-012cd23ff5de
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 0dbbf2ff-71e1-4bfe-8daf-22d6ecaf2a4a
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 0dbbf2ff-71e1-4bfe-8daf-22d6ecaf2a4a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
