contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 51b91d3d-6af3-40d3-8ba2-ae257b80dd72
inputs: []
name: Quarantine Device in Aruba ClearPass - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3261493c-e6df-49e6-832b-5a0eccb00783
      iscommand: false
      name: ""
      version: -1
    taskid: 3261493c-e6df-49e6-832b-5a0eccb00783
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Aruba ClearPass
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: eb6bb537-5d17-407d-8f5e-3a1e02350a3b
      iscommand: false
      name: Is Aruba ClearPass Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: eb6bb537-5d17-407d-8f5e-3a1e02350a3b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: Quarantine
      alert_severity:
        simple: ${incident.alertSeverity}
      alert_type:
        simple: ${incident.alertType}
      integration:
        simple: clearpass
      mac_address:
        simple: ${incident.macAddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7d10b842-1b95-4e03-8865-0a56441c0464
      iscommand: false
      name: Create AlertType and AlertSeverity Custom Attributes for endpoint
      script: QuarantinePANWIoTDevice
      type: regular
      version: -1
    taskid: 7d10b842-1b95-4e03-8865-0a56441c0464
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: clearpass
      message:
        simple: Aruba ClearPass  instance is not configured
      playbook_name:
        simple: Quarantine Device in Aruba ClearPass - PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: efa0d494-1a6e-4d4d-8b9f-887135381eb9
      iscommand: true
      name: Send disable status to IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: efa0d494-1a6e-4d4d-8b9f-887135381eb9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: ea9ff6fa-5e93-4f38-8197-dfdeac3b0a11
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ea9ff6fa-5e93-4f38-8197-dfdeac3b0a11
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
