contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.3
    packID: ""
    packName: Palo Alto Networks IoT 3rd Party Integrations
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook gets all available device inventory from PANW IoT Cloud
  and updates/creates endpoints with custom attributes on ServiceNow.
id: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 987aaa4c-3f61-4cc4-8787-bd77bf77a2d6
      iscommand: false
      name: ""
      version: -1
    taskid: 987aaa4c-3f61-4cc4-8787-bd77bf77a2d6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "12"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: f63bd45d-a4d8-4f0b-8434-7da70a25477a
      iscommand: false
      name: Is ServiceNow enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: f63bd45d-a4d8-4f0b-8434-7da70a25477a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      customized_servicenow_config:
        simple: ${PanwIot3rdParty.SNConfig}
      iot_servicenow_category_map:
        simple: ${PanwIot3rdParty.SNCategoryMapping}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all available devices from the IoT cloud and sends it to the
        ServiceNow.
      id: 26dc16d0-41ad-42be-8353-9466267c1e12
      iscommand: false
      name: Send all PANW IoT devices to ServiceNow
      script: SendAllPANWIoTDevicesToServiceNow
      type: regular
      version: -1
    taskid: 26dc16d0-41ad-42be-8353-9466267c1e12
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1245
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 707bf663-f67a-4a01-8df9-13b0e45a351e
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 707bf663-f67a-4a01-8df9-13b0e45a351e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1770
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: Servicenow integration is not enabled
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: f9612ed3-d983-4e7a-83be-c3334959e62f
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: f9612ed3-d983-4e7a-83be-c3334959e62f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 91bdd55a-fecb-4738-8a5c-d182d769344a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 91bdd55a-fecb-4738-8a5c-d182d769344a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: a915b0ca-c657-4dfa-8005-409bec04ead0
      iscommand: false
      name: Was there an error when sending devices to servicenow?
      script: isError
      type: condition
      version: -1
    taskid: a915b0ca-c657-4dfa-8005-409bec04ead0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1420
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to do a bulk device sync to ServiceNow. Please see
          the detailed error message from the playbook'
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: a0f4a97e-e3c2-4759-87ef-88f1a2444c48
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: a0f4a97e-e3c2-4759-87ef-88f1a2444c48
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1595
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 4c31d314-5e2e-4838-821d-aea9272bcd6d
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4c31d314-5e2e-4838-821d-aea9272bcd6d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1770
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: ${SN-IoT.bulkResult}
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 2e2f4448-4f7c-4d61-8055-cf08d71736f7
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 2e2f4448-4f7c-4d61-8055-cf08d71736f7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1595
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all customized table and column names in the customers' ServiceNow.
      id: 7a0e3042-0963-4d7a-8ff2-f00737da4283
      iscommand: false
      name: Get ServiceNow Customized Configuration
      script: GetServiceNowCustomizedConfiguration
      type: regular
      version: -1
    taskid: 7a0e3042-0963-4d7a-8ff2-f00737da4283
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 895
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      incident:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get PANW IoT and ServiceNow category mapping
      id: 42d5740e-0e80-445a-806e-13424c990604
      iscommand: false
      name: Get PANW IoT ServiceNow Category Mapping
      script: GetPANWIoTServiceNowCategoryMapping
      type: regular
      version: -1
    taskid: 42d5740e-0e80-445a-806e-13424c990604
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1070
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "no":
      - "13"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7ceab854-b760-4cb5-88c4-b617de4d63cc
      iscommand: false
      name: is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 7ceab854-b760-4cb5-88c4-b617de4d63cc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      integration_name:
        simple: servicenow
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 35e9df14-2b21-43d8-8827-0f0c1b5024d0
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 35e9df14-2b21-43d8-8827-0f0c1b5024d0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: servicenow
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: c42a9170-13fe-49fc-8f52-37e51a16400c
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: c42a9170-13fe-49fc-8f52-37e51a16400c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: d2c1b659-639a-466a-80d5-e801a0bbe1e2
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d2c1b659-639a-466a-80d5-e801a0bbe1e2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get ServiceNow Table Mapping Method
      id: 41a11ad3-6694-4432-82b2-e44bf5a49f17
      iscommand: true
      name: Get ServiceNow Mapping Method
      script: '|||get-mapping-method'
      type: regular
      version: -1
    taskid: 41a11ad3-6694-4432-82b2-e44bf5a49f17
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "18"
    note: false
    quietmode: 0
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${SN.MappingMethod}
      right:
        simple: Use ServiceNow Classes
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: d20da040-67af-4501-88f1-ce26f8463dc3
      iscommand: false
      name: Is ServiceNow OT Mapping?
      script: AreValuesEqual
      type: condition
      version: -1
    taskid: d20da040-67af-4501-88f1-ce26f8463dc3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      iot_servicenow_category_map:
        simple: ${incident.panwservicenowcategorymap}
      servicenow_instance_name:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all available devices from the IoT cloud and sends it to the
        ServiceNow OT Classes
      id: 18090a21-b6db-46f6-8cda-af96cfa48664
      iscommand: false
      name: SendAllPANWIoTDevicesToServiceNowOTClasses
      script: 9103572f-1d45-4ff6-8f2c-9ecc32bb2fd1
      type: regular
      version: -1
    taskid: 18090a21-b6db-46f6-8cda-af96cfa48664
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1860,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1815,
        "width": 2190,
        "x": 50,
        "y": 50
      }
    }
  }
