contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 6.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 6c5ee2fe-98bf-40ab-8ab0-c624a765cab3
inputs: []
name: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT Cloud
outputs: []
sourceplaybookid: 985135c8-3cc9-43b1-8783-926b487a076d
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d67c6042-4a7a-44d1-879a-07022fe64f63
      iscommand: false
      name: ""
      version: -1
    taskid: d67c6042-4a7a-44d1-879a-07022fe64f63
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 20
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "11"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - BlueCat IPAM
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: d00d2786-426b-4798-8f97-8aa166b67530
      iscommand: false
      name: Is BlueCat enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: d00d2786-426b-4798-8f97-8aa166b67530
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 960,
          "y": 400
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ipam_bluecat
      message:
        simple: BlueCat IPAM integration is not enabled
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 8b882fda-6198-4f54-894a-a27f6643d905
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 8b882fda-6198-4f54-894a-a27f6643d905
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 280,
          "y": 570
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: f13da3e7-3d0e-4faf-8d1c-345bfcb52538
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f13da3e7-3d0e-4faf-8d1c-345bfcb52538
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": 770
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      bluecat_instance_name:
        simple: ${incident.integrationinstancename}
      data_overwrite:
        simple: ${incident.useipamnonsitedataifthesameblockorsubnetisiniotsecurity}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5c78b181-846e-4707-8a56-cfcb5b7a7de8
      iscommand: false
      name: Export BlueCat Subnet Info and Update PANW IoT cloud
      script: BlueCatIPAMGetSubnetNetwork
      type: regular
      version: -1
    taskid: 5c78b181-846e-4707-8a56-cfcb5b7a7de8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 720
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: b20c73bd-bfea-497d-8d34-b3a36e1d321f
      iscommand: false
      name: Was there an error when sending devices to PANW IoT Cloud?
      script: isError
      type: condition
      version: -1
    taskid: b20c73bd-bfea-497d-8d34-b3a36e1d321f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 895
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ipam_bluecat
      message:
        simple: 'Error: Failed to do a bulk export BlueCat IPAM Data'
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: a325734e-7f44-40d9-883a-deb0c8d79b2d
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: a325734e-7f44-40d9-883a-deb0c8d79b2d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 1070
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 3dfdeaa7-7b20-4e17-8a3e-0b752ae30d8f
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 3dfdeaa7-7b20-4e17-8a3e-0b752ae30d8f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 1245
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 43288981-6797-4177-84cd-7392862441fd
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 43288981-6797-4177-84cd-7392862441fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1245
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: ipam_bluecat
      message:
        simple: Successfully exported BlueCat IPAM Data
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 8783a139-b752-405d-8f8b-2a4db41f5f87
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 8783a139-b752-405d-8f8b-2a4db41f5f87
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1070
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "no":
      - "12"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - BlueCat IPAM
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5de01de0-9964-478a-827b-08da95c96006
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 5de01de0-9964-478a-827b-08da95c96006
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 980,
          "y": 610
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ipam_bluecat
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Bulk Import of subnet network info from BlueCat IPAM to PANW IoT Cloud
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 3c1a8bcb-8abe-4f5b-88ca-337d9bf7f39e
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 3c1a8bcb-8abe-4f5b-88ca-337d9bf7f39e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 850
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 4850051d-0a70-4c3d-87d5-b630f1403fc6
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4850051d-0a70-4c3d-87d5-b630f1403fc6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1020
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ipam_bluecat
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Bulk Import of subnet network info from BlueCat IPAM to PANW IoT Cloud
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: ab6f62c3-8346-4157-81c4-3a8a241959f4
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: ab6f62c3-8346-4157-81c4-3a8a241959f4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 670,
          "y": 850
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "16"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: f352ce00-f2c5-4ddc-8e24-280f034b51d5
      iscommand: false
      name: Is BlueCat IPAM Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: f352ce00-f2c5-4ddc-8e24-280f034b51d5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 175
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: ipam_bluecat
      message:
        simple: No BlueCat IPAM integration is passed
      playbook_name:
        simple: Bulk Import of  subnet network info from BlueCat IPAM to PANW IoT
          Cloud
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: dd099c1c-365c-4ac2-8f0f-c671b4dfda71
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: dd099c1c-365c-4ac2-8f0f-c671b4dfda71
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -140,
          "y": 530
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "15_16_no": 0.14
    },
    "paper": {
      "dimensions": {
        "height": 1320,
        "width": 2300,
        "x": -140,
        "y": 20
      }
    }
  }
