contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.0.4
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5d79a068-1055-4b9c-826a-b5ccb88cd619
inputs: []
name: Bulk Import of Panorama Security Rules to PANW IoT 3rd Party Integration
outputs: []
sourceplaybookid: 985135c8-3cc9-43b1-8783-926b487a076d
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a1034a67-c233-4201-8245-ae75c35df8b1
      iscommand: false
      name: ""
      version: -1
    taskid: a1034a67-c233-4201-8245-ae75c35df8b1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "11"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: PANW IoT 3rd Party Integration - Panorama
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 07c159f6-339b-4f51-8900-5ad851ff2c83
      iscommand: false
      name: Is Panorama enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 07c159f6-339b-4f51-8900-5ad851ff2c83
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: panorama
      message:
        simple: Panorama integration is not enabled
      playbook_name:
        simple: Bulk Import of Panorama Security Rules to PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 489b98c1-4fc7-4a0c-865c-7b96effdf30d
      iscommand: true
      name: Send disabled status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 489b98c1-4fc7-4a0c-865c-7b96effdf30d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: be9405c0-381a-43b7-8f8d-58cad731e0e6
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: be9405c0-381a-43b7-8f8d-58cad731e0e6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      panorama_instance:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6ad0e09a-3900-4020-8fac-d37ed307d185
      iscommand: false
      name: Import Panorama security rules and Update PANW IoT cloud
      script: SendAllPanoramaSecurityRulesToPANWIoT
      type: regular
      version: -1
    taskid: 6ad0e09a-3900-4020-8fac-d37ed307d185
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 720
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: f653deea-a4c4-4781-8425-72043a2e741f
      iscommand: false
      name: Was there an error when sending devices to PANW IoT Cloud?
      script: isError
      type: condition
      version: -1
    taskid: f653deea-a4c4-4781-8425-72043a2e741f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 895
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: panorama
      message:
        simple: 'Error: Failed to do a bulk import of panorama security rules'
      playbook_name:
        simple: Bulk Import of Panorama Security Rules to PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 2e8b8826-e8e1-4644-89db-74e9e0036ed0
      iscommand: true
      name: Send error status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 2e8b8826-e8e1-4644-89db-74e9e0036ed0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 1070
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 339b5ac4-415d-47f4-8ebb-da8736a8237d
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 339b5ac4-415d-47f4-8ebb-da8736a8237d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 1245
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: panorama
      message:
        simple: Successfully Imported  Panorama Security Rules to PANW IoT Cloud
      playbook_name:
        simple: Bulk Import of Panorama Security Rules to PANW IoT 3rd Party Integration
      status:
        simple: success
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 534e1228-f4f1-40f3-822a-a64c42a46bcc
      iscommand: true
      name: Send success status back to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 534e1228-f4f1-40f3-822a-a64c42a46bcc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1070
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "no":
      - "12"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      integration_name:
        simple: PANW IoT 3rd Party Integration - Panorama
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9983810c-93bf-4e62-83ae-c72a23a946b9
      iscommand: false
      name: Is License Available?
      script: CheckPANWIoTIntegrationLicense
      type: condition
      version: -1
    taskid: 9983810c-93bf-4e62-83ae-c72a23a946b9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 545
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: panorama
      message:
        simple: License Limit Exceeded.
      playbook_name:
        simple: Bulk Import of Panorama Security Rules to PANW IoT 3rd Party Integration
      status:
        simple: license_limit_exceeded
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 4e8fb8ea-8515-4df6-8200-762070b4aff2
      iscommand: true
      name: License Limited Exceed. Report status to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 4e8fb8ea-8515-4df6-8200-762070b4aff2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: ace13c7c-395e-464c-856e-060754787bb1
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ace13c7c-395e-464c-856e-060754787bb1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 895
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: panorama
      message:
        simple: 'Error: Failed to get License'
      playbook_name:
        simple: Bulk Import of Panorama Security Rules to PANW IoT 3rd Party Integration
      status:
        simple: error
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: bc612d4c-bf23-4b8b-8cc1-4f969d62b967
      iscommand: true
      name: Failed to get License. Report Error to PANW IoT Cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: bc612d4c-bf23-4b8b-8cc1-4f969d62b967
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "16"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${incident.integrationinstancename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 89532a23-2e33-4103-8d03-7f7f8ceb242b
      iscommand: false
      name: Is Panorama Integration Instance Available
      script: Exists
      type: condition
      version: -1
    taskid: 89532a23-2e33-4103-8d03-7f7f8ceb242b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 195
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      custom_integration_name:
        simple: ${incident.integrationinstancename}
      integration_name:
        simple: panorama
      message:
        simple: No Panorama integration is passed
      playbook_name:
        simple: Bulk Import of Panorama Security Rules to PANW IoT 3rd Party Integration
      status:
        simple: disabled
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: e5f94a79-6e9a-41ec-898b-14ece5a98160
      iscommand: true
      name: No Instance passed to this Playbook. Reporting Error
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e5f94a79-6e9a-41ec-898b-14ece5a98160
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 2110,
        "x": 50,
        "y": 50
      }
    }
  }
